import type { ArchetypeProfile } from '../../schemas';

/** Days 31–60: each day's unique archetype. Pure copy; per-day color + sigil derive from the day. */
export const archetypes31to60: readonly ArchetypeProfile[] = [
  {
    id: 'arch-31',
    name: 'The Watcher of Impressions',
    essence: 'Discernment at the threshold, seeing the pull before the obedience.',
    light: 'Catches the impression as it arrives, before it asks to be acted on.',
    shadow: 'Watching everything and choosing nothing. Surveillance mistaken for action.',
    discipline: 'Name the impression as an impression before responding to it.',
    temptation: 'Treating the first pull as a command instead of a proposal.',
    practice: 'When the urge appears, say inwardly: an impression has arrived, not a command.',
    lapseMedicine: 'Do not study the lapse through the voice that argued for it. Wait until clear, then look.',
    dailyCommand: 'See the pull before you obey it.',
    retainLine: 'An impression is a knock. The assent is the door.',
  },
  {
    id: 'arch-32',
    name: 'The Keeper of Consent',
    essence: 'Final authority over the inward yes that turns a proposal into act.',
    light: 'Knows the signature is his and cannot be taken, only badly given.',
    shadow: 'Withholding from everything good, mistaking refusal itself for strength.',
    discipline: 'Withhold consent without entering the argument.',
    temptation: 'Believing the compulsion can bind him without his agreement.',
    practice: 'At the strongest pull, say inwardly: I do not consent. Move on.',
    lapseMedicine: 'Consent was given once, not forever. Reclaim the signature and continue.',
    dailyCommand: 'No yes, no act.',
    retainLine: 'The compulsion proposes. Only your signature makes it law.',
  },
  {
    id: 'arch-33',
    name: 'The Namer of Voices',
    essence: 'Recognition of the compulsion\'s style — its arguments, its hours, its signature.',
    light: 'Hears the familiar voice and names it before it does its work.',
    shadow: 'Naming as a substitute for refusing. Cataloguing voices instead of declining them.',
    discipline: 'Name the voice when it speaks, then refuse to answer it.',
    temptation: 'Mistaking a well-known voice for his own honest thought.',
    practice: 'Keep a short list of the compulsion\'s top arguments and the hours they arrive.',
    lapseMedicine: 'Learn the voice\'s signature from the lapse. The next round becomes survivable.',
    dailyCommand: 'Name the voice. Do not answer it.',
    retainLine: 'A voice named is a voice halved.',
  },
  {
    id: 'arch-34',
    name: 'The Warden of the Gap',
    essence: 'The trained space between impulse and action, where the choice still lives.',
    light: 'Steps into the gap deliberately instead of being carried past it.',
    shadow: 'Hesitation dressed as patience. Living in the gap to avoid the act after it.',
    discipline: 'Take three breaths before any reactive act.',
    temptation: 'Believing the gap is too small to use, so skipping it entirely.',
    practice: 'Enter the gap on purpose ten times today, in small moments — not just urges.',
    lapseMedicine: 'The gap shrank; it did not vanish. Widen it again with one slow breath.',
    dailyCommand: 'Find the space. Live there.',
    retainLine: 'The space between is a place. Learn to live there.',
  },
  {
    id: 'arch-35',
    name: 'The Keeper of the Citadel',
    essence: 'Holding the inner fortress built only of what is genuinely his.',
    light: 'Spends his force on what he can change and lets the weather pass.',
    shadow: 'Walling off so much that he stops acting on what he actually controls.',
    discipline: 'Ask first whether a difficulty is in your control, then spend force only there.',
    temptation: 'Pouring strength into outcomes the world, not the man, decides.',
    practice: 'List what is up to you today and what is not. Work only the first list.',
    lapseMedicine: 'The response is still yours even when the urge is not. Rebuild from what holds.',
    dailyCommand: 'Hold only what is yours to hold.',
    retainLine: 'The inner citadel is built only of what is up to you.',
  },
  {
    id: 'arch-36',
    name: 'The Mender of Wounds',
    essence: 'Tending the bare sensation without adding the story that doubles it.',
    light: 'Lets the first arrow be what it is and refuses to fire the second.',
    shadow: 'Tending the wound so long it becomes an identity. Mercy without movement.',
    discipline: 'Refuse the second arrow — the catastrophe the mind builds around the urge.',
    temptation: 'Generalizing one moment of wanting into a whole verdict on the man.',
    practice: 'When something hard arrives, name it briefly and do not narrate it.',
    lapseMedicine: 'The lapse is the first arrow. Do not fire the story that says it is who you are.',
    dailyCommand: 'Do not add the second arrow.',
    retainLine: 'The urge is the first arrow. The story is the second. Refuse it.',
  },
  {
    id: 'arch-37',
    name: 'The Withholder of Verdicts',
    essence: 'Suspended judgment — receiving the impression as data before evaluating it.',
    light: 'Sees the impression clearly, without drama, before deciding what it deserves.',
    shadow: 'Withholding so long that no decision ever lands. Suspension as paralysis.',
    discipline: 'Suspend judgment on the impression. Decide later, with less mood.',
    temptation: 'Firing the instant verdict that intensifies the urge it judges.',
    practice: 'Use the phrase: is, before good or bad. Apply it to events as they arrive.',
    lapseMedicine: 'Do not sentence yourself in the first ten seconds. Withhold the verdict and look.',
    dailyCommand: 'Hold the verdict. Open the room.',
    retainLine: 'Judgment is a power. Use it deliberately, or it uses you.',
  },
  {
    id: 'arch-38',
    name: 'The Walker of the Next Step',
    essence: 'Returning to the road by one clean act, not by solving the whole road.',
    light: 'When clouded, moves — small, clean, immediate, without theater.',
    shadow: 'Endless small motion that avoids the one act that actually matters.',
    discipline: 'When in doubt, do one clean act within three minutes.',
    temptation: 'Dramatizing being stuck as a way to delay the next step.',
    practice: 'When the mind clouds, do not analyze. Do one specific clean thing now.',
    lapseMedicine: 'Stand up. Take the next clean step. Do not perform the contrition.',
    dailyCommand: 'When unclear: act small, act clean, act now.',
    retainLine: 'You do not solve the road. You walk it.',
  },
  {
    id: 'arch-39',
    name: 'The Inner Witness',
    essence: 'The quiet watcher that no mood can deceive and no argument can outrun.',
    light: 'Sees the pattern, the rationalization, the argument he would lose if he kept it.',
    shadow: 'Hyper-self-consciousness that becomes its own torment and delay.',
    discipline: 'Keep the witness awake. Notice yourself noticing.',
    temptation: 'Letting moods run him unobserved because the watcher fell asleep.',
    practice: 'Three times today, ask: who in me is watching this? Stay for one breath.',
    lapseMedicine: 'The witness does not condemn. It sees. Look at the lapse as a watcher, not a judge.',
    dailyCommand: 'Keep the watcher awake.',
    retainLine: 'You are not the urge. You are the one who sees it.',
  },
  {
    id: 'arch-40',
    name: 'The Warden of the Trained Watch',
    essence: 'Command as the residue of forty days of small acts of governance.',
    light: 'Holds the gate not by nature but by having drilled the watch.',
    shadow: 'Believing the watch will hold itself now that it is trained.',
    discipline: 'Account for the command you have actually built, then keep standing it.',
    temptation: 'Mistaking a trained reflex for a finished achievement.',
    practice: 'Name three impressions you handled differently this week than in week one.',
    lapseMedicine: 'Trained command is not lost in one night. Return to the watch and keep it.',
    dailyCommand: 'Stand the watch you trained for.',
    retainLine: 'Command is trained, not given.',
  },
  {
    id: 'arch-41',
    name: 'The Steward of the Throne',
    essence: 'Keeping the seat of rule for reason, not surrendering it to appetite.',
    light: 'Asks who governs and refuses to mistake a marketplace for a kingdom.',
    shadow: 'Governing by suppression, leaving the kingdom orderly but joyless.',
    discipline: 'When appetite speaks, ask: would I let this voice rule a kingdom?',
    temptation: 'Letting the loudest part call itself king while reason waits outside.',
    practice: 'At three decisions today, name which part speaks: appetite, spirit, or reason.',
    lapseMedicine: 'A king who falls returns to the throne. He does not abandon the kingdom.',
    dailyCommand: 'Keep reason on the throne.',
    retainLine: 'A kingdom with appetite on the throne is only a marketplace.',
  },
  {
    id: 'arch-42',
    name: 'The Master of Spirit',
    essence: 'Commanding thumos — the spirited fire — into worthy work instead of noise.',
    light: 'Turns indignation and pride into courage that serves reason.',
    shadow: 'Spirit undirected: aggression, petty contests, discharge on the undeserving.',
    discipline: 'Let spirit serve reason. Give it work that earns its strength.',
    temptation: 'Spending fire on small slights instead of worthy targets.',
    practice: 'Each time spirit fires today, ask: is this in service of reason or against it?',
    lapseMedicine: 'The spirit was not the problem; the aim was. Point the fire at something worthy.',
    dailyCommand: 'Aim the fire before you spend it.',
    retainLine: 'Spirit trained becomes courage. Spirit wild becomes noise.',
  },
  {
    id: 'arch-43',
    name: 'The Day-Legislator',
    essence: 'Reason ruling by structure laid down in the calm of morning.',
    light: 'Legislates the day when whole and merely enforces it when tired.',
    shadow: 'Rigidity that cannot bend a law even when the day genuinely changes.',
    discipline: 'Let reason legislate the morning. By evening, simply enforce.',
    temptation: 'Letting the evening self overturn the morning self\'s decision.',
    practice: 'Write three structural decisions the evening self does not get to revise.',
    lapseMedicine: 'Pass the law again at dawn. The evening cannot repeal what morning rewrites.',
    dailyCommand: 'Legislate at dawn. Enforce at dusk.',
    retainLine: 'Reason rules by repetition, not by force.',
  },
  {
    id: 'arch-44',
    name: 'The Reconciler of the Three',
    essence: 'Aligning appetite, spirit, and reason so the man moves as one.',
    light: 'Holds all three in one direction without fracture or suppression.',
    shadow: 'Forcing a false peace, calling silence between the parts true order.',
    discipline: 'Check the alignment three times a day and adjust where you can.',
    temptation: 'Mistaking a desireless man for an integrated one.',
    practice: 'Morning, noon, evening: ask which parts pull together and which apart.',
    lapseMedicine: 'War between the parts is information, not failure. Realign and continue.',
    dailyCommand: 'Hold the three in one direction.',
    retainLine: 'The undivided man is not desireless. He is ordered.',
  },
  {
    id: 'arch-45',
    name: 'The Returning King',
    essence: 'Reclaiming the throne by presence, day after day, not by coronation.',
    light: 'Governs the inner kingdom that the compulsion held only while it sat empty.',
    shadow: 'Declaring victory at the return and walking away from the throne.',
    discipline: 'Account for the kingdom you are building. Keep the throne, do not crown yourself.',
    temptation: 'Treating the halfway mark as an arrival instead of a return.',
    practice: 'Name one part of the inner kingdom more ordered than it was on day one.',
    lapseMedicine: 'The throne sits empty only until you return. Take it back by being present.',
    dailyCommand: 'Return to the throne. Keep it.',
    retainLine: 'The King is the man who sits on the throne even when it is hard.',
  },
  {
    id: 'arch-46',
    name: 'The Riverbed Maker',
    essence: 'Laying the channel first so desire learns to flow inside it.',
    light: 'Sets structure in advance so the compulsion finds fewer empty hours.',
    shadow: 'Resenting the structure that carries him, calling order itself the problem.',
    discipline: 'Honor a structure that desire would dismantle if it could.',
    temptation: 'Dropping the bedtime, the gate, the morning when desire calls them constraints.',
    practice: 'Keep one load-bearing structure intact today without negotiation.',
    lapseMedicine: 'If the channel broke, rebuild it gently. The riverbed shapes the water again.',
    dailyCommand: 'Set the channel before the flood.',
    retainLine: 'Order is the bed in which desire learns to flow.',
  },
  {
    id: 'arch-47',
    name: 'The Lord of the Small Kingdom',
    essence: 'Ruling first the territory directly under his hand — room, desk, schedule, body.',
    light: 'Practices self-rule where it is real instead of fantasizing about empires.',
    shadow: 'Polishing the small kingdom to avoid the larger work it was meant to enable.',
    discipline: 'Govern the small kingdom visibly. Leave it in better order than you found it.',
    temptation: 'Dreaming of great enterprises while the immediate space stays chaos.',
    practice: 'Order one small domain completely today — room, desk, schedule, or speech.',
    lapseMedicine: 'Govern the nearest small thing. The small kingdom steadies the large disorder.',
    dailyCommand: 'Rule what is under your hand.',
    retainLine: 'The small kingdom is where the King practices being a king.',
  },
  {
    id: 'arch-48',
    name: 'The Keeper of the Four Domains',
    essence: 'Governing speech, room, body, and time as the ground of every discipline.',
    light: 'Tends the four load-bearing domains daily, not for show but because they hold.',
    shadow: 'Auditing the four endlessly without ever acting through them.',
    discipline: 'Give each of the four domains one conscious act of governance today.',
    temptation: 'Letting loose speech, chaos, idleness, and stolen hours erode the practice.',
    practice: 'Tonight, audit the four: how did speech, room, body, and time go?',
    lapseMedicine: 'Pick the weakest domain and put twenty minutes into it. The four rebuild the man.',
    dailyCommand: 'Govern speech, room, body, time.',
    retainLine: 'Govern these four and you govern enough.',
  },
  {
    id: 'arch-49',
    name: 'The Forger of the Inner Crown',
    essence: 'Building the crown inwardly, now, in the shape the man is taking.',
    light: 'Reads himself by pattern, not mood, naming what is genuinely changing.',
    shadow: 'Inflating small changes into a crown not yet earned — or deflating them away.',
    discipline: 'Name three real changes without exaggeration and without deflation.',
    temptation: 'Waiting for the crown at a finish line instead of forging it daily.',
    practice: 'Write the three changes down. Add to the list as the days reveal more.',
    lapseMedicine: 'The materials of the crown are not undone by one day. Keep gathering them.',
    dailyCommand: 'Forge the crown from within.',
    retainLine: 'The crown is grown from days, not granted at the end.',
  },
  {
    id: 'arch-50',
    name: 'The Guardian of the Throne',
    essence: 'Guarding the held throne daily, the way a city watches its gate.',
    light: 'Notes the position calmly at the halfway mark and renews the watch.',
    shadow: 'Believing past discipline has earned a license to stop watching.',
    discipline: 'Stand at the halfway mark and renew the watch. Treat the practice as held.',
    temptation: 'Declaring the throne won once instead of guarded always.',
    practice: 'Strengthen one piece of the guard — a boundary, a structure, a daily ritual.',
    lapseMedicine: 'A gate left open is repaired, not mourned. Renew the watch and continue.',
    dailyCommand: 'Guard the throne daily.',
    retainLine: 'The throne is guarded daily, not won once.',
  },
  {
    id: 'arch-51',
    name: 'The Furnace-Lighter',
    essence: 'Opening the Forge — turning conserved fire into form before it becomes pressure.',
    light: 'Gives the fire a destination so it becomes power instead of restlessness.',
    shadow: 'Endless lighting and relighting, hiding in preparation instead of producing.',
    discipline: 'Give the fire a destination before the day asks you to spend it elsewhere.',
    temptation: 'Conserving energy and letting it sour into irritability and drift.',
    practice: 'Choose one Forge category today and put thirty real minutes of fire into it.',
    lapseMedicine: 'Light the furnace on one small thing. Form interrupts the scattering of the fire.',
    dailyCommand: 'Give the fire a form.',
    retainLine: 'The fire becomes power only when it enters form.',
  },
  {
    id: 'arch-52',
    name: 'The Vessel-Maker',
    essence: 'Keeping worthy forms waiting so desire has somewhere to go but the cheap default.',
    light: 'Has projects, plans, and real work ready before the fire rises.',
    shadow: 'Building vessels forever and never pouring the fire into any of them.',
    discipline: 'Prepare the vessel before the fire rises. Make the worthy outlet convenient.',
    temptation: 'Having no channel ready, so the fire returns to its old outlet by default.',
    practice: 'Set up one project tonight so the morning has nowhere to go but the Forge.',
    lapseMedicine: 'A missing vessel is architecture, not weakness. Build one and pour again.',
    dailyCommand: 'Ready the vessel before the fire.',
    retainLine: 'Desire is the question. Form is the answer.',
  },
  {
    id: 'arch-53',
    name: 'The Maker of Real Things',
    essence: 'Crossing from intending to making, with hands genuinely engaged.',
    light: 'Lets the made thing teach him — realness over polish, completion over plan.',
    shadow: 'Hiding in dignified preparation that feels productive and returns nothing.',
    discipline: 'Make something real in thirty unbroken minutes. Smallness is fine.',
    temptation: 'Confusing the plan, which changes nothing, with progress.',
    practice: 'Thirty minutes of actual production, hands or mind engaged, no planning.',
    lapseMedicine: 'Make one small real thing. The act of making interrupts the spiral.',
    dailyCommand: 'Make something real today.',
    retainLine: 'The made thing teaches. The plan only delays.',
  },
  {
    id: 'arch-54',
    name: 'The Keeper of the Ratio',
    essence: 'Watching the balance of what he consumes against what he makes.',
    light: 'Keeps consumption small and chosen so making can build the interior.',
    shadow: 'Absorbing tools and content endlessly instead of building with them.',
    discipline: 'Shift one hour from consumption into the Forge today.',
    temptation: 'Letting passive intake fill the space where making should be.',
    practice: 'Track the consumption-to-making ratio honestly today. Adjust tomorrow.',
    lapseMedicine: 'Take the next hour off the screen and into one act of craft. The man is the residue.',
    dailyCommand: 'Make more than you consume.',
    retainLine: 'Consume less than you make. The man is the residue.',
  },
  {
    id: 'arch-55',
    name: 'The Scholar of the Fire',
    essence: 'Giving the fire to serious study that gives the mind real labor.',
    light: 'Reads to be changed, and watches the fog of his interior lift.',
    shadow: 'Reading for information and credentials while nothing actually changes.',
    discipline: 'Give the mind one real piece of study — not content, study.',
    temptation: 'Choosing the comfortable easy reading over the demanding page.',
    practice: 'Read thirty minutes of something demanding, slowly, with attention.',
    lapseMedicine: 'A foggy mind is the compulsion\'s terrain. Burn the fog with one real page.',
    dailyCommand: 'Study to be changed.',
    retainLine: 'The studied mind is the mind less easily seduced.',
  },
  {
    id: 'arch-56',
    name: 'The Forged Workman',
    essence: 'Bringing the conserved fire into work, fully present, no splitting.',
    light: 'Works from a furnace, not depletion — clarity, force, full presence.',
    shadow: 'Escaping into organizing and optimizing instead of doing the work.',
    discipline: 'Bring the fire into one hour of real work. Full presence, no splitting.',
    temptation: 'Working half-present, the condition the compulsion thrives on.',
    practice: 'One hour today with no inputs but the work itself. Notice its quality.',
    lapseMedicine: 'Put the fire into one forged hour. The work tells you what it does with it.',
    dailyCommand: 'Bring the fire into the work.',
    retainLine: 'Forged work is the man made visible in what he does.',
  },
  {
    id: 'arch-57',
    name: 'The Keeper of Stillness',
    essence: 'Pouring the fire into contemplative attention turned beyond the self.',
    light: 'Draws depth from quiet; grows less reactive, harder for the compulsion to reach.',
    shadow: 'Calling stillness superiority, using quiet to escape rather than to attend.',
    discipline: 'Give the fire ten minutes of contemplative attention. Sit, breathe, attend.',
    temptation: 'Filling every quiet moment with noise the inner life cannot rest in.',
    practice: 'Choose one contemplative form and practice it deliberately today.',
    lapseMedicine: 'Return to the breath. Do not confess to the void. Sit, and begin again.',
    dailyCommand: 'Pour the fire into stillness.',
    retainLine: 'Fire poured into stillness deepens; poured into noise it dissipates.',
  },
  {
    id: 'arch-58',
    name: 'The Servant of the Unseen Need',
    essence: 'Giving the fire to another\'s real need, quietly, without collecting credit.',
    light: 'Serves cleanly, and the act reorganizes him steadier than before.',
    shadow: 'Wanting the service known, so the help becomes a quiet performance.',
    discipline: 'Give the fire to one act of service no one will know you performed.',
    temptation: 'Staying absorbed in his own urge cycle when a real person needs help.',
    practice: 'Perform one act of help today without recording it or being thanked.',
    lapseMedicine: 'Service quiets the loops that feed the compulsion. Reach toward one real need.',
    dailyCommand: 'Serve where no one is watching.',
    retainLine: 'Anonymous service forges the man more than visible service.',
  },
  {
    id: 'arch-59',
    name: 'The Warden of the Vessel',
    essence: 'Keeping watch so the fire always has a chosen vessel, never a crack.',
    light: 'Prepares the container in advance, removing the fuel, not just the spark.',
    shadow: 'Watching anxiously for danger outside while the empty evening waits inside.',
    discipline: 'Have a vessel ready for every stretch of energy you expect to feel.',
    temptation: 'Letting conserved fire run through the easiest available crack.',
    practice: 'Map today\'s energy peaks and pair each with a chosen vessel in advance.',
    lapseMedicine: 'An empty evening with no plan is architecture, not failing. Set one small vessel.',
    dailyCommand: 'Ready a vessel for the fire.',
    retainLine: 'Build the vessel before the fire rises.',
  },
  {
    id: 'arch-60',
    name: 'The Bearer of Quiet Strength',
    essence: 'Strength matured past the need for an audience — steady, undivided, unannounced.',
    light: 'Works steadily and goes home; does not flare or demand to be seen.',
    shadow: 'Letting quiet harden into isolation, mistaking restraint for distance.',
    discipline: 'Recognize the quiet strength being built. No performance.',
    temptation: 'Needing the audience that fragile strength requires.',
    practice: 'Name what in you has gone from loud to quiet, and renew the vow with thirty days in view.',
    lapseMedicine: 'Quiet strength is not lost in noise. Settle, and do the next strong thing unseen.',
    dailyCommand: 'Be strong without announcement.',
    retainLine: 'Quiet strength is the kind that lasts.',
  },
];
