import type { ArchetypeProfile } from '../../schemas';

/** Days 16–30: each day's unique archetype. Pure copy; per-day color + sigil derive from the day. */
export const archetypes16to30: readonly ArchetypeProfile[] = [
  {
    id: 'arch-16',
    name: 'The Witness',
    essence: 'Detached attention, honest observation, the gap between impression and assent.',
    light: 'Watches the urge rise without obeying it. Names the appearance instead of agreeing with it.',
    shadow: 'Watching that becomes paralysis. Observing the life he refuses to live. Cold detachment posing as wisdom.',
    discipline: 'Catch the impression before it becomes a command. Withhold assent.',
    temptation: 'Mistaking the first impulse for the final authority.',
    practice: 'When the urge arrives, name it aloud as an impression — then choose the next act.',
    lapseMedicine: 'Not punishment. Study the moment of assent, not the moment of desire, and return.',
    dailyCommand: 'An impression is not a command.',
    retainLine: 'The Witness does not argue with the urge. He simply refuses to sign its order.',
  },
  {
    id: 'arch-17',
    name: 'The Gatekeeper of the Night',
    essence: 'Foresight, pre-decision, governing the dark before it governs the man.',
    light: 'Sets the gate while judgment is full. Decides the evening in the clear light of morning.',
    shadow: 'Rigidity that fears the dark instead of preparing for it. Dread dressed as discipline.',
    discipline: 'Plan the temptation hour in advance. Never negotiate inside the dark.',
    temptation: 'Improvising the late hours while tired, when every threshold is lowest.',
    practice: 'Each morning, decide where the phone sleeps and when the day ends — before the night arrives.',
    lapseMedicine: 'If the night turned hard, this is practice, not failure: rest, and set the gate earlier tomorrow.',
    dailyCommand: 'Govern the evening in the morning.',
    retainLine: 'The Gatekeeper does not fight the fire at eleven. He bars the gate at noon.',
  },
  {
    id: 'arch-18',
    name: 'The Steward of the Body',
    essence: 'Maintenance, self-honesty, reading the state beneath the urge.',
    light: 'Treats hunger, anger, loneliness, and fatigue as information, not identity. Tends before he is tested.',
    shadow: 'Using the state as an excuse. Endless self-tending that never reaches the act.',
    discipline: 'Address the state directly — eat, walk it off, reach out, rest — before the temptation hour.',
    temptation: 'Neglecting maintenance until the body\'s signals become demands.',
    practice: 'Name which state you are in each hour, and repair it the moment you find it open.',
    lapseMedicine: 'Not shame. Ask which state was unguarded, dress it, and return.',
    dailyCommand: 'Address the state, not just the urge.',
    retainLine: 'The Steward gives the compulsion less to work with by tending the wound first.',
  },
  {
    id: 'arch-19',
    name: 'The Maker',
    essence: 'Production, flow, energy turned into a finished thing.',
    light: 'Begins before he is ready. Moves the pull into the hands before it can peak.',
    shadow: 'Perfectionism as avoidance. Consuming tools and knowledge instead of building with them.',
    discipline: 'Make, do not plan. Maximize the attention, never mind the quality of the output.',
    temptation: 'Postponing the work until conditions are perfect, which they never are.',
    practice: 'Thirty uninterrupted minutes of genuine making — hands busy, mind absorbed.',
    lapseMedicine: 'Make one small thing. The act of creating interrupts the shame spiral and returns the man.',
    dailyCommand: 'Make something real.',
    retainLine: 'The Maker knows energy becomes clean when it enters the hands.',
  },
  {
    id: 'arch-20',
    name: 'The Kinsman',
    essence: 'Loyalty, honest contact, refusing to disappear.',
    light: 'Reaches out before pride makes the cost too high. Speaks truth to one trusted man.',
    shadow: 'Dependence. Approval-seeking. Tribal grievance standing in for real friendship.',
    discipline: 'Break isolation with one honest conversation — not to confess, to reconnect.',
    temptation: 'Suffering silently to protect an image of self-sufficiency.',
    practice: 'Reach one man today with honesty rather than performance.',
    lapseMedicine: 'Isolation makes the urge louder. Find one voice, reconnect, and return.',
    dailyCommand: 'Do not disappear.',
    retainLine: 'A kinsman\'s hand is sometimes the difference between a lapse and a return.',
  },
  {
    id: 'arch-21',
    name: 'The Forgemaster',
    essence: 'Repetition under heat, the new groove cut beside the old.',
    light: 'Recognizes what three weeks of intentional acts have already built. Keeps walking the new path.',
    shadow: 'Pride in the milestone. Believing the old groove is gone instead of merely overgrown.',
    discipline: 'Walk the pause groove so often the compulsion groove grows over from disuse.',
    temptation: 'Easing the heat the moment the new shape begins to hold.',
    practice: 'Complete your most demanding Forge act yet — longer, harder, or more meaningful than before.',
    lapseMedicine: 'The groove is still cut. Step back onto it in the next five minutes, not tomorrow.',
    dailyCommand: 'Walk the new groove daily.',
    retainLine: 'The Forgemaster knows what was impossible on day one is now merely difficult.',
  },
  {
    id: 'arch-22',
    name: 'The Charioteer',
    essence: 'Holding the reins of appetite and spirit so reason can steer.',
    light: 'Drives both horses without letting either run the chariot. Lets reason hold the last word.',
    shadow: 'Whipping the team into submission. Mistaking a single runaway horse for the whole self.',
    discipline: 'When the urge pulls, name it as appetite — and take the reins back for reason.',
    temptation: 'Letting one horse seize the reins and call its hunger the destination.',
    practice: 'At each decision, name which part is speaking — appetite, spirit, or reason — and let reason steer.',
    lapseMedicine: 'A horse bolted. Not a verdict on the driver. Gather the reins and steer again.',
    dailyCommand: 'Let reason steer the team.',
    retainLine: 'The Charioteer is not dragged by appetite. He drives it where reason points.',
  },
  {
    id: 'arch-23',
    name: 'The Champion',
    essence: 'Trained spirit, dignified defiance, courage in service of reason.',
    light: 'Refuses the urge from self-respect, not fear. Carries his fire into the contest.',
    shadow: 'Aggression mistaken for strength. Pride in the wrong things. Domination without purpose.',
    discipline: 'Bend thumos to serve reason — meet the urge with courage, not white-knuckled fear.',
    temptation: 'Spending spirited energy on small contests instead of worthy causes.',
    practice: 'Find one place today where courage, not mere willpower, is required — and act from there.',
    lapseMedicine: 'Not punishment. A return from self-respect: stand, reset, and carry the fire forward.',
    dailyCommand: 'Refuse from self-respect, not fear.',
    retainLine: 'The Champion does not suppress the fire. He spends it in a worthy fight.',
  },
  {
    id: 'arch-24',
    name: 'The Lawgiver',
    essence: 'Reason practiced into authority, the inner kingdom governed daily.',
    light: 'Earns the throne through repeated acts of choosing the good over comfort.',
    shadow: 'Cold legalism. Suppressing the parts instead of governing them. One victory mistaken for completion.',
    discipline: 'Hand reason one clear act each day that appetite and spirit would not have chosen.',
    temptation: 'Believing past discipline earns future license to stop choosing.',
    practice: 'Morning: ask what reason would say of today. Evening: ask whether you lived by it.',
    lapseMedicine: 'The law is not broken by one fall. Account honestly, and govern again tomorrow.',
    dailyCommand: 'Govern the kingdom daily.',
    retainLine: 'The Lawgiver does not rule by knowing the good. He rules by choosing it again.',
  },
  {
    id: 'arch-25',
    name: 'The Ritualist',
    essence: 'Chosen form, rhythm over willpower, structure that shapes desire.',
    light: 'Builds the same act in the same order until the form itself begins to move desire toward discipline.',
    shadow: 'Empty ceremony. Clinging to the rite when its meaning has drained out.',
    discipline: 'Trust the groove over the mood — the rite is strongest when willpower is lowest.',
    temptation: 'Skipping the form on the very day it is most needed.',
    practice: 'Formalize the morning rite: stand, breathe, read the vow, name the command, anticipate the temptation.',
    lapseMedicine: 'Return to the form, not the failure. Perform the next rite cleanly and continue.',
    dailyCommand: 'Let the form carry you.',
    retainLine: 'The Ritualist is pulled through the hard hour not by force, but by groove.',
  },
  {
    id: 'arch-26',
    name: 'The Wayfarer',
    essence: 'The clean return, lapse as information, the road kept after the stumble.',
    light: 'Stands up, names the lesson, repairs one thing, and walks on — no theater, no delay.',
    shadow: 'Aimlessness disguised as freedom. Dramatizing the fall to avoid the road.',
    discipline: 'Treat the lapse as information, not a verdict. Return in the next five minutes.',
    temptation: 'Drowning the lesson in shame until a single slip becomes a long absence.',
    practice: 'After any stumble, name one thing to repair and begin it immediately.',
    lapseMedicine: 'Stand up, clean one wound, name the lesson, begin again. No internal prosecution.',
    dailyCommand: 'Return without theater.',
    retainLine: 'The Wayfarer is not the man who never falls. He is the man who keeps the road.',
  },
  {
    id: 'arch-27',
    name: 'The Almsgiver',
    essence: 'Outward attention, costly service, the self-circuit broken by another\'s need.',
    light: 'Interrupts self-absorption with concrete, uncredited help. Present to someone else\'s reality.',
    shadow: 'Service as performance. Virtue signaling. Helping to be seen rather than to give.',
    discipline: 'Turn genuine attention onto another\'s real need before the compulsion can run.',
    temptation: 'Keeping the day entirely inward — my appetite, my relief, my comfort.',
    practice: 'Find one person who needs something concrete, and offer it without seeking credit.',
    lapseMedicine: 'Turn outward. One real act of service quiets the arena where the compulsion lives.',
    dailyCommand: 'Look outward, not inward.',
    retainLine: 'The Almsgiver gives the compulsion nowhere to run by tending another man\'s need.',
  },
  {
    id: 'arch-28',
    name: 'The Hermit',
    essence: 'Stillness, tolerated silence, the interior life maintained.',
    light: 'Can be alone without leaking. Draws depth from quiet instead of fleeing it into noise.',
    shadow: 'Withdrawal becoming avoidance. Superiority. Calling isolation purity while hiding from life.',
    discipline: 'Sit in real silence — no phone, no music, no content — and let the urge grow legible.',
    temptation: 'Filling every gap with stimulation so the interior never has to be faced.',
    practice: 'Ten minutes of genuine silence at some point today, with no phone in reach.',
    lapseMedicine: 'Return to the breath. Do not confess to the void. Choose one real act in the quiet.',
    dailyCommand: 'Give silence ten real minutes.',
    retainLine: 'The Hermit knows the urge speaks loudest when everything else is loud.',
  },
  {
    id: 'arch-29',
    name: 'The Keeper of the Word',
    essence: 'Integrity in small things, repetition hardened into character.',
    light: 'States a small promise and keeps it. Builds self-trust one honored word at a time.',
    shadow: 'Rigidity over honest promises. Over-vowing to perform virtue instead of practicing it.',
    discipline: 'State one small promise before the urge peaks — then keep it exactly.',
    temptation: 'Making grand vows to feel disciplined instead of keeping small ones to become it.',
    practice: 'Name the one promise you most need to keep today. State it in the morning, keep it by night.',
    lapseMedicine: 'A broken word is not a broken man. State one small promise now and keep it cleanly.',
    dailyCommand: 'Keep one promise today.',
    retainLine: 'The Keeper of the Word builds the self-trust that is load-bearing.',
  },
  {
    id: 'arch-30',
    name: 'The Oathkeeper',
    essence: 'The vow tested under load, thirty days hardened into a spine.',
    light: 'Renews the word knowing exactly what it costs. Accounts without shame and without exaggeration.',
    shadow: 'Spiritual ego at the milestone. Believing the oath kept once is the oath kept forever.',
    discipline: 'Measure the vow by what it has survived, not by how it felt on day one.',
    temptation: 'Treating thirty days as a summit to rest on rather than a spine to carry.',
    practice: 'Read the milestone rite, audit the run honestly, and renew the vow under full knowledge.',
    lapseMedicine: 'A return inside the run does not unmake the oath. Account honestly and renew the word.',
    dailyCommand: 'Renew the oath knowing its cost.',
    retainLine: 'The Oathkeeper carries the vow as a spine, not a sentence.',
  },
];
