import type { ArchetypeProfile } from '../../schemas';

/** Days 1–15: each day's unique archetype. Pure copy; per-day color + sigil derive from the day. */
export const archetypes01to15: readonly ArchetypeProfile[] = [
  {
    id: 'arch-01',
    name: 'The Vowkeeper',
    essence: 'A word chosen when clear, carried when clouded.',
    light: 'Begins without perfect conditions. Holds the commitment past the mood that follows.',
    shadow: 'Treating the vow as a feeling, then abandoning it when the feeling cools.',
    discipline: 'Speak the commitment plainly, then keep it when it costs you something.',
    temptation: 'Waiting for the ideal morning that never comes, and calling the delay wisdom.',
    practice: 'Speak your vow aloud once today before the phone touches your hand.',
    lapseMedicine: 'A vow survives a fall. Speak it again, mean it again, and walk on.',
    dailyCommand: 'Choose the word and mean it.',
    retainLine: 'The Vowkeeper does not wait to feel ready. He speaks, and the word outweighs the mood.',
  },
  {
    id: 'arch-02',
    name: 'The Fire-Tender',
    essence: 'Stewardship of the living flame — keep it, do not kill it.',
    light: 'Meets desire without contempt. Knows the energy is the ally, not the wound.',
    shadow: 'Splitting himself in two and declaring half of his own aliveness the enemy.',
    discipline: 'Name what rises, then decide where it goes — never war on the body.',
    temptation: 'Mistaking self-hatred for discipline, and shame for strength.',
    practice: 'When desire rises, pause and ask where this fire could go if you led it.',
    lapseMedicine: 'You did not become the enemy. The fire is still yours. Tend it and return.',
    dailyCommand: 'Lead the fire, do not fight it.',
    retainLine: 'The Fire-Tender does not declare war on his own aliveness. He aims it.',
  },
  {
    id: 'arch-03',
    name: 'The Gap-Keeper',
    essence: 'Sovereign of the half-second between the urge and the act.',
    light: 'Finds the gap when others are already moving. Gives or withholds the assent freely.',
    shadow: 'Pretending the gap does not exist, so the impulse rules by default.',
    discipline: 'Hold one breath in the space between impression and assent.',
    temptation: 'Believing the urge must be obeyed simply because it speaks loudly.',
    practice: 'When the first urge appears, delay one full breath before any response.',
    lapseMedicine: 'The gap is always there to return to. Find it again on the next urge.',
    dailyCommand: 'Take the throne in the pause.',
    retainLine: 'The Gap-Keeper lets the urge speak first. He never lets it speak last.',
  },
  {
    id: 'arch-04',
    name: 'The Eye-Warden',
    essence: 'Keeper of the first gate, where the eye decides the siege.',
    light: 'Catches the spark at the threshold. Looks away before the flame can rise.',
    shadow: 'Mistaking the watch for hatred of beauty, growing brittle and afraid to see.',
    discipline: 'Notice the first capture of the gaze and redirect it at step one, not step ten.',
    temptation: 'Telling yourself one more look is harmless because the wall still stands.',
    practice: 'Practice one deliberate look-away today — catch the spark and turn the gaze.',
    lapseMedicine: 'The gate opened before you did. That is practice, not failure. Watch again tomorrow.',
    dailyCommand: 'Guard the gaze early.',
    retainLine: 'The Eye-Warden does not hate what is beautiful. He decides where his eyes may rest.',
  },
  {
    id: 'arch-05',
    name: 'The Stormrider',
    essence: 'Carries the rising surge into hard motion before it turns inward.',
    light: 'Moves in the first three minutes. Spends pressure through muscle, not fantasy.',
    shadow: 'Outrunning every feeling, never pausing long enough to know himself.',
    discipline: 'Give the restless body something hard to do before the mind can bargain.',
    temptation: 'Sitting still long enough for the easy way to start sounding reasonable.',
    practice: 'At the next strong urge, begin a physical act within three minutes — before it peaks.',
    lapseMedicine: 'No punishment, only a reset: move, sweat, breathe, and the body settles.',
    dailyCommand: 'Move before you negotiate.',
    retainLine: 'The Stormrider does not store the surge in stillness. He rides it into the work.',
  },
  {
    id: 'arch-06',
    name: 'The Voice-Namer',
    essence: 'Knows the compulsion\'s whisper by its hour, not its argument.',
    light: 'Hears "just once" and sees a mechanism, not a reason. Naming breaks the spell.',
    shadow: 'Endless analysis of the voice that becomes its own quiet way of stalling.',
    discipline: 'Name the voice the moment it speaks, instead of debating its case.',
    temptation: 'Believing the reasonable, intimate whisper because it sounds like your own thought.',
    practice: 'When you hear "just once" today, say inwardly: I know this voice.',
    lapseMedicine: 'The voice won a round, not the war. Name it next time before it finishes speaking.',
    dailyCommand: 'Name the voice, do not argue.',
    retainLine: 'The Voice-Namer does not refute the lie. He recognizes it and walks past.',
  },
  {
    id: 'arch-07',
    name: 'The Gate-Reckoner',
    essence: 'Accounts honestly for the week held and names what it proved.',
    light: 'Takes stock without boasting. Knows the groove is cut, the proof is his to keep.',
    shadow: 'Mistaking one week for a finished character, or shrinking the proof to nothing.',
    discipline: 'Reckon the week plainly — without shame and without exaggeration.',
    temptation: 'Resting on the milestone as if the road were already walked.',
    practice: 'Account for the week, then enter day eight with the intention of day one.',
    lapseMedicine: 'Even a stumbled week still taught you something true. Keep the lesson, renew the vow.',
    dailyCommand: 'Account without theater.',
    retainLine: 'The Gate-Reckoner does not celebrate the gate. He proves he can stand at it.',
  },
  {
    id: 'arch-08',
    name: 'The Forgewright',
    essence: 'Gives desire a furnace and a shape — energy refined, not spent.',
    light: 'Hands the restless fire a project before it finds the cheapest exit.',
    shadow: 'Hiding in endless planning and optimizing instead of putting hand to the work.',
    discipline: 'Ask what desire could become, then begin the making before the mood fades.',
    temptation: 'Believing the fire only ever wants discharge, never a destination.',
    practice: 'Name one thing worth building and spend thirty real minutes beginning it.',
    lapseMedicine: 'Lead is not wasted in the forge. Pick up the work again and refine.',
    dailyCommand: 'Give the fire a destination.',
    retainLine: 'The Forgewright does not extinguish the fire. He builds it a furnace.',
  },
  {
    id: 'arch-09',
    name: 'The Gatewright',
    essence: 'Redesigns the gate he carries in his pocket rather than out-fighting it.',
    light: 'Builds structure instead of trusting raw willpower against an engineered pull.',
    shadow: 'Blaming the device for the breach while leaving the gate wide open.',
    discipline: 'Close the gate before the knock — remove the temptation from the kingdom.',
    temptation: 'Believing willpower alone can outlast a thing designed to outlast willpower.',
    practice: 'Keep the phone out of reach for the first thirty minutes of the morning.',
    lapseMedicine: 'A gate left open is a thing to repair, not a verdict on the man. Redesign it.',
    dailyCommand: 'Close the gate before the knock.',
    retainLine: 'The Gatewright does not out-fight the temptation. He removes it from the room.',
  },
  {
    id: 'arch-10',
    name: 'The Hermit-Architect',
    essence: 'Gives solitude a shape so the empty hour cannot drift.',
    light: 'Designs the quiet hour before restlessness arrives. Alone and engaged, not adrift.',
    shadow: 'Calling withdrawal peace while the unstructured silence breeds fantasy.',
    discipline: 'Hand every empty hour a form — a ritual, a task, a chosen presence.',
    temptation: 'Drifting into the imagination because the solitude had no plan.',
    practice: 'Plan one activity for tonight\'s solitude before the restlessness can arrive.',
    lapseMedicine: 'The drift won an evening. Build the structure earlier next time and return.',
    dailyCommand: 'Give solitude a structure.',
    retainLine: 'The Hermit-Architect does not fear being alone. He decides what fills the silence.',
  },
  {
    id: 'arch-11',
    name: 'The Fire-Reader',
    essence: 'Reads the urge as a messenger before answering it as a command.',
    light: 'Hears the deeper hunger beneath the urge — body, work, solitude, or connection.',
    shadow: 'Endless interpreting that becomes a way to avoid meeting the real need.',
    discipline: 'Stop at the first interpretation and ask for the truer one beneath it.',
    temptation: 'Taking the urge at its word and answering a hunger it only disguises.',
    practice: 'When desire rises, ask what this energy is truly asking you to face or build.',
    lapseMedicine: 'If the fire won today, you are not the enemy. Name the real need, learn, and return.',
    dailyCommand: 'Read the fire before you answer.',
    retainLine: 'The Fire-Reader does not obey the messenger. He listens for what it carries.',
  },
  {
    id: 'arch-12',
    name: 'The Vessel-Keeper',
    essence: 'Makes inner command visible in the order of the space he inhabits.',
    light: 'Governs the room as he governs himself. A cleared space is sovereignty made plain.',
    shadow: 'Tidying as control for its own sake, or order in others before himself.',
    discipline: 'Govern one space and leave it better than you found it.',
    temptation: 'Letting entropy rule the room while telling yourself the inner work is enough.',
    practice: 'Spend fifteen minutes restoring one area of visible order today.',
    lapseMedicine: 'Clean one space. The outer order steadies the inner disorder. Then go on.',
    dailyCommand: 'Govern the space you hold.',
    retainLine: 'The Vessel-Keeper knows the room is a mirror. He rules it as he rules himself.',
  },
  {
    id: 'arch-13',
    name: 'The Beholder',
    essence: 'Fully alive to beauty, never converting it into appetite.',
    light: 'Sees deeply and reveres what he sees without reaching to possess it.',
    shadow: 'Sliding from reverence into grasping, turning every beauty into a thing to take.',
    discipline: 'Notice the reach to possess, and let it pass without following it.',
    temptation: 'Mistaking the wish to consume beauty for the capacity to love it.',
    practice: 'Appreciate one beautiful thing today without trying to own or record it.',
    lapseMedicine: 'Beholding is a trained move. Practice resting in the sight again, without the reach.',
    dailyCommand: 'Behold, do not grasp.',
    retainLine: 'The Beholder sees clearly because he is not trying to take.',
  },
  {
    id: 'arch-14',
    name: 'The Gate-Cartographer',
    essence: 'Maps his own battlefield and knows the enemy by name.',
    light: 'Fights specifically, not in the abstract. Knows the hour, the mood, the gate.',
    shadow: 'Reading the map endlessly while never positioning the guard upon it.',
    discipline: 'Meet the known gate with structure already in place, not willpower in the moment.',
    temptation: 'Treating hard-won self-knowledge as defeat instead of intelligence.',
    practice: 'Name your most reliable trigger and build one structure to meet it.',
    lapseMedicine: 'A gap in the map is information. Mark it, fortify it, and walk on without shame.',
    dailyCommand: 'Stand at the known gate.',
    retainLine: 'The Gate-Cartographer does not fear the army. He knows exactly where it enters.',
  },
  {
    id: 'arch-15',
    name: 'The Beast-Tamer',
    essence: 'Fashions the untrained animal of the body into a partner.',
    light: 'Gives the body hard, honest work so its restlessness has somewhere to go.',
    shadow: 'Despising the body as an obstacle, or driving it as a master drives a slave.',
    discipline: 'Train, rest, and feed the body well — treat physiology, not as a moral test.',
    temptation: 'Blaming weakness when the truth is a body unslept, unfed, and unmoved.',
    practice: 'Address one physical state today — sleep, food, or movement — that works against you.',
    lapseMedicine: 'Not a verdict on your will. Reset the body: move, rest, eat well, and return.',
    dailyCommand: 'Train the body as an ally.',
    retainLine: 'The Beast-Tamer does not war on the animal. He trains it to carry the fire.',
  },
];
