import type { ArchetypeProfile } from '../../schemas';

/** Days 61–90: each day's unique archetype. Pure copy; per-day color + sigil derive from the day. */
export const archetypes61to90: readonly ArchetypeProfile[] = [
  {
    id: 'arch-61',
    name: 'The Brother-Keeper',
    essence: 'Refusing to vanish, and refusing to let another vanish unseen.',
    light: 'Notices the slow withdrawal early. Sends the message before the room rots.',
    shadow: 'Self-sufficiency worn as armor. Pride that hides struggle until the cost is high.',
    discipline: 'Reach out before isolation sets in. Stay in contact when the urge is to disappear.',
    temptation: 'Suffering privately to protect an image of needing no one.',
    practice: 'Send one honest message today to someone who matters. Presence, not performance.',
    lapseMedicine: 'Isolation multiplies a lapse. Presence divides it. Reach one voice, not to confess but to remain.',
    dailyCommand: 'Do not disappear.',
    retainLine: 'The man who stays in contact has half-won the night.',
  },
  {
    id: 'arch-62',
    name: 'The Hand-Giver',
    essence: 'Honest presence over mutual performance. A hand offered without conditions.',
    light: 'Says one true thing when it matters. Offers a hand that asks for no strength in return.',
    shadow: 'Curated honesty. Trading polished weeks that return nothing to either man.',
    discipline: 'Tell one true thing to one real person. Drop the sanded-down version.',
    temptation: 'Mistaking the exchange of best selves for actual brotherhood.',
    practice: 'Give one real sentence to one real person today. Not the worst thing — a true thing.',
    lapseMedicine: 'A hand that requires no performance is the one that returns a fallen man. Offer it; accept it.',
    dailyCommand: 'Say the true thing.',
    retainLine: 'A brother\'s hand does not require the receiver to perform strength.',
  },
  {
    id: 'arch-63',
    name: 'The Forewarner',
    essence: 'Naming the danger while it is still abstract. Honesty spoken before the fall.',
    light: 'Recruits help before the crisis. Names the hard hour while still standing.',
    shadow: 'Saving honesty for the post-lapse confession, when contrition makes it easy.',
    discipline: 'Speak about the practice before any crisis. Ask for a check-in in advance.',
    temptation: 'Waiting for the loss to grant permission to finally be honest.',
    practice: 'Name the hardest hour of your week to one brother, and ask him to check in then.',
    lapseMedicine: 'The man who speaks before he falls rarely has to call after. If you did not, speak now and learn.',
    dailyCommand: 'Speak before the fall.',
    retainLine: 'Pre-crisis honesty admits, while still standing, that the standing is not guaranteed.',
  },
  {
    id: 'arch-64',
    name: 'The Companioned',
    essence: 'Humility that lets the road be walked with others, not alone.',
    light: 'Asks for company without shame. Unlocks the door pride bolted from inside.',
    shadow: 'A costume of strength worn over a weakness. Restarting in private to be seen as needing no one.',
    discipline: 'Find the door pride has locked. Open it. Make the ask you have been refusing.',
    temptation: 'Treating the request for help as a kind of failure.',
    practice: 'Identify one ask you have refused out of pride. Make it today, honestly.',
    lapseMedicine: 'After a fall, pride says recover alone. Refuse it: speak to one person within forty-eight hours.',
    dailyCommand: 'Open the locked door.',
    retainLine: 'Asking for company is not a failure of the road. It is part of how the road is walked.',
  },
  {
    id: 'arch-65',
    name: 'The Witnessed',
    essence: 'Strength that knows itself to be partly relational. Being truly seen.',
    light: 'Borrows steadiness from grounded company. Builds witness deliberately, not by accident.',
    shadow: 'Mistaking permanent isolation for strength. Refusing to be seen and calling it independence.',
    discipline: 'Arrange real witness. Audit who actually sees you, and strengthen the weakest part.',
    temptation: 'Believing the man who needs no witness is the strong man.',
    practice: 'Arrange one piece of real witness today — a call, a meeting, an honest conversation.',
    lapseMedicine: 'The opposite of compulsion is not willpower; it is connection. Be witnessed, then continue.',
    dailyCommand: 'Arrange to be seen.',
    retainLine: 'No man governs himself well in permanent isolation. Witness is structure, not luxury.',
  },
  {
    id: 'arch-66',
    name: 'The Servant',
    essence: 'Attention turned outward toward another\'s real need, with no claim on return.',
    light: 'Occupies the channel the compulsion wants with someone else\'s reality. Serves unseen.',
    shadow: 'Service as performance. Helping in order to be thanked rather than to help.',
    discipline: 'Serve someone today. Address a real need without making it about yourself.',
    temptation: 'Looping attention back to appetite and discomfort instead of out toward a need.',
    practice: 'Find one person whose need you can meet today, anonymously if you can.',
    lapseMedicine: 'In the loud late hour, find one person to genuinely help. The urge often dissolves unaddressed.',
    dailyCommand: 'Serve someone.',
    retainLine: 'Attention given outward returns the man to himself larger.',
  },
  {
    id: 'arch-67',
    name: 'The Mender',
    essence: 'Repairing one bond at a time. Honoring a relationship through the work of return.',
    light: 'Pays down small relational debts. One honest sentence restores what seemed lost.',
    shadow: 'The sweeping apology tour that fixes nothing. Avoidance disguised as deliberation.',
    discipline: 'Pick one repair. Not all of them. Make it this week, then pick the next.',
    temptation: 'Carrying fifty avoided conversations because no single one feels urgent.',
    practice: 'List three relational debts. Choose the one most likely to repay attention. Address it today.',
    lapseMedicine: 'A lapse is one more thing to mend, not a verdict. Repair one bond and keep moving.',
    dailyCommand: 'Repair one bond.',
    retainLine: 'Small honest repair returns more than any heroic apology tour.',
  },
  {
    id: 'arch-68',
    name: 'The Lodge-Builder',
    essence: 'Pairing solitude with community, the way every tradition that lasted did.',
    light: 'Tells the sanctuary from the cell. Binds his aloneness to real contact.',
    shadow: 'The solitary romance that becomes a costume for hiding. Discipline mistaken for disappearance.',
    discipline: 'Honor restorative solitude and genuine community both. Leave the cell when it has become one.',
    temptation: 'Telling himself he is being disciplined when he is actually hiding from life.',
    practice: 'Examine your ratio of solitude to community. Take one concrete act of contact today.',
    lapseMedicine: 'Solitude without witness drifts toward distortion. After a fall, rejoin the lodge, then rest alone.',
    dailyCommand: 'Leave the cell.',
    retainLine: 'Solitude returns the man strong. Isolation removes him.',
  },
  {
    id: 'arch-69',
    name: 'The Whetstone',
    essence: 'Company that sharpens — the shared project of becoming stronger, not the shared complaint.',
    light: 'Steers conversation toward what is being built. Leaves men stronger than he found them.',
    shadow: 'The grievance circle that feels like loyalty and builds nothing. Bitterness mistaken for bonding.',
    discipline: 'Refuse every grievance circle. Ask one forward question for each backward complaint.',
    temptation: 'Camaraderie around what is wrong with the world, returning home slightly more bitter.',
    practice: 'In every conversation today, turn the talk toward what is being made, not what is being mourned.',
    lapseMedicine: 'Grievance is the compulsion in a social costume. After a fall, find company that builds, not that complains.',
    dailyCommand: 'Build, do not complain.',
    retainLine: 'Brotherhood worth keeping is brotherhood that builds.',
  },
  {
    id: 'arch-70',
    name: 'The Embedded',
    essence: 'Strength no longer held alone, but woven into the brothers around him.',
    light: 'Lets discipline reach into service, presence, and witness. Held by more than himself.',
    shadow: 'Hoarding strength until it fractures. Keeping the practice private and slowly losing it.',
    discipline: 'Let the practice extend outward. Account for what brotherhood and service have built.',
    temptation: 'Believing strength is safest when held only for the self.',
    practice: 'Name what the last ten days extended beyond you. Renew the vow with seventy days kept.',
    lapseMedicine: 'Strength shared is held by more than one man. After a fall, the brotherhood still holds it with you.',
    dailyCommand: 'Share the strength.',
    retainLine: 'Strength shared is strengthened. Strength hoarded is lost.',
  },
  {
    id: 'arch-71',
    name: 'The Shadow-Namer',
    essence: 'Naming the disowned material so it loses its grip the moment it is seen.',
    light: 'Looks at what he has managed not to see. Names without wallowing or worship.',
    shadow: 'The unnamed pattern running the man from underneath, surfacing as compulsion and reactivity.',
    discipline: 'Name one disowned thing honestly. To yourself first, then perhaps one other.',
    temptation: 'Looking away from the self and managing not to belong to what is there.',
    practice: 'Sit ten minutes with one difficult inward truth without rushing to resolve it.',
    lapseMedicine: 'A lapse names a shadow out loud. Read it as intelligence, not confession, and it becomes workable.',
    dailyCommand: 'Name what you have not let yourself see.',
    retainLine: 'The shadow named is the shadow workable.',
  },
  {
    id: 'arch-72',
    name: 'The Absolver',
    essence: 'Separating the guilt that repairs from the shame that only hides.',
    light: 'Lets specific guilt motivate repair. Sets down diffuse shame about being.',
    shadow: 'Shame that says the man himself is wrong — the compulsion\'s most loyal employee.',
    discipline: 'Use guilt; refuse shame. Translate "I am the problem" into "what is the repair?"',
    temptation: 'Running on an undercurrent of shame that makes the next lapse more likely.',
    practice: 'When shame speaks, convert it: this act was wrong; here is the concrete repair.',
    lapseMedicine: 'After a fall, refuse the narrator who says "this is who I am." Not that voice. Return to the work.',
    dailyCommand: 'Repair with guilt; refuse shame.',
    retainLine: 'Guilt repairs. Shame hides. Choose the workable one.',
  },
  {
    id: 'arch-73',
    name: 'The Root-Reader',
    essence: 'Seeing the pattern beneath the urge — what the compulsion is quietly solving.',
    light: 'Reads the urge as a symptom. Asks what state it medicates, then meets that state.',
    shadow: 'Endless inquiry as delay. Mapping the room forever instead of leaving it.',
    discipline: 'One asked question, one action. Address the underlying state directly.',
    temptation: 'Fighting only the surface symptom while the root stays untouched.',
    practice: 'When the urge arrives, ask once: what state is this trying to solve? Then solve that.',
    lapseMedicine: 'A lapse points at the root, not just the act. Read what it medicated and address it directly.',
    dailyCommand: 'Find the root, not the surface.',
    retainLine: 'The urge is the symptom. The root is the work.',
  },
  {
    id: 'arch-74',
    name: 'The Grief-Bearer',
    essence: 'Letting the feeling beneath the anger exist, in the one channel he was never given.',
    light: 'Sits with a strong feeling until it softens to its truer shape. Lets grief be grief.',
    shadow: 'Pain routed through the only permitted channel — aggression that is really grief or fear.',
    discipline: 'When a strong feeling arrives, hold it one minute before doing anything with it.',
    temptation: 'Converting grief, fear, and longing back into the more acceptable form of anger.',
    practice: 'Practice the one-minute sit. Let the feeling become whatever it actually is underneath.',
    lapseMedicine: 'A lapse often discharges an unfelt feeling. After it, feel the thing for one minute and name it.',
    dailyCommand: 'Feel it before you move it.',
    retainLine: 'A feeling truly felt completes faster than one endlessly avoided.',
  },
  {
    id: 'arch-75',
    name: 'The Throne-Keeper',
    essence: 'Treating the wound honestly without seating it on the throne of identity.',
    light: 'Honors the shadow work, then returns the throne to the man it belongs to.',
    shadow: 'Wound-as-identity. Organizing a whole life around the struggle because the throne is at least occupied.',
    discipline: 'Account for the work without enshrining it. Demote the wound to its proper place.',
    temptation: 'Letting the struggle become the only story the man tells about himself.',
    practice: 'Name what you have looked at honestly. Renew the vow with the wound in its place.',
    lapseMedicine: 'A lapse is a wound, not a crown. Treat it, do not seat it. The throne belongs to the man.',
    dailyCommand: 'Treat the wound; do not crown it.',
    retainLine: 'The wound is part of the kingdom. It is not the kingdom.',
  },
  {
    id: 'arch-76',
    name: 'The Returner',
    essence: 'The clean return — one honest action after every stumble, without theater.',
    light: 'Stands up, names what happened, takes the lesson, moves. No grand vow, no penance.',
    shadow: 'The dramatic collapse that mistakes its own theater for the seriousness of the practice.',
    discipline: 'Return cleanly. Acknowledge briefly, learn briefly, repair briefly, continue.',
    temptation: 'Dramatizing the fall because the drama feels like seriousness.',
    practice: 'Apply the clean return to any setback: ninety seconds of honesty, then back to the rhythm.',
    lapseMedicine: 'The drama is wasted fire the next lapse is waiting to use. Stand up, take the lesson, return.',
    dailyCommand: 'Return without theater.',
    retainLine: 'Clean return is the discipline. Drama is the substitute.',
  },
  {
    id: 'arch-77',
    name: 'The Wound-Cleaner',
    essence: 'Moving from naming the wound to treating it. Cleaning, not worshiping.',
    light: 'Turns named patterns into concrete change. Honors the wound by healing it.',
    shadow: 'Returning to the wound to pick at it, telling its story without changing anything.',
    discipline: 'Choose one named pattern and begin the next available treatment today.',
    temptation: 'Staying at the entrance, naming forever, mistaking the door for the room.',
    practice: 'Identify one shadow pattern named long enough. Make one structural change toward healing it.',
    lapseMedicine: 'After a fall, do not re-tell the wound. Ask: what one change addresses what it just revealed?',
    dailyCommand: 'Treat what you have named.',
    retainLine: 'Naming is the door. Treatment is the room.',
  },
  {
    id: 'arch-78',
    name: 'The Investigator',
    essence: 'Studying the lapse as a case to solve, with the detachment of a detective.',
    light: 'Reads each setback as an intelligence file. Maps the chain so it can be broken earlier.',
    shadow: 'Drowning the information in shame, or turning the report into self-flagellation.',
    discipline: 'Study the last lapse as intelligence. Chart the chain; file it; use it.',
    temptation: 'Confusing the investigator with the criminal and abandoning the case.',
    practice: 'Write the lapse report: twelve hours back, six, one. What cracked, what voice spoke, what gate was open.',
    lapseMedicine: 'The investigator is not the criminal. He wants the case understood so it does not repeat.',
    dailyCommand: 'Study the case.',
    retainLine: 'A lapse studied is information. A lapse repeated is a pattern waiting for attention.',
  },
  {
    id: 'arch-79',
    name: 'The Gate-Builder',
    essence: 'Building structure in calm daylight so it holds at the hour of fire.',
    light: 'Turns hard-won data into specific boundaries — time rules, environment, protocol.',
    shadow: 'Suspicion hardening into rigidity, or blaming temptation instead of building structure.',
    discipline: 'Build the boundary before the spark. Remove the fuel, not just resist the flame.',
    temptation: 'Trying to legislate at the hour of temptation, when no boundary holds.',
    practice: 'Translate the lapse intelligence into one specific structural commitment. Write it down.',
    lapseMedicine: 'A lapse shows where the next gate belongs. Build it informed by data, not by shame.',
    dailyCommand: 'Build the gate when calm.',
    retainLine: 'A boundary is law passed when calm and obeyed when tested.',
  },
  {
    id: 'arch-80',
    name: 'The Road-Keeper',
    essence: 'Keeping the road through imperfection. The path is for the man with practiced returns.',
    light: 'Keeps walking when the road is rough. Does not need it to have been smooth.',
    shadow: 'Quitting at the first sustained difficulty, expecting the path to be smooth for someone.',
    discipline: 'Keep the road. That is the whole instruction. Renew the vow with days remaining.',
    temptation: 'Believing the completed man is the one with no struggles, rather than practiced returns.',
    practice: 'Honor the road kept over eighty days. Acknowledge the shadow work honestly.',
    lapseMedicine: 'The man who keeps the road is not the man who never falls. Keep walking; that is the practice.',
    dailyCommand: 'Keep the road.',
    retainLine: 'The Road-Keeper is not the man who never falls. He is the man who keeps the road.',
  },
  {
    id: 'arch-81',
    name: 'The Integrated',
    essence: 'Holding the whole without fracture — appetite, spirit, and reason ordered around a center.',
    light: 'Allows each part its presence and directs each toward its proper end.',
    shadow: 'Suppression mistaken for integration. A part erased rather than governed.',
    discipline: 'Govern the parts. Notice where appetite, spirit, and reason each point today.',
    temptation: 'Believing integration means the disappearance of desire rather than its ordering.',
    practice: 'Make one decision today using all three parts: hard work, courageous spirit, clear reason.',
    lapseMedicine: 'A part out of order is not the enemy; it is unintegrated. Re-order it and continue.',
    dailyCommand: 'Govern the parts; erase none.',
    retainLine: 'Integration is parts present and ordered, not parts erased.',
  },
  {
    id: 'arch-82',
    name: 'The Quiet King',
    essence: 'Strength that is owned rather than announced. Authority without display.',
    light: 'Uses strength in service of something real. Acts without strain or audience.',
    shadow: 'Control and entitlement. Strength performed because it is not yet fully owned.',
    discipline: 'Use strength quietly. Refuse every impulse to perform the discipline.',
    temptation: 'Showing the strength to himself and to an audience that was never coming.',
    practice: 'Notice each impulse to display your discipline today. Refuse it. Simply live it.',
    lapseMedicine: 'The strength was always for you, not the audience. After a fall, use it quietly again.',
    dailyCommand: 'Use strength without announcing it.',
    retainLine: 'Power that needs an audience is borrowed. Power that does not is yours.',
  },
  {
    id: 'arch-83',
    name: 'The Undivided',
    essence: 'Not desireless but undivided — desire kept, and pointed at worthy things.',
    light: 'Lets desire have a stable direction. Channels it toward work, training, service, real love.',
    shadow: 'Waiting for desire to vanish before counting himself free, and so waiting forever.',
    discipline: 'Aim desire, do not negotiate it away. Point it where the trained man would.',
    temptation: 'Believing freedom means the absence of appetite rather than its direction.',
    practice: 'Each time desire rises today, ask where the trained man would let it point, and point it there.',
    lapseMedicine: 'Desire never leaves; direction becomes reliable. After a fall, aim it again at the worthy thing.',
    dailyCommand: 'Give desire direction.',
    retainLine: 'The Undivided is not desireless. His desire is pointed at worthy things.',
  },
  {
    id: 'arch-84',
    name: 'The Commissioned',
    essence: 'Receiving the crown as a charge to keep, not a prize for having won.',
    light: 'Takes responsibility for his formation, his brothers, and the things larger than himself.',
    shadow: 'Reaching for the crown as a reward, then surprised by what it actually asks.',
    discipline: 'Treat the approaching crown as commission. Begin one durable commitment now.',
    temptation: 'Wanting the authority of the crown without earning continued self-rule.',
    practice: 'Sketch the Long Path: the daily, weekly, and monthly practices that carry the formation forward.',
    lapseMedicine: 'The crown is a commission, not a verdict on a single day. After a fall, keep the charge.',
    dailyCommand: 'Wear the crown as service.',
    retainLine: 'The crown is not a reward for perfection. It is a commission for maturity.',
  },
  {
    id: 'arch-85',
    name: 'The Long-Walker',
    essence: 'Reliability over inspiration — the practice as a way of life, not a season.',
    light: 'Keeps the account through the unmarked stretch, when no milestone is coming.',
    shadow: 'Believing one victory means completion, and letting the practice lapse without structure.',
    discipline: 'Build a lighter, durable rhythm. Hold the fire more by habit, less by attention.',
    temptation: 'Needing the inspiration of early days to keep practicing at all.',
    practice: 'Write week one of the Long Path: daily practices, weekly witness, monthly review.',
    lapseMedicine: 'The Long Path expects rough stretches. After a fall, return to the rhythm and keep walking.',
    dailyCommand: 'Be reliable, not only inspired.',
    retainLine: 'Ninety days prepares the man. The Long Path is where he lives.',
  },
  {
    id: 'arch-86',
    name: 'The Day-Ruler',
    essence: 'Governing the ordinary day, where the practice actually lives or dies.',
    light: 'Brings sovereignty to the unremarkable Tuesday. Rules the small things with full care.',
    shadow: 'Saving sovereignty for special moments and treating ordinary days as filler.',
    discipline: 'Rule the small things — speech, room, body, time — as if they all mattered. They do.',
    temptation: 'Imagining the crown will be carried by some elevated state rather than ordinary hours.',
    practice: 'Govern one ordinary stretch today with the same care you would give a milestone day.',
    lapseMedicine: 'The kingdom is held by ordinary days. After a fall, simply rule the next ordinary one well.',
    dailyCommand: 'Rule the ordinary day.',
    retainLine: 'The kingdom is held by ordinary days well-ruled.',
  },
  {
    id: 'arch-87',
    name: 'The Exemplar',
    essence: 'Teaching by presence, not preaching. The changed life that speaks for itself.',
    light: 'Lives the practice visibly, answers briefly when asked, grows no movement.',
    shadow: 'Preaching from fresh success — fragility that needs others to confirm the conviction.',
    discipline: 'Refuse to preach. When tempted to explain, live it instead.',
    temptation: 'Recruiting others to validate a conviction that is not yet settled.',
    practice: 'When tempted to explain the practice today, restrain it and be quietly present instead.',
    lapseMedicine: 'The example does the work, not the sermon. After a fall, keep living it without explanation.',
    dailyCommand: 'Let presence do the teaching.',
    retainLine: 'Presence teaches what preaching cannot.',
  },
  {
    id: 'arch-88',
    name: 'The Fire-Bearer',
    essence: 'Carrying the fire as a matter of course — the ally used, not displayed.',
    light: 'Moves the fire into form: real work, real training, real service. Holds it without performing.',
    shadow: 'Spiritual ego that still wants the world to know what has been done.',
    discipline: 'Carry the fire quietly. Use it on real things; do not announce the use.',
    temptation: 'The last plausible argument: "you have already done it, one night changes nothing."',
    practice: 'Do one substantial Forge act today and tell no one about it.',
    lapseMedicine: 'The graduation-robed argument is the day-six argument in disguise. Refuse the audience, not by debate.',
    dailyCommand: 'Carry the fire; do not announce it.',
    retainLine: 'The fire that is used does not need to be displayed.',
  },
  {
    id: 'arch-89',
    name: 'The Final Sentinel',
    essence: 'Holding the last gate with the same discipline as the first. No coasting near the end.',
    light: 'Keeps the gate as if many days remain, because they do. Refuses the ceremonial coast.',
    shadow: 'Treating the last day as different, relaxing because the milestone looks achieved.',
    discipline: 'Perform every element with full attention. Hold the gate as though forty days lay ahead.',
    temptation: 'The compulsion\'s last good argument: the final day is essentially won already.',
    practice: 'Complete one Forge act today equal in intensity to the early days. Treat it as one of many.',
    lapseMedicine: 'The crown is the cumulative integrity of guarded days. After a fall, guard this one anyway.',
    dailyCommand: 'Hold the final gate.',
    retainLine: 'The final gate is kept by the same discipline as the first.',
  },
  {
    id: 'arch-90',
    name: 'The Crowned',
    essence: 'The undivided man, formed enough to be trusted with what comes next.',
    light: 'Holds the whole without fracture. Receives the crown as responsibility, then walks on.',
    shadow: 'Mistaking the crown for a trophy, or for a promise of permanent victory.',
    discipline: 'Receive the crown. Then begin the Long Path with the discipline that produced it.',
    temptation: 'Believing the formation is finished rather than entrusted to a longer work.',
    practice: 'Read the Crown Rite. Acknowledge what has been formed. Begin the Long Path tomorrow.',
    lapseMedicine: 'The crown is not a promise never to fall. It is proof a man can be formed, and re-formed.',
    dailyCommand: 'Receive the crown as responsibility.',
    retainLine: 'Ninety days proves the man can be formed. The crown is responsibility.',
  },
];
