import type { ArchetypeProfile } from '../../schemas';

/**
 * The 12 archetypes are modes of formation, not costumes. Each has a light and a
 * shadow so the man can recognize himself honestly. Manforge voices honor the shadow
 * without becoming its mouthpiece — the shadow is named to be understood, not
 * worshiped (see docs/CONTENT_SAFETY.md).
 */
export const archetypeProfiles: readonly ArchetypeProfile[] = [
  {
    id: 'monk',
    name: 'The Monk',
    essence: 'Silence, restraint, sacred attention, inner stillness.',
    light: 'Able to be alone without leaking. Draws depth from quiet.',
    shadow: 'Withdrawal becoming avoidance. Superiority. Contempt for the ordinary world.',
    discipline: 'Solitude without fantasy — presence without escape.',
    temptation: 'Calling isolation "purity" while hiding from life and its demands.',
    practice: 'Ten minutes of silence before reaching for the screen.',
    lapseMedicine: 'Return to the breath. Do not confess to the void. Choose one real act.',
    dailyCommand: 'Guard the inner room.',
    retainLine: 'The Monk does not hate the world. He refuses to be invaded by it.',
  },
  {
    id: 'warrior',
    name: 'The Warrior',
    essence: 'Courage, endurance, decisive action, containment under pressure.',
    light: 'Moves when others stall. Carries weight without complaint.',
    shadow: 'Aggression mistaken for strength. Ego. Contempt for the soft.',
    discipline: 'Train when the body wants comfort. Act before negotiating.',
    temptation: 'Channeling unresolved pain into domination or empty contests.',
    practice: 'One hard physical act completed today before seeking ease.',
    lapseMedicine: 'Not punishment. A physical reset: move, sweat, breathe, return.',
    dailyCommand: 'Move before you negotiate.',
    retainLine: 'The Warrior does not spend fire in fantasy. He carries it into the contest.',
  },
  {
    id: 'craftsman',
    name: 'The Craftsman',
    essence: 'Patience, skill, repetition, excellence through care.',
    light: 'Can turn any urge into a finished thing. Finds flow in making.',
    shadow: 'Perfectionism as avoidance. Hiding in preparation instead of producing.',
    discipline: 'Turn urge into craft. Start before ready. Finish one thing.',
    temptation: 'Consuming knowledge and tools instead of building with them.',
    practice: 'Thirty minutes of deep, focused work — no queue, no multitask.',
    lapseMedicine: 'Make something small. The act of creating interrupts the shame spiral.',
    dailyCommand: 'Make something real.',
    retainLine: 'The Craftsman knows that energy becomes noble when it enters the hands.',
  },
  {
    id: 'king',
    name: 'The King',
    essence: 'Order, responsibility, protection, sound judgment.',
    light: 'Governs the space he inhabits. Steady under pressure. Others trust his word.',
    shadow: 'Control for control\'s sake. Entitlement. Expecting order in others before himself.',
    discipline: 'Govern the small kingdom first — room, schedule, speech, body.',
    temptation: 'Wanting authority without earning self-rule.',
    practice: 'Restore one area of visible order daily.',
    lapseMedicine: 'Clean the room. The outer order steadies the inner disorder.',
    dailyCommand: 'Rule yourself before you rule anything else.',
    retainLine: 'The King\'s first kingdom is his own attention.',
  },
  {
    id: 'lover',
    name: 'The Lover',
    essence: 'Beauty, reverence, tenderness, full presence.',
    light: 'Can appreciate without consuming. Sees the sacred in the ordinary.',
    shadow: 'Lust, fantasy, possession. Sentimental collapse. Confusing appetite for love.',
    discipline: 'See beauty without grasping it. Behold without consuming.',
    temptation: 'Mistaking desire for devotion — and devotion for weakness.',
    practice: 'Notice one beautiful or meaningful thing today without trying to own or record it.',
    lapseMedicine: 'Distinguish between what you want and what you revere.',
    dailyCommand: 'Revere, do not consume.',
    retainLine: 'The Lover is not ruled by appetite. He is trained to behold.',
  },
  {
    id: 'pilgrim',
    name: 'The Pilgrim',
    essence: 'Humility, journey, return, learning from the road.',
    light: 'Keeps walking after imperfection. Does not need the path to be perfect.',
    shadow: 'Aimlessness disguised as freedom. Self-pity. Endless restarting without learning.',
    discipline: 'One clean action after every mistake. No theater. No delay.',
    temptation: 'Dramatizing the fall as a way to avoid the return.',
    practice: 'After any stumble: name one thing to repair, and begin immediately.',
    lapseMedicine: 'Stand up. Clean one thing. Do not perform the contrition — just move.',
    dailyCommand: 'Return without theater.',
    retainLine: 'The Pilgrim is not the man who never falls. He is the man who keeps the road.',
  },
  {
    id: 'sage',
    name: 'The Sage',
    essence: 'Discernment, honest self-knowledge, pattern recognition.',
    light: 'Can see the shape of his own compulsion clearly and without drama.',
    shadow: 'Overthinking as avoidance. Intellectual pride. Analysis as delay.',
    discipline: 'One insight, one action. Understanding without practice is decoration.',
    temptation: 'Reading instead of practicing. Mapping the territory instead of crossing it.',
    practice: 'Name one recurring pattern today — then do the thing that interrupts it.',
    lapseMedicine: 'Study the lapse the way a physician studies a symptom: with curiosity, not contempt.',
    dailyCommand: 'Know the pattern. Break the spell.',
    retainLine: 'The Sage does not ask only what happened. He asks what kept happening.',
  },
  {
    id: 'brother',
    name: 'The Brother',
    essence: 'Loyalty, honesty, accountability, warm presence.',
    light: 'Reaches out. Does not disappear. Can ask for help without shame.',
    shadow: 'Dependence. Approval-seeking. Tribal grievance that replaces honest friendship.',
    discipline: 'Reach out before isolation rots. Send the message before pride makes the cost too high.',
    temptation: 'Suffering silently to protect an image of self-sufficiency.',
    practice: 'Contact one person today with honesty, not performance.',
    lapseMedicine: 'Isolation makes the urge louder. Find one voice — not to confess, to reconnect.',
    dailyCommand: 'Do not disappear.',
    retainLine: 'A brother\'s hand is sometimes the difference between a lapse and a return.',
  },
  {
    id: 'guardian',
    name: 'The Guardian',
    essence: 'Vigilance, protection, early prevention, structural discipline.',
    light: 'Wins before the battle becomes dramatic. Sets the gate before the test.',
    shadow: 'Suspicion becoming rigidity. Fear driving the watch. Blaming temptation instead of building structure.',
    discipline: 'Guard the gates before the fire rises. Remove the fuel, not just the spark.',
    temptation: 'Watching for danger from the wrong direction — outside, not inside.',
    practice: 'Remove one trigger from your environment today.',
    lapseMedicine: 'Audit: which gate was left open? Repair it quietly and move forward.',
    dailyCommand: 'Close the gate early.',
    retainLine: 'The Guardian wins before the battle becomes dramatic.',
  },
  {
    id: 'builder',
    name: 'The Builder',
    essence: 'Purpose, structure, long-horizon work, legacy.',
    light: 'Gives desire a destination. Converts energy into something that lasts.',
    shadow: 'Identity through output alone. Workaholism as a form of avoidance.',
    discipline: 'Advance one real project daily. Not planning — progress.',
    temptation: 'Escaping into organizing, planning, and optimizing instead of building.',
    practice: 'Name the one project that most deserves your energy. Give it thirty real minutes.',
    lapseMedicine: 'Redirect: what can I build right now, in the next hour, that matters?',
    dailyCommand: 'Build what makes you harder to enslave.',
    retainLine: 'The Builder gives desire a destination.',
  },
  {
    id: 'healer',
    name: 'The Healer',
    essence: 'Repair, integration, mercy without excusing, restoration.',
    light: 'Cleans wounds honestly. Can repair without self-destruction or denial.',
    shadow: 'Softness without standards. Endless self-analysis used to avoid action.',
    discipline: 'Repair what you can, then move. Do not make wounds an identity.',
    temptation: 'Using pain as a personality. Suffering that substitutes for growth.',
    practice: 'Find one thing to repair today: an apology, a conversation, a commitment met.',
    lapseMedicine: 'Do not erase the wound. Stop worshiping it. Ask: what can be repaired right now?',
    dailyCommand: 'Repair what you can.',
    retainLine: 'The Healer does not erase the wound. He stops worshiping it.',
  },
  {
    id: 'sovereign',
    name: 'The Sovereign',
    essence: 'Integrated command, mature freedom, holding all parts in order.',
    light: 'Holds the whole without fracture. Appetite, spirit, and reason aligned.',
    shadow: 'Spiritual ego. Isolation at the top. Believing one victory means completion.',
    discipline: 'Daily account. Nothing suppressed, nothing indulged without question.',
    temptation: 'Believing that past discipline earns future license.',
    practice: 'At day\'s end: what did appetite want? What did spirit say? What did reason command?',
    lapseMedicine: 'The Sovereign is not the man who never falls. He is the man who can account honestly.',
    dailyCommand: 'Remain governable by the good.',
    retainLine: 'The Sovereign is not desireless. He is undivided.',
  },
] as const;
