import type { LineagePassage } from '@/content/schemas';

/**
 * Lineage passages — wisdom from the contemplative traditions, mapped to the
 * day's theme and archetype. `verbatim: true` entries are well-known public-
 * domain quotations cited to author + work; `verbatim: false` entries are
 * original synthesis written in the app's voice, inspired by a tradition (never
 * a false quote, attributed to the tradition rather than a person).
 *
 * All framed as philosophical inspiration — never authority, proof, or a medical
 * claim. `sourceUrl` hosts are restricted to the public-domain allowlist in
 * lineage.schema.ts (enforced by test).
 */
export const lineagePassages: LineagePassage[] = [
  // ── Beginning / the vow ────────────────────────────────────────────────────
  {
    id: 'tao-64-single-step',
    text: 'The journey of a thousand li commenced with a single step.',
    attribution: 'Laozi',
    work: 'Tao Te Ching, 64',
    tradition: 'taoist',
    sourceUrl: 'https://www.sacred-texts.com/tao/taote.htm',
    verbatim: true,
    theme: 'beginning, the vow',
    archetype: 'pilgrim',
  },
  {
    id: 'synthesis-watch-the-cloud',
    text: 'A brother asked the elder how to overcome the passions. He said: do not make war on them. Stand still and watch them as you would watch clouds cross the sky. They came from elsewhere; they will go elsewhere. What you do not feed cannot stay.',
    attribution: 'After the Desert Fathers',
    work: '',
    tradition: 'monastic',
    sourceUrl: null,
    verbatim: false,
    theme: 'desire is not the enemy, non-suppression',
    archetype: 'healer',
  },
  {
    id: 'epictetus-ench-5-opinions',
    text: 'Men are disturbed not by the things which happen, but by the opinions about the things.',
    attribution: 'Epictetus',
    work: 'Enchiridion, 5',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Epictetus/epicench.html',
    verbatim: true,
    theme: 'the pause, response over reaction',
    archetype: 'sovereign',
  },
  {
    id: 'tao-12-five-colours',
    text: 'The five colours make a man’s eyes blind; the five notes make his ears deaf; the five tastes injure his palate.',
    attribution: 'Laozi',
    work: 'Tao Te Ching, 12',
    tradition: 'taoist',
    sourceUrl: 'https://www.sacred-texts.com/tao/taote.htm',
    verbatim: true,
    theme: 'guarding the senses, the eyes',
    archetype: 'guardian',
  },
  {
    id: 'dhammapada-103-conquer-self',
    text: 'If one man conquer in battle a thousand times thousand men, and if another conquer himself, he is the greatest of conquerors.',
    attribution: 'The Dhammapada',
    work: 'Dhammapada, 103',
    tradition: 'buddhist',
    sourceUrl: 'https://www.sacred-texts.com/bud/sbe10/index.htm',
    verbatim: true,
    theme: 'self-conquest, the body and discipline',
    archetype: 'warrior',
  },
  {
    id: 'analects-2-17-knowledge',
    text: 'When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it—this is knowledge.',
    attribution: 'Confucius',
    work: 'Analects, 2.17',
    tradition: 'confucian',
    sourceUrl: 'https://www.sacred-texts.com/cfu/conf1.htm',
    verbatim: true,
    theme: 'honest self-knowledge, knowing the voice',
    archetype: 'sage',
  },
  {
    id: 'dhammapada-33-straighten',
    text: 'As a fletcher makes straight his arrow, a wise man makes straight his trembling and unsteady thought, which is difficult to guard, difficult to hold back.',
    attribution: 'The Dhammapada',
    work: 'Dhammapada, 33',
    tradition: 'buddhist',
    sourceUrl: 'https://www.sacred-texts.com/bud/sbe10/index.htm',
    verbatim: true,
    theme: 'shaping the mind, the first week',
    archetype: 'guardian',
  },
  {
    id: 'synthesis-forge-the-fire',
    text: 'The fire that was not spent does not vanish. Carry it to the workbench, the field, the page. Energy refused one outlet will take the next you open for it — so open a worthy one.',
    attribution: 'After the makers’ traditions',
    work: '',
    tradition: 'virtue_ethics',
    sourceUrl: null,
    verbatim: false,
    theme: 'transmutation, energy seeking form',
    archetype: 'builder',
  },
  {
    id: 'synthesis-guard-the-doors',
    text: 'The teaching speaks of guarding the doors of the senses. The gate need not be grand to be decisive: a screen turned face-down, a room left, a glance returned to the work. Hold the small gate and the siege never reaches the wall.',
    attribution: 'After the Buddhist teaching on sense-restraint',
    work: '',
    tradition: 'buddhist',
    sourceUrl: null,
    verbatim: false,
    theme: 'attention, the phone, the gates',
    archetype: 'guardian',
  },
  {
    id: 'synthesis-stillness',
    text: 'Stillness is not emptiness. The monk’s cell is bare so that what fills it is chosen. Give the silent hour a shape — a task, a breath, a page — and solitude becomes a forge instead of a drift.',
    attribution: 'After the monastic tradition',
    work: '',
    tradition: 'monastic',
    sourceUrl: null,
    verbatim: false,
    theme: 'solitude, structure, stillness',
    archetype: 'monk',
  },

  // ── Available for later arcs ────────────────────────────────────────────────
  {
    id: 'tao-33-self-mastery',
    text: 'He who knows other men is discerning; he who knows himself is intelligent. He who overcomes others is strong; he who overcomes himself is mighty.',
    attribution: 'Laozi',
    work: 'Tao Te Ching, 33',
    tradition: 'taoist',
    sourceUrl: 'https://www.sacred-texts.com/tao/taote.htm',
    verbatim: true,
    theme: 'self-command, the inner kingdom',
    archetype: 'king',
  },
  {
    id: 'aurelius-8-59-one-another',
    text: 'Men exist for the sake of one another. Teach them then or bear with them.',
    attribution: 'Marcus Aurelius',
    work: 'Meditations, 8.59',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Antoninus/meditations.html',
    verbatim: true,
    theme: 'brotherhood, service',
    archetype: 'brother',
  },
  {
    id: 'aurelius-6-11-return',
    text: 'When thou art compelled by circumstances to be disturbed in a manner, quickly return to thyself, and do not continue out of tune longer than the compulsion lasts.',
    attribution: 'Marcus Aurelius',
    work: 'Meditations, 6.11',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Antoninus/meditations.html',
    verbatim: true,
    theme: 'the return, recovery after a lapse',
    archetype: 'pilgrim',
  },
  {
    id: 'dhammapada-1-thought',
    text: 'All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.',
    attribution: 'The Dhammapada',
    work: 'Dhammapada, 1',
    tradition: 'buddhist',
    sourceUrl: 'https://www.sacred-texts.com/bud/sbe10/index.htm',
    verbatim: true,
    theme: 'attention, what we feed',
    archetype: 'sage',
  },

  // ── Order / the inner kingdom ──────────────────────────────────────────────
  {
    id: 'synthesis-order-is-command',
    text: 'Order is command made visible. The man who governs the room he wakes in — the made bed, the cleared desk — has practised sovereignty before the first urge has spoken a word.',
    attribution: 'After the Stoics',
    work: '',
    tradition: 'stoic',
    sourceUrl: null,
    verbatim: false,
    theme: 'order, environment, inner command',
    archetype: 'king',
  },
  {
    id: 'synthesis-reason-rules',
    text: 'Plato set reason on the throne, with spirit as its guard and appetite as its servant. A kingdom is not ruled by killing the servant but by keeping the order. Today, let the rightful part govern.',
    attribution: 'After Plato',
    work: '',
    tradition: 'virtue_ethics',
    sourceUrl: null,
    verbatim: false,
    theme: 'the inner kingdom, reason rules appetite',
    archetype: 'sovereign',
  },
  {
    id: 'epictetus-ench-1-power',
    text: 'Some things are in our power, and others are not.',
    attribution: 'Epictetus',
    work: 'Enchiridion, 1',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Epictetus/epicench.html',
    verbatim: true,
    theme: 'the dichotomy of control, what is mine',
    archetype: 'sage',
  },
  {
    id: 'aurelius-7-29-present',
    text: 'Confine thyself to the present.',
    attribution: 'Marcus Aurelius',
    work: 'Meditations, 7.29',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Antoninus/meditations.html',
    verbatim: true,
    theme: 'the present, ruling the ordinary day',
    archetype: 'sovereign',
  },

  // ── Assent / the witness / not adding the story ────────────────────────────
  {
    id: 'aurelius-8-47-estimate',
    text: 'If thou art pained by any external thing, it is not this thing that disturbs thee, but thy own judgement about it; and it is in thy power to wipe out this judgement now.',
    attribution: 'Marcus Aurelius',
    work: 'Meditations, 8.47',
    tradition: 'stoic',
    sourceUrl: 'http://classics.mit.edu/Antoninus/meditations.html',
    verbatim: true,
    theme: 'the second arrow, do not add the story',
    archetype: 'healer',
  },
  {
    id: 'analects-12-4-within',
    text: 'Being internally examined, and finding nothing wrong there, what is there to be anxious about, what is there to fear?',
    attribution: 'Confucius',
    work: 'Analects, 12.4',
    tradition: 'confucian',
    sourceUrl: 'https://www.sacred-texts.com/cfu/conf1.htm',
    verbatim: true,
    theme: 'the inner witness, the examined life',
    archetype: 'sage',
  },
  {
    id: 'analects-1-8-faults',
    text: 'When you have faults, do not fear to abandon them.',
    attribution: 'Confucius',
    work: 'Analects, 1.8',
    tradition: 'confucian',
    sourceUrl: 'https://www.sacred-texts.com/cfu/conf1.htm',
    verbatim: true,
    theme: 'one clean act, repair without shame',
    archetype: 'pilgrim',
  },
  {
    id: 'synthesis-halt',
    text: 'When the fire wins, it rarely finds a man whole. It finds him hungry, angry, lonely, or tired. Tend the real lack — feed, mend, reach, rest — and the urge often forgets the errand it came on.',
    attribution: 'After the contemplative traditions',
    work: '',
    tradition: 'monastic',
    sourceUrl: null,
    verbatim: false,
    theme: 'vulnerability states, HALT, the real need',
    archetype: 'healer',
  },

  // ── Beauty without grasping ────────────────────────────────────────────────
  {
    id: 'synthesis-behold-not-grasp',
    text: 'There is a way of seeing that does not reach to own. The blossom is beautiful because it falls; the hand that grasps it already loses what it reached for. Behold — and let the wanting pass.',
    attribution: 'After the teaching of impermanence',
    work: '',
    tradition: 'buddhist',
    sourceUrl: null,
    verbatim: false,
    theme: 'reverence, presence without consumption',
    archetype: 'lover',
  },

  // ── The forge / transmutation / making ─────────────────────────────────────
  {
    id: 'dhammapada-145-fashion',
    text: 'Well-makers lead the water; fletchers bend the arrow; carpenters bend a log of wood; good people fashion themselves.',
    attribution: 'The Dhammapada',
    work: 'Dhammapada, 145',
    tradition: 'buddhist',
    sourceUrl: 'https://www.sacred-texts.com/bud/sbe10/index.htm',
    verbatim: true,
    theme: 'self-fashioning, craft, making something real',
    archetype: 'craftsman',
  },
  {
    id: 'synthesis-work-receives-fire',
    text: 'Every tradition that holds the fire also labours. The hand at honest work is a furnace; the energy that finds the bench rarely needs to be fought in the mind.',
    attribution: 'After the makers’ traditions',
    work: '',
    tradition: 'virtue_ethics',
    sourceUrl: null,
    verbatim: false,
    theme: 'work as transmutation, the forge',
    archetype: 'builder',
  },
  {
    id: 'synthesis-prayer-receives-fire',
    text: 'The contemplative does not waste the rising force; he lets it climb. Held and lifted rather than spent, the same fire that pulls a man downward can steady his mind.',
    attribution: 'After the contemplative traditions',
    work: '',
    tradition: 'monastic',
    sourceUrl: null,
    verbatim: false,
    theme: 'contemplative practice, spirit receives the fire',
    archetype: 'monk',
  },

  // ── Brotherhood & service ──────────────────────────────────────────────────
  {
    id: 'synthesis-another-self',
    text: 'The old teachers called a true friend another self — the man in whom your own struggle is known and not despised. Isolation is the compulsion’s favourite weather. Be known.',
    attribution: 'After Aristotle',
    work: '',
    tradition: 'virtue_ethics',
    sourceUrl: null,
    verbatim: false,
    theme: 'brotherhood, witness, not disappearing',
    archetype: 'brother',
  },
  {
    id: 'analects-15-23-reciprocity',
    text: 'What you do not want done to yourself, do not do to others.',
    attribution: 'Confucius',
    work: 'Analects, 15.23',
    tradition: 'confucian',
    sourceUrl: 'https://www.sacred-texts.com/cfu/conf1.htm',
    verbatim: true,
    theme: 'service, reciprocity, repair a bond',
    archetype: 'brother',
  },
  {
    id: 'tao-8-water',
    text: 'The highest excellence is like that of water. The excellence of water appears in its benefiting all things, and in its occupying, without striving, the low place which all men dislike.',
    attribution: 'Laozi',
    work: 'Tao Te Ching, 8',
    tradition: 'taoist',
    sourceUrl: 'https://www.sacred-texts.com/tao/taote.htm',
    verbatim: true,
    theme: 'quiet strength, service, low place',
    archetype: 'sovereign',
  },

  // ── The shadow & the return ────────────────────────────────────────────────
  {
    id: 'synthesis-shame-vs-guilt',
    text: 'Guilt says: I did a harmful thing, and I can repair it. Shame says: I am a harmful thing, so why try. The first is medicine; the second is the wound calling itself the man. Keep guilt; refuse shame.',
    attribution: 'After the monastic teachers',
    work: '',
    tradition: 'monastic',
    sourceUrl: null,
    verbatim: false,
    theme: 'shame is not command, healing over punishment',
    archetype: 'healer',
  },
  {
    id: 'dhammapada-223-anger-by-love',
    text: 'Let a man overcome anger by love, let him overcome evil by good; let him overcome the greedy by liberality, the liar by truth.',
    attribution: 'The Dhammapada',
    work: 'Dhammapada, 223',
    tradition: 'buddhist',
    sourceUrl: 'https://www.sacred-texts.com/bud/sbe10/index.htm',
    verbatim: true,
    theme: 'anger, the shadow met without contempt',
    archetype: 'warrior',
  },
  {
    id: 'synthesis-study-the-lapse',
    text: 'Study the fall the way a physician studies a symptom — with curiosity, not contempt. A lapse hides its lesson only from the man too ashamed to look at it.',
    attribution: 'After the Stoics',
    work: '',
    tradition: 'stoic',
    sourceUrl: null,
    verbatim: false,
    theme: 'study the lapse, return without theater',
    archetype: 'sage',
  },

  // ── The crown / integration ────────────────────────────────────────────────
  {
    id: 'tao-24-tiptoe',
    text: 'He who stands on his tiptoes does not stand firm; he who stretches his legs does not walk easily.',
    attribution: 'Laozi',
    work: 'Tao Te Ching, 24',
    tradition: 'taoist',
    sourceUrl: 'https://www.sacred-texts.com/tao/taote.htm',
    verbatim: true,
    theme: 'power without ego, no straining for show',
    archetype: 'king',
  },
  {
    id: 'synthesis-teach-by-example',
    text: 'The strongest teaching is a life, not a sermon. Carry the fire quietly; the man beside you learns more from how you stand than from anything you say about standing.',
    attribution: 'After Confucius',
    work: '',
    tradition: 'confucian',
    sourceUrl: null,
    verbatim: false,
    theme: 'teach without preaching, quiet example',
    archetype: 'brother',
  },
  {
    id: 'synthesis-crown-is-responsibility',
    text: 'The crown is not a reward worn for an audience; it is a weight carried for those who depend on the man beneath it. Authority earned in self-command becomes service, or it becomes nothing.',
    attribution: 'After the virtue traditions',
    work: '',
    tradition: 'virtue_ethics',
    sourceUrl: null,
    verbatim: false,
    theme: 'the crown is responsibility, mature power',
    archetype: 'king',
  },
];
