import type { DailyPathContent } from '../../schemas';

export const days01to15: readonly DailyPathContent[] = [
  {
    id: 'day-01',
    dayNumber: 1,
    title: 'The Vow',
    season: 'the_vow',
    archetype: 'pilgrim',
    openingLine: 'A man begins not when conditions are perfect, but when he chooses a word and means it.',
    teachingBody:
      'The vow is not a performance. It is the act of addressing yourself honestly: I am choosing to change the relationship between my will and my impulse. It does not require purity, a fresh month, or an ideal morning. It requires the moment you are in and a word you are willing to hold.\n\nMost men wait to begin. They say: when things settle, when I am less tired, when the season changes. But the compulsion does not wait. It arrives in the exact gap between intention and action. The vow fills that gap with something stronger than mood.\n\nBegin with the smallest possible gesture of truth: name what you are choosing, and choose it.',
    command: 'Choose your word and speak it — aloud if you are alone, inwardly if not.',
    practice: 'Write or recite your vow once this morning, before the phone.',
    forgeChallenge: 'Complete one act of discipline today that costs you comfort and earns you nothing visible.',
    journalPrompt: 'What is driving me to begin this practice? Name the real reason, not the flattering one.',
    eveningAccount: 'Did I live today from intention or from habit?',
    seal: 'A man begins the day he stops waiting to begin.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['energy-is-ally', 'pause-is-where-manhood-begins'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-02',
    dayNumber: 2,
    title: 'The Fire Is Not the Enemy',
    season: 'the_vow',
    archetype: 'healer',
    openingLine: 'What you are learning to govern is the same force that builds men, fills art, and founds families.',
    teachingBody:
      'The first mistake of the practice is to declare war on desire itself. That war cannot be won, and trying to win it produces something worse: a man split in half, ashamed of his own aliveness.\n\nRetain begins somewhere different. The fire — the drive, the appetite, the force that rises — is not the problem. The compulsion is the problem: the automatic, the unconscious, the habituated discharge that spends energy before it can become anything.\n\nThe energy itself is clean. It is the same force that makes a man build a company, train for something hard, or love deeply. The practice is not to extinguish it. The practice is to stop letting it be hijacked by the cheapest available outlet.',
    command: 'Today, do not fight what you feel. Name it, and then decide where it goes.',
    practice: 'When desire rises today, pause for thirty seconds and ask: "Where could this go if I give it direction?"',
    forgeChallenge: 'Find one hour of sustained work — physical, creative, or service — and give it the energy that would otherwise be spent.',
    journalPrompt: 'What do I believe about desire? Is it something to be hated or something to be led?',
    eveningAccount: 'Did I treat the energy as enemy or ally today?',
    seal: 'The fire is neutral. What matters is what it enters.',
    relatedStudyIds: ['brahmacharya-vow-and-attention', 'the-inner-forge-transmutation'],
    relatedPrincipleIds: ['energy-is-ally', 'compulsion-is-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-03',
    dayNumber: 3,
    title: 'The First Pause',
    season: 'the_vow',
    archetype: 'sovereign',
    openingLine: 'The pause is not a moment of weakness. It is the moment when the man is most fully himself.',
    teachingBody:
      'In Stoic thought, the impression and the assent are two different things. The impulse arrives — the image, the pull, the want. But the assent is yours. You are not required to agree with what your appetite proposes. You are not ruled by it simply because it speaks loudly.\n\nThis is the first pause: the gap between the urge arriving and the action following. It is tiny at first — a half-second of awareness before the hand moves. But that half-second is the whole game. Everything the practice builds lives in that gap.\n\nThe pause is not suppression. It is the moment you step into the driver\'s seat and feel the wheel.',
    command: 'When the first urge appears today, pause for one breath before responding to it.',
    practice: 'Practice deliberate delay: when you want to reach for the phone, pause for sixty seconds first. See what the urge does.',
    forgeChallenge: 'Take one strong urge today and redirect it within five minutes into a Forge act. Record it.',
    journalPrompt: 'What does the urge feel like in the body? Where does it live? What does it say?',
    eveningAccount: 'How many times today did I pause before I acted? Even once counts.',
    seal: 'Manhood begins in the pause between urge and action.',
    relatedStudyIds: ['guarding-the-gates-sense-restraint'],
    relatedPrincipleIds: ['pause-is-where-manhood-begins', 'hold-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-04',
    dayNumber: 4,
    title: 'Guard the Eyes',
    season: 'the_vow',
    archetype: 'guardian',
    openingLine: 'Most battles are won or lost long before the moment of temptation.',
    teachingBody:
      'The Buddhist teaching on *indriya-saṃvara* — guarding the sense doors — begins at the eye. Not because sight is shameful, but because attention is where desire begins. The moment a man\'s gaze is captured by something that feeds the compulsion, the battle has already started. Guarding the eye means catching it earlier.\n\nThis is not avoidance of beauty or of women or of life. It is the trained discipline of noticing where the attention is being led, and choosing differently at the first step rather than the tenth.\n\nThe first victory is often the simplest: look away. Scroll past. Close the tab. Leave the room. These acts seem small. They are not small. They are the gates of the inner castle, and holding them prevents the siege.',
    command: 'Today, practice one deliberate "look away." Notice the first spark and redirect before it becomes a flame.',
    practice: 'Audit your first thirty minutes online today. Where did your eyes go that they did not need to go?',
    forgeChallenge: 'Remove or block one source of visual temptation from your environment today.',
    journalPrompt: 'What do my eyes seek when I am restless or lonely? What are they actually asking for?',
    eveningAccount: 'Where was the first gate tonight? Did I hold it or did I let the army in?',
    seal: 'The first victory is often looking away.',
    relatedStudyIds: ['guarding-the-gates-sense-restraint'],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-05',
    dayNumber: 5,
    title: 'The Body Must Move',
    season: 'the_vow',
    archetype: 'warrior',
    openingLine: 'A disordered body will ask for false comfort. A trained body asks for something harder.',
    teachingBody:
      'Sexual energy does not only live in the mind. It lives in the body — in tension, in restlessness, in the legs that want to move and the hands that want to work. A man who practices retention and does not give the body a physical outlet is storing pressure in a vessel with no release valve.\n\nThis is why every tradition that practices conservation also practices rigorous physical discipline: monastic traditions train, martial arts schools train, brahmacharya students follow demanding physical regimens. The body is not the enemy of the practice — it is one of its instruments.\n\nWhen the fire rises today, don\'t first ask your mind to hold it. Ask your body to carry it somewhere. Train. Walk hard. Work with your hands. Let the energy move through muscle before it becomes compulsion in the mind.',
    command: 'Today, move the body before you entertain any strong urge.',
    practice: 'Complete one demanding physical act today — not for appearance, but for the feeling of energy well-spent.',
    forgeChallenge: 'Train for at least twenty minutes at an intensity that requires focus.',
    journalPrompt: 'What does my body need when I am restless — what would movement actually address?',
    eveningAccount: 'Did the body serve me today, or did I leave it agitated and unspent?',
    seal: 'The warrior\'s body is a partner, not a problem.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-06',
    dayNumber: 6,
    title: "The Lie of 'Just Once'",
    season: 'the_vow',
    archetype: 'sage',
    openingLine: "The compulsion has one argument it repeats with every face: 'Just this once will not matter.'",
    teachingBody:
      "The voice of compulsion is not stupid. It does not say: give up the practice, abandon the vow, stop caring. It says: tonight is fine. Just once. You\'ve been doing well. You deserve a release. It won\'t affect anything.\n\nThis is the lie. Not because pleasure is evil — it is not — but because the line between a deliberate choice and an automated discharge has been erased. 'Just once' is how the groove re-cuts. It is how the old pattern reclaims territory the man had won.\n\nThe Sage knows this voice by its style, not its content. The content changes. The voice is always the same: reasonable, intimate, whispering at the hour when the defenses are lowest. Learning to hear the style — not the words — is how you stay ahead of it.",
    command: "When you hear 'just once' today, name it. Say inwardly: 'I know this voice.'",
    practice: 'Identify the three hours when you are most vulnerable to this argument. Name them. Plan for them.',
    forgeChallenge: "Tonight, when the lie arrives — and it may — refuse not by fighting it but by beginning a Forge act before it can finish speaking.",
    journalPrompt: "What does 'just once' cost me beyond the act itself? What does it cost in terms of the man I am building?",
    eveningAccount: "Did the voice speak tonight? What did it say? Did I know it by its style?",
    seal: 'Know the voice. Not by its argument — by its hour.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['compulsion-is-enemy', 'lapse-is-information'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-07',
    dayNumber: 7,
    title: 'The First Gate',
    season: 'the_vow',
    archetype: 'guardian',
    openingLine: 'Seven days. The pause is real. The gate is real. You are real.',
    teachingBody:
      'At the end of the first week, a man who has been honest knows something that cannot be given to him from outside: the practice is possible. Not easy — possible. The urges came, and the world did not end when he did not follow them. The fire rose, and he gave it somewhere to go. The voice spoke, and he recognized it.\n\nThis is the end of the theoretical and the beginning of the actual. A week of pauses has already carved something. Not a completed character — that takes time — but a groove running in a new direction. The task now is to deepen it.\n\nThe first gate is not the end of the battle. It is the proof that the man can stand and fight. That proof is now his.',
    command: 'Stand at the end of this week and account for it without shame and without exaggeration.',
    practice: 'Read the rite. Do the audit. Renew the vow. Then begin day eight with the same intention as day one.',
    forgeChallenge: 'Complete a physical or creative act of discipline today that marks the week as real.',
    journalPrompt: 'What surprised me about this week? What do I know now that I did not know on day one?',
    eveningAccount: 'What did the first week teach me about where my battle actually is?',
    seal: 'The gate is real. The man who guards it is being made.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates', 'hold-the-fire'],
    milestoneRiteId: 'rite-day-7',
    safetyGuardrail: null,
  },
  {
    id: 'day-08',
    dayNumber: 8,
    title: 'Desire Is Energy Seeking Form',
    season: 'guard_the_gates',
    archetype: 'builder',
    openingLine: 'Raw desire is not asking to be satisfied. It is asking to be shaped.',
    teachingBody:
      'In Daoist thought, *jing* — the vital essence — is not something to be destroyed or denied. It is something to be refined: transformed from raw vitality into focused energy (*qi*) and eventually into clarity of spirit (*shen*). The alchemical metaphor is exact: lead is not wasted, it is transmuted. The fire is not put out, it is given a furnace.\n\nThe question is always: what form is this energy seeking? When a man is restless, the compulsion offers one answer: discharge. The practice offers another: direction. Training. Work. Art. Prayer. Brotherhood. These are not replacements for desire — they are places desire can become something that lasts.\n\nThe Builder understands this. He is not running away from desire. He is looking for the worthiest possible form it can take.',
    command: 'Find the form today. Do not let desire wait. Give it a project.',
    practice: 'Name one thing you want to build this month. Today, spend thirty minutes beginning it.',
    forgeChallenge: 'Give a strong urge today its most creative possible outlet. What did you make?',
    journalPrompt: 'What wants to be built in me that keeps being postponed by the easier option?',
    eveningAccount: 'Did desire find a worthy form today, or did it go to the default?',
    seal: 'The fire does not need to be killed. It needs a destination.',
    relatedStudyIds: ['the-inner-forge-transmutation'],
    relatedPrincipleIds: ['energy-is-ally', 'refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-09',
    dayNumber: 9,
    title: 'The Phone Is a Gate',
    season: 'guard_the_gates',
    archetype: 'guardian',
    openingLine: 'The most dangerous gate in most men\'s lives has a screen and a notification.',
    teachingBody:
      'The phone is not neutral. It is an architecture designed by people with significant resources to maximize the amount of time your attention stays on it. Every notification is a request for your impulse to fire. Every feed is designed to keep the eyes moving and the dopamine cycling.\n\nThis is not a conspiracy theory. It is engineering. And a man practicing attention discipline is training in the exact terrain these tools exploit.\n\nGuarding the phone gate means: not looking at it first in the morning. Not keeping it in the bedroom. Not opening it when lonely or restless. Not using it as a default comfort. These rules are simple. They are not easy. But they are the gates through which most compulsive triggers enter.',
    command: 'Today, the phone is a tool, not a companion. Use it with intention, not as a default reach.',
    practice: 'For the first thirty minutes of your morning, do not look at the phone. Reclaim the opening hour.',
    forgeChallenge: 'Identify and close the specific phone behavior most linked to your temptation pattern.',
    journalPrompt: 'When do I reach for the phone? What am I actually seeking in those moments?',
    eveningAccount: 'Was the phone a gate I guarded today or a gate I left open?',
    seal: 'The first gate is the one you carry in your pocket.',
    relatedStudyIds: ['guarding-the-gates-sense-restraint'],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-10',
    dayNumber: 10,
    title: 'Solitude Without Fantasy',
    season: 'guard_the_gates',
    archetype: 'monk',
    openingLine: 'A man can be completely alone and still not be present.',
    teachingBody:
      'There is a kind of solitude that feeds the practice: quiet, without intrusion, with the mind resting or working on something real. And there is a kind of solitude that feeds the compulsion: alone, phone available, tired, bored, and drifting into fantasy.\n\nThe Monk\'s discipline is learning the difference and designing accordingly. Fantasy — the indulgence of the imagination in scenes that feed the urge without spending it — is not neutral. It is preparation. It fills the magazine before the trigger is pulled.\n\nLoneliness is real. Solitude becomes lonely when it has no structure. The practice: give solitude a form. A ritual. A task. A book. A silence with intention. Lonely and drifting becomes an incubator. Alone and engaged becomes a forge.',
    command: 'Today, give every moment of solitude a structure before it becomes drift.',
    practice: 'When you are alone this evening, have a planned activity ready before the restlessness arrives.',
    forgeChallenge: 'Take thirty minutes of solitude tonight with no phone, no screen, and no fantasy. Sit, breathe, and be present with your own mind.',
    journalPrompt: 'When does solitude become dangerous for me? What structure prevents the drift?',
    eveningAccount: 'Was I present in my solitude today, or did I disappear into my own entertainment?',
    seal: 'Solitude is a forge or a trap. What makes the difference is structure.',
    relatedStudyIds: ['brahmacharya-vow-and-attention'],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-11',
    dayNumber: 11,
    title: 'The Fire as Messenger',
    season: 'guard_the_gates',
    archetype: 'sage',
    openingLine: 'The urge is not always asking for release. Sometimes it is announcing unused life.',
    teachingBody:
      'When the fire rises, ask what part of you has gone unfed. Is it the body needing movement? The soul needing silence? The mind needing work? The heart needing brotherhood? Compulsion offers one answer to every form of discomfort: discharge. A man learns to hear more deeply.\n\nAnger wants training. Loneliness wants connection. Boredom wants a real task. Grief wants acknowledgment. When the compulsion speaks, it is often translating one of these underlying hungers into its own language — offering its solution before the man can ask a better question.\n\nThe Sage\'s practice is to stop at the first interpretation and ask for the second. Not "how do I stop feeling this?" but "what is this feeling actually about, and what would genuinely address it?"',
    command: 'Do not obey the first interpretation of the urge.',
    practice: 'When desire rises today, ask: "What is this energy really asking me to build, face, clean, move, or repair?"',
    forgeChallenge: 'Turn one urge today into twenty minutes of physical movement or meaningful work.',
    journalPrompt: 'What need hides beneath my strongest urges?',
    eveningAccount: 'Did I treat the fire as command, enemy, or messenger today?',
    seal: 'The fire speaks. The man interprets.',
    relatedStudyIds: ['brahmacharya-vow-and-attention'],
    relatedPrincipleIds: ['energy-is-ally', 'refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-12',
    dayNumber: 12,
    title: 'Clean the Vessel',
    season: 'guard_the_gates',
    archetype: 'king',
    openingLine: 'A disordered environment is a vote for a disordered interior.',
    teachingBody:
      'The ancient traditions of inner alchemy understood something that modern men often miss: the inner and outer are not separate systems. The state of a man\'s room, his schedule, his desk, his relationship to physical chaos — all of these feed or drain the practice. A man who cannot govern the space he inhabits is already practicing a certain kind of surrender.\n\nOrder is not aesthetics. Order is command made visible. When a man cleans his room, makes his bed, removes the debris that accumulated while he was not paying attention, he is practicing the same discipline as the pause: choosing how the space is used instead of letting entropy use it for him.\n\nThe King\'s first act is always inward. But the inward command expresses itself outward, in the ordered kingdom that surrounds him.',
    command: 'Today, govern one space. Do not leave it in the state you found it.',
    practice: 'Spend fifteen minutes restoring one area of visible order.',
    forgeChallenge: 'Identify and remove one source of environmental temptation or disorder from your life today.',
    journalPrompt: 'What does my physical environment say about my interior state right now?',
    eveningAccount: 'Did I leave the world I touched today in better or worse order?',
    seal: 'The outer order is a mirror of the inner command.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-13',
    dayNumber: 13,
    title: 'Beauty Without Consumption',
    season: 'guard_the_gates',
    archetype: 'lover',
    openingLine: 'There is a way of seeing that does not require owning.',
    teachingBody:
      'The Lover\'s discipline is the most subtle of all: to be fully alive to beauty without being captured by it. This is not indifference — that is the Monk\'s path. The Lover sees deeply, feels fully, and appreciates with real reverence. What he trains is the second move: not grasping, not consuming, not converting every beautiful thing into an object of appetite.\n\nThis matters for the practice because much of what feeds the compulsion is not ugliness — it is beauty that has been hijacked by appetite. The training: learn to behold without the reaching. Notice the desire to possess and let it pass without following it. This is different from repression. It is the discipline of presence without consumption.\n\nA man who can appreciate without grasping has learned something most men never do.',
    command: 'Today, appreciate one beautiful thing without trying to own or record it.',
    practice: 'When you notice something beautiful today — in nature, a person, a moment — stay with the appreciation for five seconds without immediately doing anything with it.',
    forgeChallenge: 'Find one act of genuine service or giving today — something that gives rather than takes.',
    journalPrompt: 'What is the difference between love and appetite? Where do they overlap and where do they part?',
    eveningAccount: 'Did I behold anything today, or only consume?',
    seal: 'The Lover sees clearly because he is not trying to take.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-14',
    dayNumber: 14,
    title: 'The Gatekeeper',
    season: 'guard_the_gates',
    archetype: 'guardian',
    openingLine: 'After two weeks, a man begins to know his enemy by name.',
    teachingBody:
      'The second week teaches the specifics. Not temptation in the abstract, but the particular trigger that comes for you. The hour. The mood. The state — tired, lonely, bored, frustrated, or even elated. The app. The content. The thought that arrives just before the compulsion speaks.\n\nThis knowledge is not defeat — it is intelligence. The gatekeeper\'s power comes from knowing exactly where the army enters. Not from pretending the army does not exist, not from being overwhelmed by it, but from positioning the defense at the right gate, at the right hour, with the right structure.\n\nYou know your gates now. That is a form of command the man two weeks ago did not have.',
    command: 'Stand at your known gate today with structure, not willpower.',
    practice: 'Read the milestone rite. Account for two weeks honestly.',
    forgeChallenge: 'Build one new specific boundary based on what these fourteen days revealed.',
    journalPrompt: 'Which trigger has appeared most reliably? What structure — not willpower — would address it?',
    eveningAccount: 'Am I guarding gates or relying on willpower? What is the difference?',
    seal: 'The man who knows his gates is already a step ahead of the fire.',
    relatedStudyIds: ['guarding-the-gates-sense-restraint'],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: 'rite-day-14',
    safetyGuardrail: null,
  },
  {
    id: 'day-15',
    dayNumber: 15,
    title: 'Train the Animal',
    season: 'body_must_be_included',
    archetype: 'warrior',
    openingLine: 'The body is not the enemy. But an untrained body makes a demanding master.',
    teachingBody:
      'This week enters a new territory: the body must be deliberately included in the practice, not merely dragged along behind the mind\'s intentions. The body has its own rhythms, its own hungers, its own demands — and when those demands go unmet, the compulsion finds fertile ground.\n\nSleep-deprived men are more vulnerable to urge. Sedentary bodies store tension that becomes compulsion. Underfed or overcaffeinated nervous systems cannot hold the pause with the same stability as rested, trained ones. This is not moral weakness — it is physiology, and the practice must account for it.\n\nThe Warrior\'s discipline is to treat the body as an ally in the training, not as an obstacle. Train it, rest it, feed it well, give it physical demands worthy of its capacity.',
    command: 'Train the body today with the same intentionality you bring to the mind.',
    practice: 'Assess your physical state: sleep, food, movement. Address one area where you are working against the practice.',
    forgeChallenge: 'Complete a demanding physical training session — something that requires you to want to stop and choose not to.',
    journalPrompt: 'When does my body become a vulnerability? What physical states make discipline easier or harder?',
    eveningAccount: 'Did I take the body seriously today as part of the practice?',
    seal: 'A trained body is a practiced will.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
];
