import type { DailyPathContent } from '../../schemas';

export const days16to30: readonly DailyPathContent[] = [
  {
    id: 'day-16',
    dayNumber: 16,
    title: 'The Urge Is an Impression',
    season: 'body_must_be_included',
    archetype: 'sage',
    openingLine: 'The impulse arrives. The assent is yours.',
    teachingBody:
      'Marcus Aurelius wrote about distinguishing the impression from the response. Epictetus taught that we are not disturbed by events, but by our judgments about them. At the center of Stoic practice is a single, radical idea: the first impulse is not the final authority. Something appears, but you are not required to agree with what it proposes.\n\nWhen the urge rises, something real is happening in the body and the mind. That part is not under direct control. But the assent — the moment of agreement that says "yes, follow this" — that is yours. Not easily, not automatically, but actually.\n\nThe Stoic practice in Retain\'s language: the impression is not a command. The pause between impression and assent is where the practice lives.',
    command: 'When the urge arrives today, name it as an impression. Say internally: "This is an impression. I do not have to agree."',
    practice: 'Use the four-step assent drill: (1) This is an impression. (2) It is not yet a command. (3) I do not have to agree. (4) I choose the next act.',
    forgeChallenge: 'Ride one strong urge all the way to its natural peak and watch it pass without acting on it.',
    journalPrompt: 'Where in today did I confuse an impression with a command? What would the pause have looked like?',
    eveningAccount: 'How many impressions today did I treat as optional rather than obligatory?',
    seal: 'You are not the urge. You are the one who chooses.',
    relatedStudyIds: ['brahmacharya-vow-and-attention'],
    relatedPrincipleIds: ['pause-is-where-manhood-begins', 'compulsion-is-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-17',
    dayNumber: 17,
    title: 'No Negotiation in Darkness',
    season: 'body_must_be_included',
    archetype: 'king',
    openingLine: 'The night has its own physics. Decisions made in the dark rarely look the same in the morning.',
    teachingBody:
      'Most lapses happen late. Not because the evening is inherently more dangerous, but because by late evening most men have spent their decision-making energy, their willpower has been depleted by a full day of choices, and they are tired, which lowers every threshold.\n\nThis is not a moral failure — it is chronobiology. The King\'s response is not shame but structure: decide in advance, in the morning, what the evening will look like. Set the gate before the temptation hour arrives. Establish a hard boundary around the phone in bed. Have the ritual ready.\n\nNegotiating with the compulsion at 11pm in the dark, while tired, is not a fair fight. The man who plans the evening in the morning wins more often than the man who improvises it at 11pm.',
    command: 'Tonight, have your structure in place before the hour when you are weakest.',
    practice: 'This morning, plan the last two hours of your evening: what you will do, where the phone will sleep, what time the day ends.',
    forgeChallenge: 'Go to sleep thirty minutes earlier than usual tonight. Rest is a boundary.',
    journalPrompt: 'What does my typical late evening look like? What structure would make it less dangerous?',
    eveningAccount: 'Did I govern the night, or did I improvise it?',
    seal: 'Govern the evening in the morning. By evening it is too late to plan.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-18',
    dayNumber: 18,
    title: 'Hunger, Anger, Loneliness, Fatigue',
    season: 'body_must_be_included',
    archetype: 'healer',
    openingLine: 'The states that precede a lapse are almost always the same. They are not mysterious.',
    teachingBody:
      'Recovery communities have long used the acronym HALT: Hungry, Angry, Lonely, Tired. These four states are the most reliable predictors of vulnerability to any compulsion. Not because they cause the urge, but because they reduce the man\'s capacity to hold the pause.\n\nA hungry man has lower tolerance. An angry man is looking for a discharge. A lonely man wants something that feels like connection. A tired man cannot maintain the gap between impression and assent.\n\nThe Healer\'s discipline is to treat these states as signals rather than triggers: when I notice I am in one of them, address the state before the temptation arrives. Eat. Walk off the anger. Call someone. Sleep. These are not excuses — they are maintenance, and a man who neglects maintenance pays for it in lapses.',
    command: 'Check your state before the urge arrives, not after.',
    practice: 'Today, notice which of the four states you are in at any given hour. Address the state directly when you find it.',
    forgeChallenge: 'Identify the state you are most prone to neglecting. Today, address it proactively — not reactively.',
    journalPrompt: 'In the hour before my last lapse or near-lapse, which state was I in? Was I attending to it?',
    eveningAccount: 'Did I treat my body\'s signals as information today, or ignore them until they became demands?',
    seal: 'Address the state, not just the urge.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-19',
    dayNumber: 19,
    title: 'Make Something Real',
    season: 'body_must_be_included',
    archetype: 'craftsman',
    openingLine: 'Desire becomes clean when it enters the hands.',
    teachingBody:
      'The Craftsman tradition — from medieval guilds to the Japanese concept of *shokunin* — holds that mastery is inseparable from making. The craftsman does not think about the work until it is perfect before beginning. He begins, and the thinking happens through the making.\n\nFor a man practicing retention, this is one of the most reliable outlets: not thinking about redirecting desire but actually making something with it. Writing that doesn\'t have to be read. Drawing that doesn\'t have to be good. Code that might not ship. Music no one hears. The act of creating is itself the transmutation.\n\nThe key is not the quality of the output. It is the quality of the attention given to it. Thirty minutes of genuine making — hands busy, mind absorbed, desire channeled into craft — is better than any amount of planning to make.',
    command: 'Today, make something real. Not plan. Not think. Make.',
    practice: 'Spend thirty uninterrupted minutes on a creative or skill-based act. Minimize the output, maximize the attention.',
    forgeChallenge: 'Turn your strongest urge today into your most ambitious creative or productive act this week.',
    journalPrompt: 'What do I want to build or make that keeps being postponed? What small step could happen today?',
    eveningAccount: 'Did I create anything today? Even ten minutes of genuine making?',
    seal: 'The Craftsman knows that energy becomes noble when it enters the hands.',
    relatedStudyIds: ['the-inner-forge-transmutation'],
    relatedPrincipleIds: ['refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-20',
    dayNumber: 20,
    title: "The Brother's Hand",
    season: 'body_must_be_included',
    archetype: 'brother',
    openingLine: 'Isolation is the compulsion\'s natural habitat.',
    teachingBody:
      "The Surgeon General's advisory on loneliness identified social isolation as one of the most significant public health concerns facing men. Men who lack close friendships are dramatically more likely to struggle with mental health, compulsive behavior, and chronic physical illness.\n\nFor the practice, this is not abstract. A man who is isolated, who has no one he can speak honestly with, who carries the practice entirely alone, is fighting with one hand tied. Not because weakness requires confession, but because human beings are social creatures whose nervous systems regulate partly through genuine contact with other people.\n\nBrotherhood does not require a tribe or a formal structure. It requires one conversation in which both men speak honestly. Reach out before pride makes the cost too high.",
    command: 'Do not disappear. Reach one man today with honesty.',
    practice: 'Send a message or make a call to someone you trust — not to perform your discipline, but to simply be present with another human voice.',
    forgeChallenge: 'Offer genuine help to someone today — not advice, not information, but actual presence or service.',
    journalPrompt: 'Who do I trust enough to tell the truth to about my struggles? Have I been honest with them lately?',
    eveningAccount: 'Was I connected to anyone genuinely today? Or did I spend the day performing or hiding?',
    seal: 'A brother\'s hand is sometimes the difference between a lapse and a return.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-21',
    dayNumber: 21,
    title: 'The Forge Opens',
    season: 'body_must_be_included',
    archetype: 'craftsman',
    openingLine: 'Three weeks of choosing direction over default. The forge is real now.',
    teachingBody:
      'The first three weeks are the hardest — the body argues, the habits have momentum, and the compulsion speaks with practiced authority. The man who reaches day twenty-one has done something more than maintained a streak. He has established a new groove.\n\nNeuroscience supports what the old traditions understood: repeated action under intentional attention changes the brain. The pathways of the compulsion do not disappear, but the pathways of the pause are now deeper than they were. Each time the urge arrived and the man chose differently, the alternative path was worn a little clearer.\n\nThe Forge opens not with ceremony but with the quiet recognition that what was impossible on day one is now merely difficult. That is the whole distance between struggle and practice.',
    command: 'Enter the next three weeks knowing you have already changed something that cannot be taken back.',
    practice: 'Read the milestone rite. Account honestly. Renew the vow.',
    forgeChallenge: 'Complete your most demanding Forge act yet. Longer, harder, or more meaningful than anything in the past three weeks.',
    journalPrompt: 'What is different in me after three weeks? Name something specific.',
    eveningAccount: 'Did I recognize today what I have already built, without needing to exaggerate it?',
    seal: 'Twenty-one days of choosing direction over compulsion. The Forge is open.',
    relatedStudyIds: ['the-inner-forge-transmutation'],
    relatedPrincipleIds: ['refine-the-fire', 'hold-the-fire'],
    milestoneRiteId: 'rite-day-21',
    safetyGuardrail: null,
  },
  {
    id: 'day-22',
    dayNumber: 22,
    title: 'Appetite Is Not King',
    season: 'discipline_of_assent',
    archetype: 'king',
    openingLine: 'Plato described the soul as a kingdom. The question is who holds the throne.',
    teachingBody:
      'Plato\'s *Republic* offers one of the most useful maps of the inner life available in Western philosophy. He described three parts: appetite, which has force and hunger; spirit (*thumos*), which has courage and indignation; and reason, which has judgment and direction. A well-governed soul is one where reason leads, spirit provides the energy to act on reason\'s direction, and appetite follows rather than commands.\n\nThe disordered soul is not one that lacks appetite — appetite is always present. The disordered soul is one where appetite has seized the throne that belongs to reason, and uses spirit\'s courage to serve its own demands.\n\nRetain translates this simply: appetite has force, spirit has courage, reason must give direction. The urge is appetite speaking. The man who follows it without pause has let appetite rule. The pause is reason reclaiming the throne.',
    command: 'When appetite speaks today, ask reason what it thinks before responding.',
    practice: 'At each significant decision today, name which part is speaking: appetite, spirit, or reason. Let reason have the last word.',
    forgeChallenge: 'Complete one act today that appetite would not choose but reason endorses.',
    journalPrompt: 'What does appetite want right now? What does reason say about it?',
    eveningAccount: 'Who held the throne today?',
    seal: 'Appetite has force. Reason must give direction.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['compulsion-is-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: 'This is philosophical inspiration, not medical advice or religious doctrine.',
  },
  {
    id: 'day-23',
    dayNumber: 23,
    title: 'The Spirited Part',
    season: 'discipline_of_assent',
    archetype: 'warrior',
    openingLine: 'The spirit that becomes rage without reason becomes tyranny. Trained, it becomes courage.',
    teachingBody:
      'Plato\'s *thumos* — the spirited part — is the source of righteous anger, courage, pride, and the drive to resist injustice or humiliation. It is what makes a man willing to fight for something, to refuse to be diminished, to stand when others sit.\n\nIn the practice, *thumos* is an ally when it is working for reason. A man whose spirit is engaged can hold the pause with real conviction — not just as a mental exercise but as an act of self-respect. The urge is not just an impression; it is a kind of insult to the man he is building, and the spirited part can be trained to reject that.\n\nBut *thumos* without reason becomes aggression, pride in the wrong things, domination that has no legitimate purpose. The warrior disciplines it by giving it worthy causes: the body to train, the project to complete, the man to protect.',
    command: 'Let your spirit work for reason today, not against it.',
    practice: 'Find one place today where courage — not just willpower — is required. Act from there.',
    forgeChallenge: 'Do one difficult, courageous act today that you have been avoiding because it costs something.',
    journalPrompt: 'Where does my anger or pride most often work against me? Where could that same energy work for me?',
    eveningAccount: 'Did I use my spirit for something worthy today, or did I spend it on something small?',
    seal: 'Spirit trained to serve reason becomes courage. Spirit on its own becomes fire without direction.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['energy-is-ally'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-24',
    dayNumber: 24,
    title: 'Reason Must Rule',
    season: 'discipline_of_assent',
    archetype: 'sovereign',
    openingLine: 'The inner throne belongs to reason — but reason must earn it daily.',
    teachingBody:
      'Reason\'s rule is not passive. It is not enough to know the right thing — reason must be practiced into authority through repeated acts of choosing it over the alternatives. Plato\'s philosopher-king did not rule because he was smart. He ruled because he had trained his soul through years of choosing wisdom over comfort.\n\nFor a man practicing retention, the inner throne is contested daily. Appetite presents its arguments in the morning, in the temptation hour, in the lonely evening. Spirit gets angry about small things and wants to discharge its energy in the nearest available direction. Reason\'s task is to govern both — not to suppress them, but to give them worthy form.\n\nThe Sovereign is the archetype of the man who has exercised this so long that it begins to feel natural. Not desireless, not without passion — but ordered. Undivided.',
    command: 'Give reason one clear action today that appetite and spirit would not have chosen without it.',
    practice: 'Morning: what would reason say about today? Evening: did I live by it?',
    forgeChallenge: 'Make one long-term decision today — about a boundary, a goal, a commitment — that reason endorses and appetite resists.',
    journalPrompt: 'What would today look like if reason held the throne completely? What would change?',
    eveningAccount: 'Was I governed by reason, spirit, or appetite today? Who won the later hours?',
    seal: 'The inner kingdom is not won once. It is governed daily.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['pause-is-where-manhood-begins'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-25',
    dayNumber: 25,
    title: 'Ritual Shapes Desire',
    season: 'discipline_of_assent',
    archetype: 'monk',
    openingLine: 'Without ritual, desire invents the day.',
    teachingBody:
      'Confucian thought has one of the most sophisticated analyses of ritual (*li*) in any philosophical tradition. For Confucius, ritual was not empty ceremony — it was a structure that formed the soul by shaping conduct. Repeated ritual practice trains desire itself: the man who always begins the day with the same act of discipline eventually finds that his desire moves toward discipline before the ritual reminds it.\n\nThis is the paradox the practice eventually reveals: the ritual feels most powerful not when willpower is high, but when willpower is depleted. When the man is tired and the compulsion is speaking, the morning ritual that was repeated for twenty-five days reaches back and pulls him through. Not by force — by groove.\n\nThe ritual does not need to be elaborate. It needs to be consistent. The same act, in the same order, at the same time.',
    command: 'Today, perform your morning ritual before anything else, and see what it opens.',
    practice: 'Formalize your morning rite: stand, breathe, read the vow, name the command, anticipate the likely temptation.',
    forgeChallenge: 'Add one evening ritual that closes the day with the same intentionality the morning opens it.',
    journalPrompt: 'What small ritual has already shaped my desire in these twenty-five days?',
    eveningAccount: 'Did my rituals serve me today, or did I skip them when they were most needed?',
    seal: 'A ritual is a chosen form that trains wild energy.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates', 'return-to-order'],
    milestoneRiteId: null,
    safetyGuardrail: 'This is philosophical inspiration from one tradition among many.',
  },
  {
    id: 'day-26',
    dayNumber: 26,
    title: 'Return Without Shame',
    season: 'discipline_of_assent',
    archetype: 'pilgrim',
    openingLine: 'The fall does not disqualify the man. The drama made of the fall disqualifies the practice.',
    teachingBody:
      'A lapse is information. It shows a trigger, an hour, a state. It shows what the compulsion says when it is strongest. It shows which gate was left unguarded. None of this information is available to the man who has never been tested — and none of it is useful to the man who drowns the lesson in shame.\n\nShame produces hiding. Hiding produces isolation. Isolation produces more vulnerability. This is the spiral that makes a single lapse into a prolonged relapse. Not because one act has permanent moral weight, but because the response to it does.\n\nThe Pilgrim\'s medicine is brutal in its simplicity: stand up. Clean one wound. Name the lesson. Begin again. No theater of contrition, no dramatic vow, no public confession, no internal prosecution. The man who can return cleanly — without drama and without excuse — is the man who will return every time.',
    command: 'If you have fallen, or when you do: stand up, name what happened, repair one thing, and continue.',
    practice: 'Write down the last time you returned from a setback. What did the return look like? What made it clean or difficult?',
    forgeChallenge: 'Identify one thing that needs repair right now — a lapse, a broken boundary, a neglected commitment. Begin the repair today.',
    journalPrompt: 'What does my shame voice say after a lapse? Is it useful? Is it honest?',
    eveningAccount: 'Did I return from anything today — a slip, a mood, an old pattern — without making a religion of it?',
    seal: 'A lapse ends a streak. It does not end the practice.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'man-is-never-enemy', 'shame-weakens-command'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-27',
    dayNumber: 27,
    title: 'Service Burns Fog',
    season: 'discipline_of_assent',
    archetype: 'brother',
    openingLine: 'A man absorbed in strengthening someone else has less room for the compulsion.',
    teachingBody:
      'One of the least discussed but most reliable tools in any discipline practice is service. Not performance, not virtue signaling, not self-congratulation about how much one helps — but actual, concrete, ordinary service that costs the man something and benefits someone else.\n\nService interrupts the self-absorption that feeds compulsive behavior. The compulsion is inherently self-directed: it is about *my* appetite, *my* relief, *my* comfort. The moment genuine attention is directed toward someone else\'s need, the circuit breaks. The compulsion has no power over a man who is genuinely present to someone else\'s reality.\n\nThis is why "Brotherhood" is one of the six Forge categories. Calling a friend who is struggling, helping someone practically, offering honest witness — these are not soft alternatives to discipline. They are among the most demanding and most effective acts of transmutation available.',
    command: 'Help someone today with the energy you would otherwise spend on yourself.',
    practice: 'Identify one person in your life who needs something concrete. Offer it today.',
    forgeChallenge: 'Perform one act of genuine service today — without mentioning it, recording it, or receiving credit for it.',
    journalPrompt: 'When did I last strengthen another person? What did it cost me? What did it return?',
    eveningAccount: 'Did I look outward today, or was the whole day spent looking inward?',
    seal: 'Isolation makes the urge louder. Brotherhood gives the man back his name.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-28',
    dayNumber: 28,
    title: 'The Quiet Room',
    season: 'discipline_of_assent',
    archetype: 'monk',
    openingLine: 'The man who cannot tolerate silence has made noise a necessity. The compulsion lives there.',
    teachingBody:
      'Silence is not natural for most modern men. The phone fills every gap. Music fills the commute. Podcasts fill the gym. The mind, unaccustomed to quiet, reaches for content the way the body reaches for food when bored.\n\nBut the practice is built in silence. The pause requires a man who can sit with himself without immediately reaching for stimulation. The interior life — the place where urges are examined, where the journal conversation happens, where the archetype speaks — only opens when the noise is off.\n\nTen minutes of genuine silence at some point in the day is not spiritual performance. It is maintenance. The man who allows himself to be regularly quiet will find that the compulsion loses some of its urgency there. The urge speaks loudly when everything else is loud. In quiet, it becomes more legible — and more manageable.',
    command: 'Today, give silence ten real minutes. Not meditation theater — just quiet, with no phone.',
    practice: 'Sit in silence for ten minutes at some point today. No phone, no music, no content.',
    forgeChallenge: 'Spend thirty minutes this evening with no screen, no audio, and no fantasy. Be present with your own mind.',
    journalPrompt: 'What happens in my mind when the noise stops? What do I hear?',
    eveningAccount: 'Did I give myself any genuine silence today?',
    seal: 'The practice lives in what happens when the noise stops.',
    relatedStudyIds: ['brahmacharya-vow-and-attention'],
    relatedPrincipleIds: ['guard-the-gates'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-29',
    dayNumber: 29,
    title: 'One Promise Kept',
    season: 'discipline_of_assent',
    archetype: 'craftsman',
    openingLine: 'Virtue is not a feeling. It is a trained disposition — built by repetition, not by intention.',
    teachingBody:
      'Aristotle\'s central insight about ethics is one of the most practically useful ideas in all of philosophy: we become just by doing just acts, brave by doing brave acts, disciplined by doing disciplined acts. Character is not what a man intends to be — it is the residue of what he repeatedly does.\n\nThis is why the streak is not the soul of the practice, but the practice itself is everything. Not because the streak is merely a number, but because each day of the practice is a small act that carves the groove a little deeper. Each Forge act, each pause, each kept boundary, each morning ritual completed before the phone — these are not performances. They are repetitions that become disposition.\n\nThe Craftsman understands this better than anyone: excellence is not found in a single great act but in the ordinary acts done with extraordinary attention.',
    command: 'Make one promise to yourself today and keep it.',
    practice: 'Name the one promise you most need to keep today. State it in the morning. Keep it.',
    forgeChallenge: 'Complete an act of craft or skill that you have been postponing. Finish something.',
    journalPrompt: 'What character trait am I building by repeated action in this practice? Can I name it specifically?',
    eveningAccount: 'What repetition did I add to my character today?',
    seal: 'Character is carved by repetitions too small for the ego to celebrate.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['pause-is-where-manhood-begins', 'refine-the-fire'],
    milestoneRiteId: null,
    safetyGuardrail: null,
  },
  {
    id: 'day-30',
    dayNumber: 30,
    title: 'The Oath Renewed',
    season: 'discipline_of_assent',
    archetype: 'sovereign',
    openingLine: 'Thirty days is not the summit. It is the proof that the man can live by a chosen word.',
    teachingBody:
      'Thirty days of returning to the breath, the work, and the vow. Of meeting the urge with a pause instead of a response. Of recognizing the compulsion\'s voice and choosing differently. Of building with what would have been wasted.\n\nThis is not a small thing. Most men do not go thirty days. Not because they are weak, but because they never had a practice — a structure, a voice, a place to return to. You do. You have used it.\n\nThe oath that began on day one is not the same oath today. It is deeper now, because you know what it costs. You have felt the resistance and stood in it. You have probably fallen once and returned. You have discovered something true about yourself that no one can give you: this practice is possible for you. That knowledge cannot be taken back.',
    command: 'Stand at thirty days and account without shame and without exaggeration.',
    practice: 'Read the milestone rite. Audit honestly. Renew the vow.',
    forgeChallenge: 'Complete one difficult act before any pleasure today. Let the day be authored by the man you have become.',
    journalPrompt: 'What has the practice cost me that was worth the price? What has it returned?',
    eveningAccount: 'Who held the throne today?',
    seal: 'The oath is not a sentence. It is a spine.',
    relatedStudyIds: [],
    relatedPrincipleIds: ['pause-is-where-manhood-begins', 'lapse-is-information', 'shame-weakens-command'],
    milestoneRiteId: 'rite-day-30',
    safetyGuardrail: null,
  },
];
