import type { DailyPathContent } from '../../schemas';

export const days61to90: readonly DailyPathContent[] = [
  // Arc 7: Brotherhood and Service (Days 61–70)
  {
    id: 'day-61', dayNumber: 61, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Do Not Disappear', theme: 'isolation is the enemy, reaching out',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'The man who disappears from his brothers has already lost one gate.',
    teachingBody:
      "The compulsion is patient. It does not need to defeat the man head-on. It only needs him to disappear — to stop returning calls, to skip the gathering, to keep his struggle entirely private, to become a face that nobody has seen in weeks. Isolated men lose battles they would have won in company.\n\nThis is not weakness. It is structure. The nervous system is partly regulated by genuine contact with other people. The man who carries everything alone is fighting on terrain that favors the compulsion. Reaching out before the crisis — not after — changes the terrain.\n\nThe Brother's discipline is simply not to disappear. Send the message. Make the call. Show up at the gathering even when you do not feel like it. The act of remaining present in your relationships is itself a Forge act. It builds something the practice depends on.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "There is a quiet signal that precedes most struggles: the slow withdrawal. The texts go unanswered for a day longer. The friend is not called when normally he would be. The gathering is skipped with a vague excuse. Notice this signal in yourself. It is rarely about the friend. It is usually about a part of the man that does not want to be seen right now. The discipline is to reach out anyway. The act of being witnessed interrupts the spiral.",
    crownFragment: null,
    command: 'Today, reach one brother before any part of you considers disappearing.',
    practice: 'Send one honest message today to someone who matters. No performance, no apology — simply presence.',
    forgeChallenge: 'If you have been withdrawing from anyone who matters, end the withdrawal today with one concrete act of return.',
    journalPrompt: 'Who have I been quietly withdrawing from? Why? What does the withdrawal cost me?',
    eveningAccount: 'Did I remain present to my relationships today, or did I begin to fade?',
    seal: 'The man who stays in contact has half-won the night.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy', 'guard-the-gates'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-62', dayNumber: 62, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: "The Brother's Hand", theme: 'brotherhood, honest presence',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'A brother does not need you to be strong. He needs you to be honest.',
    teachingBody:
      "Modern brotherhood often gets confused with mutual performance: each man presenting his best self, his curated week, his sanded-down version. This kind of contact returns very little. It is essentially two men avoiding each other in the same room.\n\nReal brotherhood requires honest presence. Not unburdening every fear — that is its own performance — but being willing to say what is actually happening when it matters. \"This week has been hard.\" \"I am struggling with the same thing I struggled with last month.\" \"I need to be told the truth.\" These sentences make brotherhood real.\n\nThe Brother offers what is hard to offer: a hand that does not require the receiver to perform strength. That hand, given once, often makes the difference between a lapse and a return.",
    secretContentType: 'forge_assignment', secretTitle: 'Forge Assignment',
    secretBody: "Assignment: choose one brother. Tell him one true thing this week. Not the worst thing, not the most dramatic — one true thing about how the practice is going, or how the week has been, or what you have noticed in yourself. The assignment is to practice the muscle of honesty in relationship. Most men have let this muscle atrophy. It rebuilds quickly when used.",
    crownFragment: null,
    command: 'Tell one brother one true thing today.',
    practice: 'Practice the discipline of honest presence: one real sentence, given to one real person.',
    forgeChallenge: 'Offer the kind of hand to someone today that you wish someone had offered you when you needed it.',
    journalPrompt: 'Who in my life have I been performing for instead of being honest with?',
    eveningAccount: 'Was anything I said today actually true to what I was feeling?',
    seal: 'A brother\'s hand is a hand that does not require performance.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-63', dayNumber: 63, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Speak Before the Fall', theme: 'accountability, honesty before crisis',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'The time to speak is before the hour of weakness, not after.',
    teachingBody:
      "Most men only speak about their struggle after they have lost a round. The lapse has happened; the shame is fresh; the call goes out as a kind of confession. This is better than silence — but it is the second-best version of the practice.\n\nThe first-best is to speak before the fall. Name the vulnerability while it is still abstract. \"I think this week is going to be hard. The hours are bad. The travel is bad. Can I check in with you on Thursday?\" That sentence, spoken in advance, recruits a brother into the practice before the crisis arrives.\n\nThis requires more humility than the post-lapse call. Pre-crisis honesty has no narrative of contrition. It is just admitting, while still standing, that the standing is not guaranteed. The Brother who can speak this way has matured past pride.",
    secretContentType: 'archetype_trial', secretTitle: "The Brother's Trial",
    secretBody: "Trial: this week, speak to one brother about the practice before any crisis. Tell him where you anticipate difficulty in the coming days. Ask him to check in at a specific time. The trial is to break the habit of only speaking after the loss. The man who can speak before he falls rarely has to call after he has fallen.",
    crownFragment: null,
    command: 'Today, speak to one brother about the practice before any crisis.',
    practice: 'Identify the hardest hour or day of your week. Name it in advance to someone who matters.',
    forgeChallenge: 'Set up one accountability check-in this week, before you need it.',
    journalPrompt: 'What stops me from speaking about the practice when I am still standing? What does pride cost?',
    eveningAccount: 'Was I honest in advance, or am I still saving honesty for after the loss?',
    seal: 'Speak before the fall. The man who does this falls less.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-64', dayNumber: 64, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Pride Locks the Door', theme: 'pride vs humility, asking for help',
    season: 'brotherhood_and_service', archetype: 'pilgrim',
    openingLine: "Pride says: I don't need anyone. Humility says: I'll call before it costs me.",
    teachingBody:
      "Pride is one of the compulsion's most useful allies. Not the pride that is dignity — that helps the practice. The pride that refuses help, that insists on doing everything alone, that treats reaching out as a kind of failure. This pride locks the door from the inside and then complains that no one came in.\n\nThe practice eventually exposes this pride. The man notices that he keeps not calling people who could help, not because he doesn't trust them, but because he doesn't want to be seen as a man who needs help. This is a costume of strength worn over a weakness.\n\nThe Pilgrim's humility is plain: the road is hard, the man cannot walk it perfectly alone, and asking for company is not a failure of the road. It is part of how the road is walked. Drop the pride that locks the door. The brothers are on the other side.",
    secretContentType: 'lapse_medicine', secretTitle: 'Lapse Medicine',
    secretBody: "After most lapses, pride wants the man to handle the recovery alone. \"I'll come back when I'm clean.\" \"I'll talk about it once I've made up the ground.\" This is the same pride that locked the door in the first place. The medicine is to speak to one person within forty-eight hours of any lapse — not to confess, just to remain in contact. Isolation after a lapse multiplies its effect. Presence after a lapse divides it.",
    crownFragment: null,
    command: 'Today, notice where pride is locking a door. Open it.',
    practice: 'Identify one ask you have been refusing to make out of pride. Make it today.',
    forgeChallenge: 'Call or message someone who could help with something you have been carrying alone. Ask honestly.',
    journalPrompt: 'What pride do I wear that costs me more than it returns?',
    eveningAccount: 'Did I keep any doors locked today out of pride?',
    seal: "Humility is what unlocks the door pride has been guarding.",
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['shame-weakens-command', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-65', dayNumber: 65, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'A Man Needs Witness', theme: 'being seen, the regulated nervous system',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'No man governs himself well in permanent isolation.',
    teachingBody:
      "There is a feature of the human nervous system the traditions intuited and modern science has confirmed: we regulate partly through contact with other regulated nervous systems. A man surrounded by no one steady tends to become unsteady himself. A man whose week includes real contact with grounded people borrows a stability he could not generate on his own.\n\nThis is not weakness. It is design. The man who does not need witness is not the strong man; he is the man who has not yet noticed that his strength is partly relational. The traditions all knew this. Monasteries. Lodges. Bands of brothers. Sangha. Communities of practice. They were not optional decoration. They were the structure that made the inner work survivable.\n\nThe Brother arranges for witness. Not constant company — solitude is also necessary — but reliable, regular, honest contact with people who see him.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "Recovery research has converged on a finding the traditions stated more poetically: the opposite of compulsion is not willpower. It is connection. Not connection as content — performative or distracting — but connection as genuine regulated witness. One real conversation per week with someone who actually sees the man is worth more than any amount of solitary discipline. Build the witness structure deliberately. The practice depends on it more than it admits.",
    crownFragment: null,
    command: 'Today, arrange one piece of real witness. A call, a meeting, an honest conversation.',
    practice: 'Audit your witness structure: who sees you regularly? Honestly? Strengthen the weakest part this week.',
    forgeChallenge: 'Establish one new piece of recurring witness — a weekly call, a regular meeting, a check-in pattern.',
    journalPrompt: 'Who actually sees me? When was the last time I was actually seen?',
    eveningAccount: 'Was I witnessed today, even briefly?',
    seal: 'Witness is structure, not luxury.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy', 'guard-the-gates'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-66', dayNumber: 66, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Serve Someone', theme: 'service as Forge, outward attention',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: "The man absorbed in another's need has less room for the compulsion.",
    teachingBody:
      "Service is one of the most underused tools in the practice. Not service as performance — that is its own trap. Genuine service: presence to someone else's real need, with no expectation of return, often without anyone knowing you did it.\n\nThe mechanism is simple. The compulsion is self-referential. It loops the man's attention back inward — to his appetite, his discomfort, his cravings. Service interrupts the loop by occupying the channel with someone else's reality. While the man is genuinely attending to another person, the compulsion does not have a strong signal.\n\nThis is not a moral argument for selflessness. It is a practical observation about attention. The Brother who builds a weekly habit of real service is making the compulsion's terrain smaller, week by week.",
    secretContentType: 'night_warning', secretTitle: 'Night Warning',
    secretBody: "When the late hour is hardest, find one person to genuinely help. Even by message. Even by attention. The compulsion is loudest in the self-referential late hour. Service is the most reliable interrupt. The man who learns to redirect his late-night attention to someone else's actual need finds that the urge often disappears not by being defeated but by being unaddressed. Attention elsewhere is the cure for attention here.",
    crownFragment: null,
    command: 'Today, serve someone. Anonymously if possible. Realistically if not.',
    practice: 'Identify one person whose need you can address today. Address it without making it about you.',
    forgeChallenge: 'Build one act of service into your weekly rhythm this week. Repeat next week.',
    journalPrompt: 'Whose need have I been ignoring because I have been absorbed in my own appetite?',
    eveningAccount: 'Did I serve anyone today, or did the whole day go to my own concerns?',
    seal: 'Attention given outward returns the man to himself larger.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['refine-the-fire', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-67', dayNumber: 67, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Repair One Bond', theme: 'repair, honesty, relationship',
    season: 'brotherhood_and_service', archetype: 'healer',
    openingLine: 'One honest repair is worth more than fifty avoided conversations.',
    teachingBody:
      "Most men carry a list of small, unresolved relational debts: the apology not given, the conversation avoided, the message not returned, the gratitude not expressed, the friendship that quietly faded because neither party reached out. Each of these is a small drain on the man's interior. Together, they amount to a chronic background tax that the practice eventually exposes.\n\nRepair is one of the highest-yield Forge acts available. A single honest sentence — \"I've been quiet. I'm sorry. I want to be in touch again\" — can restore a relationship the man assumed was lost. The energy required is small. The return is disproportionate.\n\nThe Healer's discipline is to look at the list and pick one. Not all of them. One. Repair it this week. Then pick the next one.",
    secretContentType: 'forge_assignment', secretTitle: 'Forge Assignment',
    secretBody: "Assignment: this week, perform one real act of relational repair. Not a sweeping apology tour — one real sentence to one real person about one real thing. Keep it specific. Keep it brief. Do not over-explain. The man who can repair one bond per month has, in a year, restored twelve relationships. That is not nothing. It is a different life.",
    crownFragment: null,
    command: 'Today, identify the next repair. Make it.',
    practice: 'List three relational debts. Pick the one most likely to repay attention. Address it today.',
    forgeChallenge: 'Send the message you have been postponing for too long. Send it now, before the day ends.',
    journalPrompt: 'What repair have I been carrying that costs me daily energy to keep avoiding?',
    eveningAccount: 'Did I repair anything today? Even one sentence?',
    seal: 'Small honest repair returns more than any heroic apology tour.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-68', dayNumber: 68, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Leave Isolation', theme: 'structural companionship, not solitary',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'The cell is not the sanctuary. The cell is sometimes the problem.',
    teachingBody:
      "There is a romance to the solitary practitioner: the lone monk, the lone warrior, the man who handles everything in private dignity. The romance is partly true — solitude is required for some of this work. But it can also become a costume for isolation. The man tells himself he is being disciplined when he is actually hiding.\n\nThe traditions all combined solitude with community. The desert hermit visited his elder. The Stoic met with his school. The monk lived in the monastery. The yogi had his guru and his lineage. None of them were doing this alone. The solitary romance is a modern distortion.\n\nThe Brother examines his solitude honestly. Is it the kind that returns the man stronger to his life? Or is it the kind that quietly removes him from it? Real solitude is a tool. Isolation dressed as solitude is a cell.",
    secretContentType: 'ancient_key', secretTitle: 'Ancient Key',
    secretBody: "The Christian Desert Fathers, the most famously solitary practitioners in Western tradition, traveled days to visit each other for honest conversation. The early Buddhist monks were forbidden from living entirely alone for the first years of practice. The traditions knew what modern men sometimes forget: even contemplatives need witness. Solitude without community produces distortion. Community without solitude produces shallow conformity. The practice needs both.",
    crownFragment: null,
    command: 'Today, leave isolation by one concrete act of contact.',
    practice: 'Examine your current ratio of solitude to community. Adjust this week if the balance has tipped.',
    forgeChallenge: 'Plan one act of genuine in-person contact this week. Then plan one act of restorative solitude. Honor both.',
    journalPrompt: 'Is my current solitude the tool, or the cell? How would I know?',
    eveningAccount: 'Was today restorative solitude or quiet isolation?',
    seal: 'Solitude returns the man strong. Isolation removes him.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-69', dayNumber: 69, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Brotherhood Without Grievance', theme: 'non-grievance brotherhood, building up',
    season: 'brotherhood_and_service', archetype: 'brother',
    openingLine: 'Brotherhood is not complaint. It is the shared project of becoming stronger.',
    teachingBody:
      "There is a counterfeit version of brotherhood that has become common: men gathered around shared grievance. The conversation is about what is wrong — with women, with society, with their bosses, with the world. The grievance bonds them, but the bond returns nothing. The men leave each meeting slightly more bitter than when they arrived.\n\nReal brotherhood has a different center. It is the shared project of becoming stronger. The conversation may include difficulty, but the orientation is forward: what is the next gate, the next discipline, the next worthy work. Men who gather around this kind of center build each other up. Men who gather around grievance erode each other in slow motion.\n\nThe Brother chooses his company by this test. Does this man, over time, make me stronger or weaker? Does this gathering, over months, produce growth or grievance? Choose accordingly.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "The grievance counterfeit is seductive because it feels like brotherhood — there is camaraderie, there is shared feeling, there is the sense of being understood. But it produces nothing. After a year, the man is in the same place, just better at complaining. After a year of real brotherhood, the man is somewhere different. Use the year test. The counterfeit fails it every time.",
    crownFragment: null,
    command: 'Today, refuse to be part of any grievance circle. Steer conversation toward what is being built.',
    practice: 'In your conversations today, ask one forward question for every backward complaint.',
    forgeChallenge: 'If you are part of a grievance circle that has been quietly draining you, leave it. Or change its center.',
    journalPrompt: 'Which of my brotherhoods produce growth? Which produce grievance?',
    eveningAccount: 'Did my conversations today build anyone, including me?',
    seal: 'Brotherhood worth keeping is brotherhood that builds.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['refine-the-fire', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-70', dayNumber: 70, arcNumber: 7, arcTitle: 'Brotherhood and Service',
    title: 'Strength Shared Is Strengthened', theme: 'arc 7 milestone, strength multiplied by sharing',
    season: 'brotherhood_and_service', archetype: 'sovereign',
    openingLine: 'Seventy days. The practice has begun to reach beyond the self.',
    teachingBody:
      "Seventy days. The practice that began as inward discipline has, by this point, started reaching beyond the man himself. His brothers have noticed something. His service has touched someone. His way of being present to others has shifted. The practice was never only about him.\n\nThis is one of the truths the rite reveals slowly: strength held alone is fragile. Strength shared is strengthened. The man who builds his discipline only for himself and shares none of it tends to lose it. The man who lets the discipline extend into his relationships, his service, his presence to others, finds that the discipline is held by more than just him.\n\nArc 7 closes with this recognition. The next twenty days are about completing the formation — shadow and crown. But the brotherhood arc, properly done, leaves the man embedded rather than isolated. The crown that arrives on day ninety is, in part, the crown of a man who has practiced not disappearing.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Seventy days. The practice has been extended outward — into brotherhood, into service, into honest presence. This fragment belongs in your Codex: strength shared is strengthened. The man who holds discipline only for himself often loses it. The man who lets it reach into how he serves and shows up multiplies its hold. You have begun this multiplication. Continue it.",
    crownFragment: 'Strength shared is strengthened.',
    command: 'Stand at seventy days and account for what the practice has extended beyond you.',
    practice: 'Read the milestone rite. Name what brotherhood and service have built in the last ten days. Renew the vow with twenty days remaining.',
    forgeChallenge: 'Complete one act today that combines inner discipline with genuine service to another person.',
    journalPrompt: 'How has the practice begun to reach beyond me? Who has felt it?',
    eveningAccount: 'Was the practice shared today, or kept private?',
    seal: 'Strength shared is strengthened. Strength hoarded is lost.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy', 'hold-the-fire'],
    milestoneRiteId: 'rite-day-75', safetyGuardrail: null,
  },

  // Arc 8: The Shadow and the Return (Days 71–80)
  {
    id: 'day-71', dayNumber: 71, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'The Shadow Speaks', theme: 'shadow, Jungian recognition, naming darkness',
    season: 'brotherhood_and_service', archetype: 'sage',
    openingLine: 'The shadow does not destroy the man who names it. It destroys the man who never does.',
    teachingBody:
      "Jung used the word *shadow* for the disowned parts of the self — the impulses, hungers, angers, and patterns the conscious mind would prefer not to belong to it. The shadow does not disappear when ignored. It runs the man from underneath, surfacing in the form of compulsions, projections, and unexplained reactivity.\n\nThe practice eventually requires looking at the shadow. Not wallowing in it, not making a religion of it, but seeing it. The man who can name what he has not wanted to see in himself takes back some of the power the unnamed material had over him. What is named loses some of its grip.\n\nThis arc is about that work. The Sage's first task is recognition: there are things in me I have been managing not to look at. They are part of why the compulsion has had purchase. They are also workable, if I can stay with looking.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "The shadow is not evil. It is unintegrated. The angry man who refuses to admit his anger is more dangerous than the angry man who knows what he carries. The compulsive pattern that is denied has more power than the one that is named. Shadow work is not confession. It is intelligence. Once material is named, it becomes available to be worked with rather than reacted from. Begin with one thing you have been managing not to see. One is enough.",
    crownFragment: null,
    command: 'Today, name one shadow material honestly. To yourself first. Possibly to one other.',
    practice: 'Sit ten minutes with a difficult inward truth without rushing to resolve it.',
    forgeChallenge: 'Speak one shadow honestly to one trusted person today. Not the worst. The one you are ready to begin with.',
    journalPrompt: 'What in me have I been managing not to look at? Why?',
    eveningAccount: 'Did I see anything in myself today that I usually do not let myself see?',
    seal: 'The shadow named is the shadow workable.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'man-is-never-enemy'],
    milestoneRiteId: null,
    safetyGuardrail: 'This is philosophical and psychological inspiration, not a substitute for professional support.',
  },
  {
    id: 'day-72', dayNumber: 72, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Shame Is Not Command', theme: 'shame vs guilt, healing vs punishment',
    season: 'brotherhood_and_service', archetype: 'healer',
    openingLine: 'Shame says you are the problem. Guilt says you did a wrong thing. Only one is useful.',
    teachingBody:
      "There is an important distinction the practice eventually requires the man to make: between guilt and shame. Guilt is the recognition that a specific act was wrong. It is workable. It motivates repair. It dissolves once repair is done. Shame is different. Shame says the man himself is wrong — not the act, but the being. Shame does not motivate repair. It motivates hiding. It does not dissolve. It accumulates.\n\nMost men who struggle with compulsion are running not only on the compulsion but on a deep undercurrent of shame about it. This undercurrent makes the next lapse more likely, not less. Shame is the compulsion's most loyal employee.\n\nThe Healer's discipline is to separate the two carefully. Specific guilt about specific acts: useful. Diffuse shame about being the kind of man who has these struggles: corrosive. Let the first do its work. Set the second down — not because it is unfounded but because it is unhelpful.",
    secretContentType: 'lapse_medicine', secretTitle: 'Lapse Medicine',
    secretBody: "After a lapse, watch the inner narrator. The narrator who says \"I did a thing I do not want to do; let me see what happened and repair\" is useful. The narrator who says \"I am the kind of man who cannot do this; this is who I am; nothing will change\" is the compulsion's voice in a different costume. The second narrator must be refused. Not argued with — refused. \"Not that voice. Not now.\" Then return to the first narrator and the work of clean recovery.",
    crownFragment: null,
    command: 'Today, distinguish guilt from shame. Use the first. Refuse the second.',
    practice: 'When you notice shame talking — \"I am the problem\" — translate to specific guilt: \"This act was wrong; what is the repair?\"',
    forgeChallenge: 'Do one clean act of repair today motivated by useful guilt, not by shame.',
    journalPrompt: 'When does shame speak in me? What does it sound like? Has it ever helped me?',
    eveningAccount: 'Did shame run me anywhere today? Did I notice it for what it was?',
    seal: 'Guilt repairs. Shame hides. Choose the workable one.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['shame-weakens-command', 'man-is-never-enemy', 'lapse-is-information'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-73', dayNumber: 73, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'The Pattern Beneath the Pattern', theme: 'root patterns, second-layer work',
    season: 'brotherhood_and_service', archetype: 'sage',
    openingLine: 'Behind the habit of the urge is usually a pattern that the urge is solving.',
    teachingBody:
      "The compulsion is often a surface symptom of something deeper. The urge solves a problem the man may not consciously be tracking: it medicates loneliness, it discharges anger, it numbs a grief, it relieves a chronic anxiety, it answers a question he cannot otherwise face. The compulsion is rarely the root. It is the most available exit from a deeper room.\n\nThis is not an excuse — the practice still requires the discipline of the surface. But sustainable retention often requires also attending to the deeper room. The man who only fights the surface symptom while leaving the root untouched is fighting a long, exhausting war.\n\nThe Sage's second-layer work is to ask, gently: what is the urge actually solving? What state does it medicate? What feeling does it discharge? The answers are not always immediately clear. But asking the question consistently begins to reveal the pattern beneath the pattern.",
    secretContentType: 'ancient_key', secretTitle: 'Ancient Key',
    secretBody: "Buddhist teaching describes *vedanā* — the felt tone of an experience as pleasant, unpleasant, or neutral — and *taṇhā* — the craving response. The cycle runs: unpleasant feeling arises, craving offers a fix, craving leads to action, action briefly relieves, the cycle resets. The practice interrupts this not only at the action stage but earlier, at the recognition of *vedanā*: \"this is the unpleasant feeling I usually try to fix with the urge.\" Naming the *vedanā* gives the man options the compulsion does not.",
    crownFragment: null,
    command: 'Today, when the urge arrives, ask once: what state is this trying to solve?',
    practice: 'Track for three days: what feeling precedes the urge most often? Loneliness? Anger? Boredom? Anxiety? Note it.',
    forgeChallenge: 'Address the underlying state directly today instead of through the urge. Eat if hungry, call if lonely, train if angry.',
    journalPrompt: 'What state does the compulsion most reliably medicate for me? What would address that state directly?',
    eveningAccount: 'Did I see beneath the urge today, or only fight its surface?',
    seal: 'The urge is the symptom. The root is the work.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'energy-is-ally'],
    milestoneRiteId: null,
    safetyGuardrail: 'Deeper patterns may benefit from professional support. This is philosophical inspiration, not therapy.',
  },
  {
    id: 'day-74', dayNumber: 74, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Anger Guards Grief', theme: 'anger as protector, grief work',
    season: 'brotherhood_and_service', archetype: 'warrior',
    openingLine: 'Beneath the anger is often a grief the man has not been permitted to feel.',
    teachingBody:
      "Men in most cultures are given a very narrow band of acceptable emotion. Anger is one of the few permitted — it codes as strength. Grief, fear, longing, tenderness — these are often coded as weakness and pushed underground. What happens then is predictable: the unpermitted feelings still exist, but they leak out through the one channel that is allowed. Anger that is actually grief. Irritability that is actually loneliness. Aggression that is actually fear.\n\nFor the practice, this matters because the compulsion often feeds on this conversion. The man feels a strong sensation he has been trained not to name. The compulsion offers a familiar discharge. The deeper feeling is buried again.\n\nThe Warrior who matures learns to let the underlying feeling exist. Not perform it, not wallow in it — simply allow it to be present long enough to be recognized. This is hard, slow work. It is also some of the most freeing work the practice contains.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "There is a brief practice the traditions converge on: when a strong feeling arises and is hard to name, sit with it for one full minute without acting on it. Just feel it. Do not try to fix it, perform it, or argue with it. Sixty seconds. Most feelings, when actually felt for one minute, soften into their truer shape: the anger becomes grief, the agitation becomes fear, the restlessness becomes loneliness. Once the truer shape is named, it can be addressed honestly.",
    crownFragment: null,
    command: 'Today, when a strong feeling arrives, sit with it for one minute before doing anything with it.',
    practice: 'Practice the one-minute sit. Let the feeling become whatever it actually is underneath.',
    forgeChallenge: 'If a real grief or loss has been waiting to be felt, let it have ten minutes today. With dignity. Without theater.',
    journalPrompt: 'What feeling have I been routing through anger that might be something else underneath?',
    eveningAccount: 'Did I feel anything truly today, or did I keep converting it into something more permitted?',
    seal: 'A feeling truly felt completes faster than a feeling endlessly avoided.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy', 'lapse-is-information'],
    milestoneRiteId: null,
    safetyGuardrail: 'Significant grief or trauma may benefit from professional support. This is inspiration, not therapy.',
  },
  {
    id: 'day-75', dayNumber: 75, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'The Wound Is Not the Throne', theme: 'milestone, wound healed not worshiped',
    season: 'brotherhood_and_service', archetype: 'healer',
    openingLine: "Seventy-five days. You have looked at the shadow. It is not the throne.",
    teachingBody:
      "A man can become attached to his wound. The wound becomes identity. The struggle becomes the story he tells about himself. The shadow becomes a kind of throne he sits on, because at least the throne is occupied. Wound-as-identity is one of the subtle traps the practice eventually has to address.\n\nThe wound is real. It deserves to be seen, named, and worked with. But it is not the throne. The throne belongs to the man — the integrated man who has a wound among many other things. The wound is part of the kingdom. It is not the kingdom.\n\nThe milestone of day seventy-five marks this distinction. The shadow has been looked at honestly. It has been named. The work is real. But the man is not the wound, and the wound is not the throne. The throne belongs to the Sovereign returning, not to the wound demanding rule.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Seventy-five days. The shadow has been worked. This fragment belongs in your Codex: the wound is not the throne. The man who organizes his life around his wound stays small. The man who recognizes his wound, treats it honestly, and returns to building does the work the wound itself was asking for. Treat the wound. Do not crown it. The throne belongs to the man.",
    crownFragment: 'The wound is not the throne.',
    command: 'Stand at day seventy-five and account for the shadow work without crowning it.',
    practice: 'Read the milestone rite. Name what you have looked at honestly. Renew the vow with the wound in its place.',
    forgeChallenge: 'Do one act today that the man-beyond-the-wound would do. Not the wounded man. The man.',
    journalPrompt: 'Where in my life am I treating the wound as the throne? What would it look like to demote it?',
    eveningAccount: 'Who sat on the throne today — me, or the wound?',
    seal: 'The wound is part of the kingdom. It is not the kingdom.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['man-is-never-enemy', 'return-to-order'],
    milestoneRiteId: 'rite-day-75', safetyGuardrail: null,
  },
  {
    id: 'day-76', dayNumber: 76, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Return Without Theater', theme: 'clean return, no drama, lapse medicine',
    season: 'the_integrated_man', archetype: 'pilgrim',
    openingLine: 'The drama of the fall is not the fall. It is the next lapse in preparation.',
    teachingBody:
      "Some men, after a lapse, perform a grand collapse — the dramatic remorse, the sweeping vow, the inner courtroom, the long stretch of self-punishment. They mistake the drama for the seriousness of the practice. It is the opposite. The drama is wasted energy that the next lapse will use.\n\nThe Pilgrim's return is clean. Stand up. Name what happened, briefly and honestly. Notice the lesson. Repair what can be repaired. Take the next clean step. No theater, no grand vow, no public penance. Just the return.\n\nThis is harder than the drama. The drama feels like seriousness. The clean return feels like nothing. But the clean return is what actually preserves the practice. The drama burns the energy the practice needs.",
    secretContentType: 'lapse_medicine', secretTitle: 'Lapse Medicine',
    secretBody: "After any lapse: ninety seconds of honest acknowledgment, ten minutes of writing the lesson, one act of clean recovery, then back to the practice in its normal rhythm. That is the protocol. The grand vow, the long remorse, the dramatic confession — refuse them. They feel like seriousness; they are theater. The clean return is the seriousness. The compulsion prefers the drama because the drama produces fatigue, and the next lapse loves a tired man.",
    crownFragment: null,
    command: 'If you have fallen recently, return cleanly today. No theater. Just the return.',
    practice: 'Practice the clean return protocol on any setback: acknowledge briefly, learn briefly, repair briefly, continue.',
    forgeChallenge: 'Take any current setback and apply the clean return today. Refuse to make a religion of it.',
    journalPrompt: 'When have I substituted drama for actual repair? What did it cost the next round?',
    eveningAccount: 'Did any return today happen cleanly, or did I dramatize it?',
    seal: 'Clean return is the discipline. Drama is the substitute.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'shame-weakens-command'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-77', dayNumber: 77, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Clean the Wound', theme: 'repair vs worshiping the wound',
    season: 'the_integrated_man', archetype: 'healer',
    openingLine: 'Clean it. Do not live in it.',
    teachingBody:
      "Cleaning a wound is not denying the wound. It is honoring it through the work of healing. The opposite of cleaning a wound is not ignoring it. It is worshiping it: returning to it, picking at it, telling its story repeatedly, organizing one's interior around it.\n\nThe practice eventually requires this distinction. The shadow has been seen; the patterns have been named. Now they must be treated rather than enshrined. Treatment is concrete: changes in behavior, changes in environment, changes in relational structure, sometimes professional help, sometimes specific small daily practices. Enshrinement is talking and re-talking the wound without changing anything.\n\nThe Healer's discipline is to move from naming to treating. The naming was the first work. The treating is the next. The man who does both heals; the man who only names stays at the entrance.",
    secretContentType: 'forge_assignment', secretTitle: 'Forge Assignment',
    secretBody: "Assignment: identify one piece of the wound that has been adequately named and is now ready for treatment. Decide on one concrete change in behavior, environment, or relational structure that addresses it. Begin the change today. Not the perfect treatment. The next available treatment. The Healer trusts that movement toward healing is better than perfect understanding without movement.",
    crownFragment: null,
    command: 'Today, move from naming the wound to treating it. One concrete change.',
    practice: 'Identify one shadow pattern that has been named long enough. Choose one treatment today.',
    forgeChallenge: 'Make one structural change in your life today that the wound has been asking for.',
    journalPrompt: 'What part of the wound have I been naming for too long without treating?',
    eveningAccount: 'Did I treat any wound today, or just visit it?',
    seal: 'Naming is the door. Treatment is the room.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'lapse-is-information'],
    milestoneRiteId: null,
    safetyGuardrail: 'Some wounds benefit from professional support. The practice complements, not replaces, real help.',
  },
  {
    id: 'day-78', dayNumber: 78, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Study the Lapse', theme: 'post-lapse analysis, intelligence gathering',
    season: 'the_integrated_man', archetype: 'sage',
    openingLine: 'A lapse studied is information. A lapse repeated is a pattern waiting for attention.',
    teachingBody:
      "Every lapse, looked at carefully, contains a small intelligence file: what state preceded it, what voice spoke, what gate was open, what hour it was, what was missing earlier in the day, what permission was granted. This information is useful — but only to the man who collects it instead of drowning it in shame.\n\nThe practice eventually requires building this intelligence file deliberately. Not as self-flagellation, not as dwelling — as research. The compulsion has patterns. The patterns can be mapped. Once mapped, they can be interrupted at earlier points where interruption is easier.\n\nThe Sage's discipline is to study what happened with the detachment of an investigator. The investigator is not the criminal. The investigator is the man who wants to understand the case so it does not repeat.",
    secretContentType: 'archetype_trial', secretTitle: "The Sage's Trial",
    secretBody: "Trial: write a short, honest report on your most recent lapse or near-lapse. What state preceded it by twelve hours? Six hours? One hour? What was the first crack? What voice spoke? What permission was given that should not have been given? What gate was open that should have been closed? Read the report once. File it. Use it to set tomorrow's structure. The report is intelligence; do not turn it into a confession.",
    crownFragment: null,
    command: 'Today, study the last lapse or near-lapse as intelligence. No shame, no drowning.',
    practice: 'Write the lapse report. Twelve hours back, six hours, one hour. Map the chain.',
    forgeChallenge: 'Use the intelligence to set one structural change for the coming week. Specific.',
    journalPrompt: 'What does the chain of the last lapse show me about where to intervene earlier?',
    eveningAccount: 'Did I gather intelligence from anything today, or only feel about it?',
    seal: 'The investigator is not the criminal. The investigator solves the case.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['lapse-is-information', 'pause-is-where-manhood-begins'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-79', dayNumber: 79, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'Build the Boundary', theme: 'structural response to shadow learning',
    season: 'the_integrated_man', archetype: 'guardian',
    openingLine: 'The boundary built after the lapse is stronger than the one built before it.',
    teachingBody:
      "The intelligence gathered through honest shadow work has one main use: it tells the man where the next boundary needs to be. Pre-lapse boundaries are guesses. Post-lapse boundaries are informed by data. They tend to be more specific, more targeted, more effective.\n\nA boundary is not a moral fence. It is a structural commitment: an environmental change, a time rule, a relational protocol, a piece of physical or digital architecture that makes the unwanted behavior measurably harder to perform on autopilot. \"I will not\" is a boundary. \"I will not, and the phone is in another room from 9 PM, and Tuesday nights I am at the gym, and on Sundays I check in with X\" is a boundary system.\n\nThe Guardian's work in arc 8 is to build these boundaries informed by what the shadow work has revealed. Not from shame. From data.",
    secretContentType: 'night_warning', secretTitle: 'Night Warning',
    secretBody: "The boundaries built in calm daylight, written down with structure, are the boundaries that hold at 11 PM. The boundaries decided in the moment of temptation almost never hold. Treat the building of boundaries as separate work from the keeping of them. Build them when calm. Keep them when tested. The hour of temptation is not the hour to legislate; it is the hour to obey what was already legislated.",
    crownFragment: null,
    command: 'Today, build one new boundary informed by what the shadow work has revealed.',
    practice: 'Translate the lapse intelligence into one specific, structural commitment. Write it down.',
    forgeChallenge: 'Implement the new boundary tonight. Make it real before the temptation hour arrives.',
    journalPrompt: 'What boundary is the data of the past month asking for?',
    eveningAccount: 'Did I build any boundary today that will hold tomorrow night?',
    seal: 'A boundary is law passed when calm and obeyed when tested.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates', 'return-to-order'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-80', dayNumber: 80, arcNumber: 8, arcTitle: 'The Shadow and the Return',
    title: 'The Pilgrim Continues', theme: 'arc 8 milestone, eighty days',
    season: 'the_integrated_man', archetype: 'pilgrim',
    openingLine: 'Eighty days. The shadow has been looked at. The path continues.',
    teachingBody:
      "Eighty days. The arc that began with looking at the shadow now closes. The man has done the work that most men never do: he has looked honestly at the patterns underneath the surface struggle, named what he saw, distinguished guilt from shame, refused to crown the wound, and begun to translate what he found into structural change.\n\nThe Pilgrim's truth is at the center of this arc: the path is not for the man who never falls. The path is for the man who keeps the road. Every tradition that takes formation seriously has known this. The completed man is not the one with no struggles. He is the one with practiced returns.\n\nTen days remain. The crown is in sight. The man who arrives at day ninety will not arrive perfect. He will arrive formed: shaped enough by the work to carry the fire into ordinary life.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Eighty days. The shadow arc closes. This fragment belongs in your Codex: the Pilgrim is not the man who never falls. He is the man who keeps the road. Most men quit at the first sustained difficulty because they expect the path to be smooth. The path is not smooth for anyone. The discipline is to keep walking. You have kept walking for eighty days. That is what is being honored.",
    crownFragment: 'The Pilgrim is not the man who never falls. He is the man who keeps the road.',
    command: 'Stand at eighty days and honor the road kept.',
    practice: 'Read the milestone rite. Acknowledge the shadow work honestly. Renew the vow with ten days remaining.',
    forgeChallenge: 'Complete one act today that the man who began this rite eighty days ago could not have completed.',
    journalPrompt: 'What has changed in me that the shadow work made possible?',
    eveningAccount: 'Was the road kept today?',
    seal: 'Keep the road. That is the whole instruction.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'hold-the-fire'],
    milestoneRiteId: 'rite-day-75', safetyGuardrail: null,
  },

  // Arc 9: The Crown (Days 81–90)
  {
    id: 'day-81', dayNumber: 81, arcNumber: 9, arcTitle: 'The Crown',
    title: 'The Integrated Man', theme: 'integration, all parts in order',
    season: 'the_integrated_man', archetype: 'sovereign',
    openingLine: 'The integrated man does not suppress appetite. He governs it.',
    teachingBody:
      "Integration is the goal the whole rite has been moving toward. Not a man without appetite — that is not a man. Not a man without anger or grief or fear — that is not honest. The integrated man has all the parts a man has, and the parts are ordered around something. They serve a center. They do not pull in different directions.\n\nThis arc names that center: the crowned man, the Sovereign, the king who has practiced returning to the throne so many times that the throne is now his by familiarity. The appetite is present and ordered. The spirit is trained and useful. The reason is awake and governs. The shadow has been seen and is not in charge.\n\nThe Sovereign at the start of arc 9 is not finished. He is formed enough to take responsibility for his own continued formation. That is the threshold the rite is preparing him to cross.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "Integration is not the disappearance of the parts. It is their ordered coexistence. A man who feels no anger is not integrated; he is suppressed. A man who feels anger and channels it toward worthy targets is integrated. The same is true of every appetite the practice has met. The crown is not the absence of desire. It is desire properly directed. The Sovereign owns this. The man at the start of his formation does not yet.",
    crownFragment: null,
    command: 'Today, govern the parts. Allow each its presence. Direct each toward its proper end.',
    practice: 'Notice once per part — appetite, spirit, reason — and where each is pointed today.',
    forgeChallenge: 'Make one decision today that uses all three parts in alignment. Hard work, courageous spirit, clear reason.',
    journalPrompt: 'Where in me are the parts now ordered? Where are they still arguing?',
    eveningAccount: 'Were all the parts present today, working together?',
    seal: 'Integration is parts present and ordered, not parts erased.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'hold-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-82', dayNumber: 82, arcNumber: 9, arcTitle: 'The Crown',
    title: 'Power Without Ego', theme: 'mature power, quiet authority',
    season: 'the_integrated_man', archetype: 'king',
    openingLine: 'The man who has to announce his strength does not yet own it.',
    teachingBody:
      "Young strength announces itself. It performs, it postures, it lets everyone know it is here. Mature strength does not need to. It is quietly present, available when needed, indifferent to recognition. The difference is not skill but ownership: the man who has not yet integrated his strength has to constantly show it to himself. The man who has integrated it can simply use it.\n\nThe practice produces this maturation in part. After ninety days of holding the fire, the man who has been honest no longer has to perform the holding. He simply holds. The performance was for an audience that was never coming. The strength was for him.\n\nThe King's discipline at this stage is to let the announcement drop. Strength used in service of something — work, family, brotherhood, real making — does not need an audience. The audience adds nothing. Sometimes it subtracts.",
    secretContentType: 'ancient_key', secretTitle: 'Ancient Key',
    secretBody: "The Daoist *wu wei* — sometimes translated as effortless action — describes power exercised without strain. The mature king does not strain to be king. The mature warrior does not strain to be courageous. They have become what they practice. Strain is the signature of unintegrated effort. The man who has practiced ninety days finds that some of the early strain has dropped away. The practice still requires attention; it requires less performance.",
    crownFragment: null,
    command: 'Today, use strength without announcing it. Quietly, in service of something real.',
    practice: 'Notice every impulse to perform your discipline today. Refuse it. Just live the discipline.',
    forgeChallenge: 'Do one strong act today that no one will know you did. Let it stand without record.',
    journalPrompt: 'Where am I still performing strength I have already built? What would dropping the performance look like?',
    eveningAccount: 'Was today\'s strength quiet, or did I need to display it?',
    seal: 'Power that needs an audience is borrowed. Power that does not is yours.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['hold-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-83', dayNumber: 83, arcNumber: 9, arcTitle: 'The Crown',
    title: 'Desire With Direction', theme: 'directed desire, permanent practice model',
    season: 'the_integrated_man', archetype: 'sovereign',
    openingLine: 'The desire does not leave. The direction becomes stable.',
    teachingBody:
      "It is important to be honest about what the ninety days do and do not do. They do not produce a man without desire. They do not eliminate appetite. They do not make the body new. The body continues to be the body, with its hungers and its rhythms and its insistent aliveness.\n\nWhat the ninety days can produce is something more useful: stable direction. The desire is still there, but it points somewhere. Toward worthy work. Toward training. Toward real relationships. Toward service. Toward attention itself. The desire is no longer constantly being hijacked by the easiest available outlet because the harder, worthier outlets have become more habitual.\n\nThe Sovereign's truth about the long path: desire never leaves; direction becomes more reliable. That is the equipment the man is being given. It is not the equipment the marketing of \"victory\" suggests. It is better, because it is the equipment that actually works for a life.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Eighty-three days. Most men would be celebrating the elimination of desire. The practice does not eliminate it. The practice directs it. This fragment belongs in your Codex: desire with direction is not a problem. It is a life. The man who waits for desire to disappear before he considers himself free will wait forever. The man who lets desire point toward worthy things is free now.",
    crownFragment: 'Desire with direction is not a problem. It is a life.',
    command: 'Today, let desire have direction. Do not negotiate it away. Point it.',
    practice: 'Each time desire arises today, ask: where would the trained man let this point?',
    forgeChallenge: 'Channel one strong desire today into the most ambitious worthy form available.',
    journalPrompt: 'What does desire look like now compared to day one? Where does it tend to point?',
    eveningAccount: 'Was desire directed today, or did it scatter?',
    seal: 'Desire with direction is not a problem. It is a life.',
    contentStatus: 'final',
    relatedStudyIds: ['the-inner-forge-transmutation'],
    relatedPrincipleIds: ['energy-is-ally', 'refine-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-84', dayNumber: 84, arcNumber: 9, arcTitle: 'The Crown',
    title: 'The Crown Is Responsibility', theme: 'leadership, the crown as burden and honor',
    season: 'the_integrated_man', archetype: 'king',
    openingLine: 'The crown is not a reward for perfection. It is a commission for maturity.',
    teachingBody:
      "There is a common misunderstanding about what the crown means. It is not a prize for the man who has finally won. It is a commission for the man who has matured enough to be entrusted with something. The crown carries weight. The man who reaches for it as a reward will be surprised by what it actually asks of him.\n\nWhat does it ask? That the man take responsibility for his continued formation. That he take responsibility for the brothers around him who are earlier in their walk. That he refuse the temptation to use his discipline as a status marker. That he serve the things larger than himself that the practice has prepared him to serve.\n\nThe King's truth on day eighty-four is that the crown about to arrive is not a finish line. It is a beginning of a different kind of work: the responsibility to live what has been built, in ordinary life, without an audience, for the rest of the life that follows.",
    secretContentType: 'forge_assignment', secretTitle: 'Forge Assignment',
    secretBody: "Assignment: write down what taking responsibility looks like after day ninety. Specifically. Not aspirations. Concrete commitments. What daily practice will continue? What service will be ongoing? What brothers will be checked in on? What boundaries will remain in force? What boundaries will be strengthened? The Long Path begins on day ninety-one. Begin the architecture today.",
    crownFragment: null,
    command: 'Today, treat the approaching crown as commission, not reward.',
    practice: 'Sketch the Long Path: what daily, weekly, monthly practices will carry the formation forward after day ninety?',
    forgeChallenge: 'Begin one Long Path commitment today, before the crown arrives. Live it now.',
    journalPrompt: 'What is the crown actually going to ask of me? Am I ready to accept the ask?',
    eveningAccount: 'Did I act today like a man preparing for responsibility, or like a man chasing a reward?',
    seal: 'The crown is a commission. The man wears it as service.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'hold-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-85', dayNumber: 85, arcNumber: 9, arcTitle: 'The Crown',
    title: 'The Long Path', theme: 'preparing for post-90, what comes after',
    season: 'the_integrated_man', archetype: 'sovereign',
    openingLine: 'Ninety days prepares the man. The Long Path is where he lives.',
    teachingBody:
      "The ninety days are formation. The Long Path is life. The formation prepares the man to carry the fire into ordinary life — into the marriage that did not pause for the practice, into the work that did not slow down, into the long stretches when no milestone is coming, into the years when there is no rite arc to mark the time.\n\nThe Long Path requires a different rhythm. The daily rituals continue, but the structure becomes lighter. The fire is held more by habit and less by attention. The brothers remain in place. The service continues. The boundaries remain operative. The man checks in with his witness regularly. The Forge continues to receive the fire. But the structure is for life, not for a season.\n\nThe Sovereign on the long path is not always inspired. He is reliable. The inspiration of the early days gives way to the deeper reliability of a man who has practiced this long enough to no longer be impressed with himself for doing it.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "The Long Path's main test is the unmarked stretch. There is no milestone next week. There is no arc ending soon. There is just the practice, day after day, season after season. The man who can keep the practice without external structure has crossed into something the early days only hinted at. The traditions call this stage by various names — the householder yogi, the mature monk who has returned to the world, the elder. The names matter less than the reality: the practice has become how the man lives, not a project he is doing.",
    crownFragment: null,
    command: 'Today, see what the Long Path looks like for you. Sketch it concretely.',
    practice: 'Write the structure of week one of the Long Path: daily practices, weekly check-ins, monthly review.',
    forgeChallenge: 'Build the Long Path schedule into your calendar today. Recurring, durable, real.',
    journalPrompt: 'What does the practice look like as a way of life, not a season?',
    eveningAccount: 'Did I prepare for the Long Path today, or only for the milestone?',
    seal: 'The Long Path is where the formation actually lives.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['hold-the-fire', 'return-to-order'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-86', dayNumber: 86, arcNumber: 9, arcTitle: 'The Crown',
    title: 'Rule the Ordinary Day', theme: 'ordinary life, daily sovereignty, no audience',
    season: 'the_integrated_man', archetype: 'king',
    openingLine: 'The ordinary day is where the practice lives or dies.',
    teachingBody:
      "There is a temptation, near the end of the rite, to imagine that after the crown the practice will be carried by some elevated state. It will not. After the crown there is mostly the ordinary day: the same commute, the same difficult coworker, the same late-evening tiredness, the same body, the same temptations in lighter or heavier form.\n\nThe ordinary day is where the practice actually lives. Not the retreat. Not the milestone. Not the inspired week. The Tuesday afternoon that has nothing to recommend it. The Sunday night that goes a little long. The hour of work that did not need to be that hard but was. These are the hours that the practice was for.\n\nThe King rules ordinary days. He does not save his sovereignty for the special moments. He brings it to the small ones. That is how the kingdom is held over time.",
    secretContentType: 'archetype_trial', secretTitle: "The King's Trial",
    secretBody: "Trial: choose one ordinary day this week and rule it deliberately. Not a day with high stakes or special meaning. An average Tuesday. From morning to night, govern the small things — speech, room, body, time — as if they all mattered. They do. The ordinary day, ruled, is the unit of the Long Path. The man who can rule one ordinary day can rule a year of them. The man who only rules special days will not rule a life.",
    crownFragment: null,
    command: 'Today, treat the ordinary as the substance. Rule it as such.',
    practice: 'Govern the small things today with the same care you would give a milestone day.',
    forgeChallenge: 'Take the most ordinary stretch of today and bring full presence to it. Notice what happens.',
    journalPrompt: 'Which ordinary days have I been treating as filler? What would treating them as substance change?',
    eveningAccount: 'Did I rule today, even though it was ordinary?',
    seal: 'The kingdom is held by ordinary days well-ruled.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['return-to-order', 'hold-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-87', dayNumber: 87, arcNumber: 9, arcTitle: 'The Crown',
    title: 'Teach Without Preaching', theme: 'witness, quiet example, not proselytizing',
    season: 'the_integrated_man', archetype: 'brother',
    openingLine: 'The crowned man does not preach. He is present in a way that speaks.',
    teachingBody:
      "After the practice produces real change, the man may be tempted to talk about it. To friends, to family, to anyone who will listen. The temptation is usually well-meant. It is also usually a mistake. Preaching from a position of having just succeeded tends to repel the very people the man hopes to reach. It often signals fragility rather than strength: the man needs to convince others to confirm his own conviction.\n\nThe better path is harder: live the practice visibly without explaining it. Let those who notice ask. Answer briefly and honestly when asked. Make no effort to recruit. The example does the work that argument cannot.\n\nThe Brother's discipline here is restraint. The discipline is for him. Sharing it with others is not the validation he might think it is. The man whose life quietly changes — who is calmer, more reliable, more present — communicates something about the practice that no sermon can.",
    secretContentType: 'hidden_teaching', secretTitle: 'Hidden Teaching',
    secretBody: "The Confucian *junzi* — the noble man — was said to teach mainly by presence. People did not always know why they trusted him; they trusted him. The same dynamic applies to a man who has been formed. His brothers, his family, the people around him will notice. Some will ask. Most will not. Both responses are fine. The practice is not a movement to grow. It is a life to live. Live it. Let those who want it find their way.",
    crownFragment: null,
    command: 'Today, refuse to preach. Let presence do whatever teaching is needed.',
    practice: 'When tempted to explain the practice to someone today, restrain it. Live it instead.',
    forgeChallenge: 'Be quietly present to someone today in a way that communicates without arguing.',
    journalPrompt: 'Where have I been tempted to preach? What was the temptation actually asking for?',
    eveningAccount: 'Did I preach today, or did I simply live what I have built?',
    seal: 'Presence teaches what preaching cannot.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['hold-the-fire', 'man-is-never-enemy'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-88', dayNumber: 88, arcNumber: 9, arcTitle: 'The Crown',
    title: 'Carry the Fire Quietly', theme: 'quiet strength, fire without announcement',
    season: 'the_integrated_man', archetype: 'sovereign',
    openingLine: 'The fire that is used does not need to be displayed.',
    teachingBody:
      "Two days from the crown. The practice has reshaped the man enough that the early triumphalism is gone. He does not need the world to know what he has done. The fire is being used; the work is being made; the life is being lived. The display is no longer needed because the fire is no longer just potential — it is moving into form.\n\nThis is the quiet that the early days could not produce because the early days were too noisy. The compulsion was loud, the wins felt dramatic, the losses felt catastrophic. Now both have settled. The man holds the fire as a matter of course. He does not perform the holding. He does not need to.\n\nThe Sovereign carries the fire quietly. This is the posture the crown of day ninety will recognize: the man who has the fire and does not need to wave it around. He uses it. He builds with it. He gives it to what deserves it. He sleeps well and starts again the next day.",
    secretContentType: 'night_warning', secretTitle: 'Night Warning',
    secretBody: "Even at day eighty-eight, the late hour can still test the man. The crown is in sight, and the compulsion sometimes makes a last, plausible argument: \"You have already done it. One night will not change anything.\" Recognize this argument by its style: it is the same argument from day six, dressed in graduation robes. Refuse it the same way: not by debate, by not granting it the audience. Two more nights. Then the long path. The same vigilance.",
    crownFragment: null,
    command: 'Today, carry the fire as a matter of course. No display.',
    practice: 'Use the fire on real work, real training, real service. Do not announce the use.',
    forgeChallenge: 'Do one substantial Forge act today and tell no one about it.',
    journalPrompt: 'What has the fire become in me at this point? How do I carry it?',
    eveningAccount: 'Was the fire used today, quietly?',
    seal: 'Carry the fire. Do not announce it.',
    contentStatus: 'final',
    relatedStudyIds: ['the-inner-forge-transmutation'],
    relatedPrincipleIds: ['hold-the-fire', 'refine-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-89', dayNumber: 89, arcNumber: 9, arcTitle: 'The Crown',
    title: 'The Final Gate', theme: 'penultimate day, last preparation',
    season: 'the_integrated_man', archetype: 'guardian',
    openingLine: 'One more day of preparation. The crown is earned by what you do today, not tomorrow.',
    teachingBody:
      "The day before the crown is not a different day. It is the same practice, performed once more, with the same attention. There is a temptation to treat it as ceremonial — to relax slightly, knowing the milestone is essentially achieved. This temptation is the compulsion's last good argument. Refuse it.\n\nThe crown is not received on day ninety because day ninety is special. It is received on day ninety because the man has performed the practice for eighty-nine days, including today, with attention. The crown is the cumulative integrity of the days. Today is one of those days. Treat it as one.\n\nThe Guardian holds the gate on day eighty-nine as if there were many more days to come. Because there are. The crown opens the Long Path, where the practice continues in a different rhythm but the same essential form. The discipline of today is rehearsal for what comes after.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Eighty-nine days. One gate remains. This fragment belongs in your Codex: the final gate is kept by the same discipline as the first. There is no special technique for the last day. There is the practice — the same practice, performed once more. The man who treats the last day as different has not yet understood the practice. The man who treats every day as one of many is already in the Long Path. Stand at the gate today. The crown opens tomorrow because today held.",
    crownFragment: 'The final gate is kept by the same discipline as the first.',
    command: 'Today, hold the gate as if there were forty more days ahead. There are. They just start in a different way.',
    practice: 'Perform every element of the day with full attention. Today is one of the many days, not a special one.',
    forgeChallenge: 'Complete one Forge act today equal in intensity to the early arc 6 days. No coasting.',
    journalPrompt: 'What does today require of me that has nothing to do with the milestone tomorrow?',
    eveningAccount: 'Was today held with the same attention as day five, day twenty, day fifty?',
    seal: 'The final gate is kept by the same discipline as the first.',
    contentStatus: 'final',
    relatedStudyIds: [],
    relatedPrincipleIds: ['guard-the-gates', 'hold-the-fire'],
    milestoneRiteId: null, safetyGuardrail: null,
  },
  {
    id: 'day-90', dayNumber: 90, arcNumber: 9, arcTitle: 'The Crown',
    title: 'The Crown of Command', theme: 'ninety-day milestone, crown received',
    season: 'the_integrated_man', archetype: 'sovereign',
    openingLine: 'Ninety days does not make a man finished. It proves he can be formed.',
    teachingBody:
      "Ninety days. Long enough for a discipline to take root. Long enough for the man to know, by direct evidence, that he is capable of carrying a chosen word through ninety daily tests. Long enough to have collected real Crown Fragments — phrases that the practice itself put into his Codex.\n\nThe crown is not the end. It is the recognition of what has been formed. The man is not finished. He is formed enough to be trusted with what comes next: the Long Path, the responsibility of carrying the fire without the daily structure of the rite, the work of being the man this practice has been making.\n\nNo medical claim. No promise of permanent victory. No suggestion that desire is gone. Only this: a chosen word has been held under live conditions for ninety days. That is not nothing. That is the proof a man can be formed. The crown belongs to the man who has stood in this for ninety days. Receive it. Then begin the Long Path.",
    secretContentType: 'crown_fragment', secretTitle: 'Crown Fragment',
    secretBody: "Ninety days. The rite closes. This final fragment belongs in your Codex and on your crown: ninety days proves the man can be formed. The crown is responsibility. The crown is not a trophy to display. It is the equipment of a formed man — quiet, durable, used. Carry it into the Long Path. The work continues, in a different rhythm but in the same essential direction. Strength shared. Fire directed. The compulsion known. The man undivided. Welcome to the rest of the work.",
    crownFragment: 'Ninety days proves the man can be formed. The crown is responsibility.',
    command: 'Receive the crown. Then begin the Long Path with the same discipline that produced it.',
    practice: 'Read the Crown Rite. Acknowledge what has been formed. Begin the Long Path tomorrow.',
    forgeChallenge: 'Complete one substantial act today worthy of a man wearing a crown that is commission, not reward.',
    journalPrompt: 'What man is being crowned today? Who was the man on day one? What is the difference?',
    eveningAccount: 'Was today honored? Is the man who held this rite ready for what comes after?',
    seal: 'Ninety days proves the man can be formed. The crown is responsibility.',
    contentStatus: 'final',
    relatedStudyIds: ['the-inner-forge-transmutation', 'brahmacharya-vow-and-attention'],
    relatedPrincipleIds: ['energy-is-ally', 'compulsion-is-enemy', 'pause-is-where-manhood-begins', 'hold-the-fire', 'return-to-order'],
    milestoneRiteId: 'rite-day-90', safetyGuardrail: null,
  },
];
