export const trials = [
  // ─── Arc 1: The Vow (Days 1–10) — foundation ───────────────────────────────
  {
    id: 'trial-day-01',
    dayNumber: 1,
    arcNumber: 1,
    name: 'The Covenant',
    tier: 'foundation',
    objectives: [
      { id: 'obj-01-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-01-2', kind: 'log_pause', label: 'Observe one urge without acting' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The vow is not a feeling. It is a direction chosen.',
  },
  {
    id: 'trial-day-02',
    dayNumber: 2,
    arcNumber: 1,
    name: 'First Fire',
    tier: 'foundation',
    objectives: [
      { id: 'obj-02-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Naming the reason plants the root before the storm arrives.',
  },
  {
    id: 'trial-day-03',
    dayNumber: 3,
    arcNumber: 1,
    name: 'The Witness',
    tier: 'foundation',
    objectives: [
      { id: 'obj-03-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-03-2', kind: 'log_pause', label: 'Observe one urge without acting' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'To watch the wave is already to stand above it.',
  },
  {
    id: 'trial-day-04',
    dayNumber: 4,
    arcNumber: 1,
    name: 'Ground Taken',
    tier: 'foundation',
    objectives: [
      { id: 'obj-04-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-04-3', kind: 'log_pause', label: 'Complete one Pause session', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Every day held is ground the compulsion did not take.',
  },
  {
    id: 'trial-day-05',
    dayNumber: 5,
    arcNumber: 1,
    name: 'The Breath',
    tier: 'foundation',
    objectives: [
      { id: 'obj-05-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-05-2', kind: 'log_pause', label: 'Use the Pause to breathe through pressure' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The breath is the oldest tool. It has never failed a patient man.',
  },
  {
    id: 'trial-day-06',
    dayNumber: 6,
    arcNumber: 1,
    name: 'Voice Named',
    tier: 'foundation',
    objectives: [
      { id: 'obj-06-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'What you can name, you can meet. What you cannot name, meets you.',
  },
  {
    id: 'trial-day-07',
    dayNumber: 7,
    arcNumber: 1,
    name: 'Seven Days',
    tier: 'foundation',
    objectives: [
      { id: 'obj-07-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-07-2', kind: 'forge_act', label: 'Complete one Forge Act in body or mind' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-7',
    flavor: 'Seven days of practice is a week of becoming a different man.',
  },
  {
    id: 'trial-day-08',
    dayNumber: 8,
    arcNumber: 1,
    name: 'Quiet Before',
    tier: 'foundation',
    objectives: [
      { id: 'obj-08-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-08-2', kind: 'log_pause', label: 'Observe an urge in its earliest form' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The earlier you see it, the less force it takes to redirect.',
  },
  {
    id: 'trial-day-09',
    dayNumber: 9,
    arcNumber: 1,
    name: 'The Return Path',
    tier: 'foundation',
    objectives: [
      { id: 'obj-09-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-09-3', kind: 'log_pause', label: 'Complete one Pause session', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Tomorrow is already being built by the choices made tonight.',
  },
  {
    id: 'trial-day-10',
    dayNumber: 10,
    arcNumber: 1,
    name: 'Arc Closed',
    tier: 'foundation',
    objectives: [
      { id: 'obj-10-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'The first arc asked you to show up. You answered.',
  },

  // ─── Arc 2: Guard the Gates (Days 11–20) — foundation ──────────────────────
  {
    id: 'trial-day-11',
    dayNumber: 11,
    arcNumber: 2,
    name: 'The Gates',
    tier: 'foundation',
    objectives: [
      { id: 'obj-11-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The gates of attention are the first battlefield. Guard them first.',
  },
  {
    id: 'trial-day-12',
    dayNumber: 12,
    arcNumber: 2,
    name: 'What Enters',
    tier: 'foundation',
    objectives: [
      { id: 'obj-12-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-12-2', kind: 'log_pause', label: 'Log a moment when something pulled at your attention' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'You cannot unsee what you let in. Choose the door carefully.',
  },
  {
    id: 'trial-day-13',
    dayNumber: 13,
    arcNumber: 2,
    name: 'Gate Held',
    tier: 'foundation',
    objectives: [
      { id: 'obj-13-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-13-3', kind: 'log_pause', label: 'Log one pull resisted', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'A gate held once teaches the hands to hold it again.',
  },
  {
    id: 'trial-day-14',
    dayNumber: 14,
    arcNumber: 2,
    name: 'Two Weeks',
    tier: 'foundation',
    objectives: [
      { id: 'obj-14-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-14-2', kind: 'forge_act', label: 'Complete one Forge Act of your choice' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-14',
    flavor: 'Two weeks is long enough to feel what discipline actually costs.',
  },
  {
    id: 'trial-day-15',
    dayNumber: 15,
    arcNumber: 2,
    name: 'The Scroll',
    tier: 'foundation',
    objectives: [
      { id: 'obj-15-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Endless scroll is a fog machine. The man who sees it can leave it.',
  },
  {
    id: 'trial-day-16',
    dayNumber: 16,
    arcNumber: 2,
    name: 'Sound and Silence',
    tier: 'foundation',
    objectives: [
      { id: 'obj-16-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-16-2', kind: 'log_pause', label: 'Notice one moment of chosen silence today' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Silence is not emptiness. It is the space where the self returns.',
  },
  {
    id: 'trial-day-17',
    dayNumber: 17,
    arcNumber: 2,
    name: 'The Watch',
    tier: 'foundation',
    objectives: [
      { id: 'obj-17-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Evening is when the gates are weakest. This is when the practice earns its keep.',
  },
  {
    id: 'trial-day-18',
    dayNumber: 18,
    arcNumber: 2,
    name: 'Threshold Kept',
    tier: 'foundation',
    objectives: [
      { id: 'obj-18-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-18-2', kind: 'log_pause', label: 'Log one urge that passed without action' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Urges that pass are not victories over the body. They are trust built with it.',
  },
  {
    id: 'trial-day-19',
    dayNumber: 19,
    arcNumber: 2,
    name: 'The Sentinel',
    tier: 'foundation',
    objectives: [
      { id: 'obj-19-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The sentinel is not tense. He is simply present at his post.',
  },
  {
    id: 'trial-day-20',
    dayNumber: 20,
    arcNumber: 2,
    name: 'Gates Sealed',
    tier: 'foundation',
    objectives: [
      { id: 'obj-20-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'Twenty days. The gates you ignored before are now ones you know by name.',
  },

  // ─── Arc 3: The Body Returns (Days 21–30) — foundation ─────────────────────
  {
    id: 'trial-day-21',
    dayNumber: 21,
    arcNumber: 3,
    name: 'The Body Speaks',
    tier: 'foundation',
    objectives: [
      { id: 'obj-21-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-21-2', kind: 'forge_act', label: 'Complete one physical Forge Act' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-21',
    flavor: 'Three weeks in, the body begins to speak a different language.',
  },
  {
    id: 'trial-day-22',
    dayNumber: 22,
    arcNumber: 3,
    name: 'Moved by Fire',
    tier: 'foundation',
    objectives: [
      { id: 'obj-22-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-22-2', kind: 'forge_act', label: 'Move your body: train, walk, lift, or stretch' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The energy wants to move. Give it a direction and it becomes strength.',
  },
  {
    id: 'trial-day-23',
    dayNumber: 23,
    arcNumber: 3,
    name: 'The Forge Begins',
    tier: 'foundation',
    objectives: [
      { id: 'obj-23-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-23-2', kind: 'forge_act', label: 'Complete one Forge Act in any category' },
      { id: 'obj-23-3', kind: 'log_pause', label: 'Observe the energy present after the act', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The Forge Act is not productivity. It is alchemy.',
  },
  {
    id: 'trial-day-24',
    dayNumber: 24,
    arcNumber: 3,
    name: 'Rest and Rise',
    tier: 'foundation',
    objectives: [
      { id: 'obj-24-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-24-2', kind: 'forge_act', label: 'Complete one recovery or rest act intentionally' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Rest chosen is not weakness. It is the next rep prepared.',
  },
  {
    id: 'trial-day-25',
    dayNumber: 25,
    arcNumber: 3,
    name: 'The Living Temple',
    tier: 'foundation',
    objectives: [
      { id: 'obj-25-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-25-2', kind: 'forge_act', label: 'Nourish or train the body with intention' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The body is not a tool to be used. It is the home the practice lives in.',
  },
  {
    id: 'trial-day-26',
    dayNumber: 26,
    arcNumber: 3,
    name: 'Cold and Clear',
    tier: 'foundation',
    objectives: [
      { id: 'obj-26-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-26-2', kind: 'forge_act', label: 'Do one act that requires physical discomfort' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Chosen discomfort is the body learning that it can be trusted.',
  },
  {
    id: 'trial-day-27',
    dayNumber: 27,
    arcNumber: 3,
    name: 'Hands at Work',
    tier: 'foundation',
    objectives: [
      { id: 'obj-27-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-27-2', kind: 'forge_act', label: 'Build, fix, or create something with your hands' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'When the hands are busy making, they are not reaching for what numbs.',
  },
  {
    id: 'trial-day-28',
    dayNumber: 28,
    arcNumber: 3,
    name: 'Breath and Steel',
    tier: 'foundation',
    objectives: [
      { id: 'obj-28-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-28-2', kind: 'forge_act', label: 'Complete a physical Forge Act' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Breathe in before the lift. Let the exhale carry what does not serve.',
  },
  {
    id: 'trial-day-29',
    dayNumber: 29,
    arcNumber: 3,
    name: 'The Body Knows',
    tier: 'foundation',
    objectives: [
      { id: 'obj-29-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The body keeps score. It also keeps receipts for the work you put in.',
  },
  {
    id: 'trial-day-30',
    dayNumber: 30,
    arcNumber: 3,
    name: 'Thirty',
    tier: 'foundation',
    objectives: [
      { id: 'obj-30-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-30-2', kind: 'forge_act', label: 'Complete one significant Forge Act to mark the month' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-30',
    flavor: 'Thirty days is not a streak. It is a new floor.',
  },

  // ─── Arc 4: The Discipline of Assent (Days 31–40) — discipline ──────────────
  {
    id: 'trial-day-31',
    dayNumber: 31,
    arcNumber: 4,
    name: 'The Assent',
    tier: 'discipline',
    objectives: [
      { id: 'obj-31-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-31-2', kind: 'log_pause', label: 'Observe one impulse and choose deliberately' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Between impulse and action lives the one moment that defines character.',
  },
  {
    id: 'trial-day-32',
    dayNumber: 32,
    arcNumber: 4,
    name: 'What You Choose',
    tier: 'discipline',
    objectives: [
      { id: 'obj-32-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-32-2', kind: 'log_pause', label: 'Log a moment of deliberate choice under pressure' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'You are not responsible for the impulse. Only for what you do next.',
  },
  {
    id: 'trial-day-33',
    dayNumber: 33,
    arcNumber: 4,
    name: 'The Gap',
    tier: 'discipline',
    objectives: [
      { id: 'obj-33-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-33-2', kind: 'log_pause', label: 'Use the Pause to widen the gap before responding' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The pause between stimulus and response is where freedom lives.',
  },
  {
    id: 'trial-day-34',
    dayNumber: 34,
    arcNumber: 4,
    name: 'Ruled by Nothing',
    tier: 'discipline',
    objectives: [
      { id: 'obj-34-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-34-2', kind: 'log_pause', label: 'Observe one craving without feeding or fighting it' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The man who is ruled by nothing has mastered the first throne.',
  },
  {
    id: 'trial-day-35',
    dayNumber: 35,
    arcNumber: 4,
    name: 'Still Waters',
    tier: 'discipline',
    objectives: [
      { id: 'obj-35-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-35-2', kind: 'log_pause', label: 'Complete one Pause when agitation is present' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Agitation is the surface. The practice learns the depth below it.',
  },
  {
    id: 'trial-day-36',
    dayNumber: 36,
    arcNumber: 4,
    name: 'No and Know',
    tier: 'discipline',
    objectives: [
      { id: 'obj-36-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-36-2', kind: 'log_pause', label: 'Say no to one habitual pull today and log it' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Each no to the lesser makes room for the yes that matters.',
  },
  {
    id: 'trial-day-37',
    dayNumber: 37,
    arcNumber: 4,
    name: 'The Inner Vote',
    tier: 'discipline',
    objectives: [
      { id: 'obj-37-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-37-2', kind: 'log_pause', label: 'Notice an internal argument and log the outcome' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Every internal debate is a vote for who you are becoming.',
  },
  {
    id: 'trial-day-38',
    dayNumber: 38,
    arcNumber: 4,
    name: 'Even Keel',
    tier: 'discipline',
    objectives: [
      { id: 'obj-38-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-38-2', kind: 'log_pause', label: 'Maintain equanimity through one difficulty today' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The boat does not fight the water. It holds its line through it.',
  },
  {
    id: 'trial-day-39',
    dayNumber: 39,
    arcNumber: 4,
    name: 'Chosen Silence',
    tier: 'discipline',
    objectives: [
      { id: 'obj-39-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-39-2', kind: 'log_pause', label: 'Practice one period of deliberate, chosen silence' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Silence chosen is power held. Silence forced is pressure building.',
  },
  {
    id: 'trial-day-40',
    dayNumber: 40,
    arcNumber: 4,
    name: 'The Governed Man',
    tier: 'discipline',
    objectives: [
      { id: 'obj-40-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'Forty days of assent. The governed man is not restrained — he is free.',
  },

  // ─── Arc 5: The Inner Kingdom (Days 41–50) — discipline ─────────────────────
  {
    id: 'trial-day-41',
    dayNumber: 41,
    arcNumber: 5,
    name: 'The Inner Court',
    tier: 'discipline',
    objectives: [
      { id: 'obj-41-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-41-2', kind: 'forge_act', label: 'Do one act that builds your inner world' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Outer kingdoms fall. The inner kingdom is the one worth ruling.',
  },
  {
    id: 'trial-day-42',
    dayNumber: 42,
    arcNumber: 5,
    name: 'The King\'s Table',
    tier: 'discipline',
    objectives: [
      { id: 'obj-42-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'A kingdom without stated values is ruled by whoever shouts loudest.',
  },
  {
    id: 'trial-day-43',
    dayNumber: 43,
    arcNumber: 5,
    name: 'The Throne Room',
    tier: 'discipline',
    objectives: [
      { id: 'obj-43-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-43-2', kind: 'forge_act', label: 'Complete one act of order or creation' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Order begins inside before it can be imposed on anything outside.',
  },
  {
    id: 'trial-day-44',
    dayNumber: 44,
    arcNumber: 5,
    name: 'The Map',
    tier: 'discipline',
    objectives: [
      { id: 'obj-44-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The man without a map wanders. The man with one walks with purpose.',
  },
  {
    id: 'trial-day-45',
    dayNumber: 45,
    arcNumber: 5,
    name: 'Halfway',
    tier: 'discipline',
    objectives: [
      { id: 'obj-45-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-45-2', kind: 'forge_act', label: 'Complete one meaningful Forge Act to mark the midpoint' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-45',
    flavor: 'You are halfway. The second half is built on what the first half taught.',
  },
  {
    id: 'trial-day-46',
    dayNumber: 46,
    arcNumber: 5,
    name: 'The Chancellor',
    tier: 'discipline',
    objectives: [
      { id: 'obj-46-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-46-2', kind: 'forge_act', label: 'Advise, mentor, or contribute to someone else\'s growth' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The kingdom that hoards its wisdom starves its own future.',
  },
  {
    id: 'trial-day-47',
    dayNumber: 47,
    arcNumber: 5,
    name: 'The Treasury',
    tier: 'discipline',
    objectives: [
      { id: 'obj-47-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Count the treasury clearly. Gratitude is not weakness — it is accounting.',
  },
  {
    id: 'trial-day-48',
    dayNumber: 48,
    arcNumber: 5,
    name: 'The Counselor',
    tier: 'discipline',
    objectives: [
      { id: 'obj-48-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-48-2', kind: 'forge_act', label: 'Write, read, or study something that sharpens the mind' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The king who stops learning prepares his own unraveling.',
  },
  {
    id: 'trial-day-49',
    dayNumber: 49,
    arcNumber: 5,
    name: 'The Keep',
    tier: 'discipline',
    objectives: [
      { id: 'obj-49-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'What you protect defines what you value. Review the walls.',
  },
  {
    id: 'trial-day-50',
    dayNumber: 50,
    arcNumber: 5,
    name: 'Kingdom Standing',
    tier: 'discipline',
    objectives: [
      { id: 'obj-50-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'Fifty days. The inner kingdom is not finished. But it is standing.',
  },

  // ─── Arc 6: The Forge (Days 51–60) — discipline ──────────────────────────────
  {
    id: 'trial-day-51',
    dayNumber: 51,
    arcNumber: 6,
    name: 'Into the Fire',
    tier: 'discipline',
    objectives: [
      { id: 'obj-51-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-51-2', kind: 'forge_act', label: 'Complete one Forge Act with full intention' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The Forge does not destroy the metal. It reveals what it always was.',
  },
  {
    id: 'trial-day-52',
    dayNumber: 52,
    arcNumber: 6,
    name: 'The Hammer',
    tier: 'discipline',
    objectives: [
      { id: 'obj-52-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-52-2', kind: 'forge_act', label: 'Do one hard physical act without negotiating yourself out of it' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The hammer does not question the work. It simply strikes true.',
  },
  {
    id: 'trial-day-53',
    dayNumber: 53,
    arcNumber: 6,
    name: 'The Crucible',
    tier: 'discipline',
    objectives: [
      { id: 'obj-53-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-53-2', kind: 'forge_act', label: 'Begin or advance a creative project' },
      { id: 'obj-53-3', kind: 'log_pause', label: 'Notice resistance and stay with the work anyway', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Resistance to creation is energy in the wrong direction. Turn it.',
  },
  {
    id: 'trial-day-54',
    dayNumber: 54,
    arcNumber: 6,
    name: 'Made by Hand',
    tier: 'discipline',
    objectives: [
      { id: 'obj-54-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-54-2', kind: 'forge_act', label: 'Build, write, cook, repair, or create something tangible' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The thing made by hand carries the energy of the maker. Forge well.',
  },
  {
    id: 'trial-day-55',
    dayNumber: 55,
    arcNumber: 6,
    name: 'The Transmutation',
    tier: 'discipline',
    objectives: [
      { id: 'obj-55-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-55-2', kind: 'forge_act', label: 'Channel restless energy into purposeful Forge Act' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Transmutation is not suppression. It is redirection toward what lives.',
  },
  {
    id: 'trial-day-56',
    dayNumber: 56,
    arcNumber: 6,
    name: 'Two Forges',
    tier: 'discipline',
    objectives: [
      { id: 'obj-56-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-56-2', kind: 'forge_act', label: 'Complete one mental and one physical Forge Act' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The forge that works on both mind and body leaves nothing unattended.',
  },
  {
    id: 'trial-day-57',
    dayNumber: 57,
    arcNumber: 6,
    name: 'The Artisan',
    tier: 'discipline',
    objectives: [
      { id: 'obj-57-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-57-2', kind: 'forge_act', label: 'Work with craftsmanship: do one thing with complete attention' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The artisan does not rush the work. The work teaches the artisan.',
  },
  {
    id: 'trial-day-58',
    dayNumber: 58,
    arcNumber: 6,
    name: 'The Output',
    tier: 'discipline',
    objectives: [
      { id: 'obj-58-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-58-2', kind: 'forge_act', label: 'Ship, submit, send, or finish one project or piece of work' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The work that stays inside does not serve. Complete it and release it.',
  },
  {
    id: 'trial-day-59',
    dayNumber: 59,
    arcNumber: 6,
    name: 'Forge Day',
    tier: 'discipline',
    objectives: [
      { id: 'obj-59-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-59-2', kind: 'forge_act', label: 'Dedicate at least one hour to a meaningful Forge Act' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'One hour of deep work is worth more than a day of scattered motion.',
  },
  {
    id: 'trial-day-60',
    dayNumber: 60,
    arcNumber: 6,
    name: 'The Forged Man',
    tier: 'discipline',
    objectives: [
      { id: 'obj-60-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-60-2', kind: 'forge_act', label: 'Complete one significant Forge Act to mark the arc' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-60',
    flavor: 'Sixty days. The fire has been burning long enough to show you what you are made of.',
  },

  // ─── Arc 7: Brotherhood and Service (Days 61–70) — mastery ──────────────────
  {
    id: 'trial-day-61',
    dayNumber: 61,
    arcNumber: 7,
    name: 'The Brother',
    tier: 'mastery',
    objectives: [
      { id: 'obj-61-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Brotherhood is not competition. It is the practice witnessed and matched.',
  },
  {
    id: 'trial-day-62',
    dayNumber: 62,
    arcNumber: 7,
    name: 'Given Forward',
    tier: 'mastery',
    objectives: [
      { id: 'obj-62-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'You cannot give from an empty vessel. Guard the source of your giving.',
  },
  {
    id: 'trial-day-63',
    dayNumber: 63,
    arcNumber: 7,
    name: 'The Servant King',
    tier: 'mastery',
    objectives: [
      { id: 'obj-63-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The man who serves from strength is not depleted by it.',
  },
  {
    id: 'trial-day-64',
    dayNumber: 64,
    arcNumber: 7,
    name: 'The Council',
    tier: 'mastery',
    objectives: [
      { id: 'obj-64-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The man without trusted counsel governs his life on guesswork alone.',
  },
  {
    id: 'trial-day-65',
    dayNumber: 65,
    arcNumber: 7,
    name: 'Accountability',
    tier: 'mastery',
    objectives: [
      { id: 'obj-65-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Accountability is not surveillance. It is the practice made visible.',
  },
  {
    id: 'trial-day-66',
    dayNumber: 66,
    arcNumber: 7,
    name: 'The Gift',
    tier: 'mastery',
    objectives: [
      { id: 'obj-66-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The fire does not diminish when it lights another candle.',
  },
  {
    id: 'trial-day-67',
    dayNumber: 67,
    arcNumber: 7,
    name: 'Side by Side',
    tier: 'mastery',
    objectives: [
      { id: 'obj-67-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Men do not inspire each other by talking about themselves. They do it by working.',
  },
  {
    id: 'trial-day-68',
    dayNumber: 68,
    arcNumber: 7,
    name: 'The Legacy',
    tier: 'mastery',
    objectives: [
      { id: 'obj-68-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Legacy is not a monument. It is the character impressed on those who knew you.',
  },
  {
    id: 'trial-day-69',
    dayNumber: 69,
    arcNumber: 7,
    name: 'The Lodge',
    tier: 'mastery',
    objectives: [
      { id: 'obj-69-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The lodge is not a club. It is the place where serious men hold each other to the work.',
  },
  {
    id: 'trial-day-70',
    dayNumber: 70,
    arcNumber: 7,
    name: 'Brotherhood Sealed',
    tier: 'mastery',
    objectives: [
      { id: 'obj-70-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'Seventy days. You have served, reflected, and remained. That is the arc of a man.',
  },

  // ─── Arc 8: The Shadow and Return (Days 71–80) — mastery ────────────────────
  {
    id: 'trial-day-71',
    dayNumber: 71,
    arcNumber: 8,
    name: 'The Shadow',
    tier: 'mastery',
    objectives: [
      { id: 'obj-71-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The shadow is not the enemy. It is the part of you that has not yet been heard.',
  },
  {
    id: 'trial-day-72',
    dayNumber: 72,
    arcNumber: 8,
    name: 'What Returns',
    tier: 'mastery',
    objectives: [
      { id: 'obj-72-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-72-2', kind: 'log_pause', label: 'Observe a recurring urge or pattern without judgment' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'What keeps returning is asking to be understood, not defeated.',
  },
  {
    id: 'trial-day-73',
    dayNumber: 73,
    arcNumber: 8,
    name: 'The Descent',
    tier: 'mastery',
    objectives: [
      { id: 'obj-73-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-73-3', kind: 'log_pause', label: 'Pause with whatever discomfort you find there', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Descent without shame is the beginning of genuine understanding.',
  },
  {
    id: 'trial-day-74',
    dayNumber: 74,
    arcNumber: 8,
    name: 'The Mirror',
    tier: 'mastery',
    objectives: [
      { id: 'obj-74-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The mirror does not lie, and it does not judge. Look without flinching.',
  },
  {
    id: 'trial-day-75',
    dayNumber: 75,
    arcNumber: 8,
    name: 'The Return',
    tier: 'mastery',
    objectives: [
      { id: 'obj-75-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-75-2', kind: 'forge_act', label: 'Complete a Forge Act as an act of return and recommitment' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-75',
    flavor: 'The return is never a failure. It is the proof that the practice is real.',
  },
  {
    id: 'trial-day-76',
    dayNumber: 76,
    arcNumber: 8,
    name: 'Named and Known',
    tier: 'mastery',
    objectives: [
      { id: 'obj-76-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-76-2', kind: 'log_pause', label: 'Name a shadow pattern during a Pause session' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'To name the shadow is not to be freed from it. It is to no longer be surprised by it.',
  },
  {
    id: 'trial-day-77',
    dayNumber: 77,
    arcNumber: 8,
    name: 'The Integration',
    tier: 'mastery',
    objectives: [
      { id: 'obj-77-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-77-3', kind: 'log_pause', label: 'Sit with the complexity without trying to resolve it', optional: true },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Integration is not resolution. It is the shadow and the light agreeing to coexist.',
  },
  {
    id: 'trial-day-78',
    dayNumber: 78,
    arcNumber: 8,
    name: 'The Night Work',
    tier: 'mastery',
    objectives: [
      { id: 'obj-78-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-78-2', kind: 'log_pause', label: 'Complete an evening Pause and observe what surfaces in the quiet' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The night reveals what the day was too busy to show.',
  },
  {
    id: 'trial-day-79',
    dayNumber: 79,
    arcNumber: 8,
    name: 'The Reconciled Man',
    tier: 'mastery',
    objectives: [
      { id: 'obj-79-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Peace with yourself is not weakness. It is the foundation all else is built upon.',
  },
  {
    id: 'trial-day-80',
    dayNumber: 80,
    arcNumber: 8,
    name: 'Shadow Sealed',
    tier: 'mastery',
    objectives: [
      { id: 'obj-80-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 35,
    rewardKeyId: null,
    flavor: 'Eighty days. The shadow work is not finished. But you have stopped running from it.',
  },

  // ─── Arc 9: The Crown (Days 81–90) — mastery ────────────────────────────────
  {
    id: 'trial-day-81',
    dayNumber: 81,
    arcNumber: 9,
    name: 'The Final Arc',
    tier: 'mastery',
    objectives: [
      { id: 'obj-81-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-81-2', kind: 'forge_act', label: 'Complete one Forge Act worthy of the arc you are closing' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Nine arcs. The last one does not ask you to become someone new. It asks you to arrive.',
  },
  {
    id: 'trial-day-82',
    dayNumber: 82,
    arcNumber: 9,
    name: 'The Full Circle',
    tier: 'mastery',
    objectives: [
      { id: 'obj-82-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The full circle is not a return to the start. It is the same place, seen differently.',
  },
  {
    id: 'trial-day-83',
    dayNumber: 83,
    arcNumber: 9,
    name: 'The Vow Renewed',
    tier: 'mastery',
    objectives: [
      { id: 'obj-83-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-83-2', kind: 'log_pause', label: 'Return to the Pause with the gravity of eighty-three days behind you' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The vow on day eighty-three is heavier and lighter than the one on day one.',
  },
  {
    id: 'trial-day-84',
    dayNumber: 84,
    arcNumber: 9,
    name: 'The Man in Full',
    tier: 'mastery',
    objectives: [
      { id: 'obj-84-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The man in full is not perfect. He is practiced, aware, and still choosing.',
  },
  {
    id: 'trial-day-85',
    dayNumber: 85,
    arcNumber: 9,
    name: 'The Offering',
    tier: 'mastery',
    objectives: [
      { id: 'obj-85-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-85-2', kind: 'forge_act', label: 'Do one Forge Act as an offering — not for yourself alone' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The offering is not sacrifice. It is abundance finding its destination.',
  },
  {
    id: 'trial-day-86',
    dayNumber: 86,
    arcNumber: 9,
    name: 'The Evening Account',
    tier: 'mastery',
    objectives: [
      { id: 'obj-86-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'At the end of every good day, the honest man knows what he did with it.',
  },
  {
    id: 'trial-day-87',
    dayNumber: 87,
    arcNumber: 9,
    name: 'The Quiet Crown',
    tier: 'mastery',
    objectives: [
      { id: 'obj-87-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-87-2', kind: 'log_pause', label: 'Sit in the Pause with nothing to prove' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The quiet crown needs no audience. Its weight is felt only by the one who wears it.',
  },
  {
    id: 'trial-day-88',
    dayNumber: 88,
    arcNumber: 9,
    name: 'The Threshold',
    tier: 'mastery',
    objectives: [
      { id: 'obj-88-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'The threshold is not the end. It is the door into what the practice was preparing you for.',
  },
  {
    id: 'trial-day-89',
    dayNumber: 89,
    arcNumber: 9,
    name: 'Almost',
    tier: 'mastery',
    objectives: [
      { id: 'obj-89-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
    ],
    rewardEmbers: 25,
    rewardKeyId: null,
    flavor: 'Tomorrow is not a finish line. It is the first day of the rest of the practice.',
  },
  {
    id: 'trial-day-90',
    dayNumber: 90,
    arcNumber: 9,
    name: 'Ninety',
    tier: 'mastery',
    objectives: [
      { id: 'obj-90-1', kind: 'reveal_secret', label: 'Reveal the day\'s teaching' },
      { id: 'obj-90-2', kind: 'forge_act', label: 'Complete one defining Forge Act on this final arc day' },
    ],
    rewardEmbers: 50,
    rewardKeyId: 'rite-day-90',
    flavor: 'Ninety days does not make a perfect man. It makes a man who chose, again and again.',
  },

  // ─── Crown Trial (Post-Day-90) — sovereign ──────────────────────────────────
  {
    id: 'trial-crown',
    dayNumber: 'crown',
    arcNumber: null,
    name: 'The Sovereign',
    tier: 'sovereign',
    objectives: [
      { id: 'obj-crown-1', kind: 'reveal_secret', label: 'Reveal the crown teaching' },
      { id: 'obj-crown-2', kind: 'forge_act', label: 'Complete one sovereign Forge Act: your highest contribution' },
    ],
    rewardEmbers: 100,
    rewardKeyId: null,
    flavor: 'The sovereign does not need a streak. He carries the practice in his character.',
  },
] as const;

export default trials;
